-- Regression tests for Stage 1 of the recurring-session occurrence-identity redesign
-- (20261001150000_session_series_occurrence_identity_stage1.sql).
--
-- Covers the two real production incidents (2026-10-04 coach change Lotem->Shira,
-- 2026-10-06 time change 18:00->19:00) via structurally equivalent synthetic fixtures, plus
-- multi-candidate ownership, idempotency, and physical-slot-conflict handling. All fixtures
-- use far-future dates and real existing coach/profile ids to avoid colliding with seeded or
-- production-like data in this test database.
--
-- Each test was independently verified (same structure) against live production in a
-- rolled-back transaction before this migration was applied; see the engagement's forensic
-- and design-review record for the full derivation.
set client_min_messages to notice;

-- TEST 1: coach change -- edited occurrence remains, original coach is never regenerated by a
-- colliding sibling series, ownership stays with the edited series.
do $$
declare
  v_coach1 uuid; v_coach2 uuid; v_manager uuid;
  v_series_a uuid; v_series_b uuid; v_sess_a uuid; v_res json; v_claim_result text; v_count int;
begin
  select v into v_coach1 from _test_ids where k='coach';
  select v into v_manager from _test_ids where k='manager';
  v_coach2 := v_manager; -- a distinct real profile usable as an alternate coach_id

  perform set_config('app.current_uid', v_manager::text, true);

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, current_date + 801, '18:00', 6, 'ongoing', 'active') returning id into v_series_a;
  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, current_date + 808, '18:00', 6, 'ongoing', 'active') returning id into v_series_b;

  perform _generate_series_occurrence_claim(v_series_a, current_date + 801);
  select id into v_sess_a from training_sessions where series_id = v_series_a and session_date = current_date + 801;
  if v_sess_a is null then raise exception 'TEST1 SETUP FAILED: series A occurrence not created'; end if;

  select staff_update_session_series_scope(v_sess_a, 'this', current_date+801, '18:00', v_coach2, 6, 60, false, false, false, null) into v_res;
  if not (v_res->>'ok')::boolean then raise exception 'TEST1 FAILED: edit rejected: %', v_res; end if;

  v_claim_result := _generate_series_occurrence_claim(v_series_b, current_date + 801);
  if v_claim_result <> 'series_logical_conflict' then
    raise exception 'TEST1 FAILED: expected series_logical_conflict, got %', v_claim_result;
  end if;

  if not exists (select 1 from training_sessions where id = v_sess_a and coach_id = v_coach2) then
    raise exception 'TEST1 FAILED: edited session missing or reverted';
  end if;
  if exists (select 1 from training_sessions where session_date = current_date+801 and start_time='18:00' and coach_id = v_coach1) then
    raise exception 'TEST1 FAILED: original-coach ghost was created -- this is the 2026-10-04 incident recurring';
  end if;
  select count(*) into v_count from training_sessions
  where session_date = current_date+801 and start_time='18:00' and coach_id in (v_coach1, v_coach2);
  if v_count <> 1 then raise exception 'TEST1 FAILED: expected exactly 1 session, found %', v_count; end if;

  raise notice 'TEST1 PASSED: coach-change regression (Lotem->Shira structure) blocked correctly';
end $$;

-- TEST 2: time change -- edited occurrence remains at the new time, original time slot is
-- never regenerated by a colliding sibling series.
do $$
declare
  v_coach1 uuid; v_manager uuid;
  v_series_a uuid; v_series_b uuid; v_sess_a uuid; v_res json; v_claim_result text; v_count int;
begin
  select v into v_coach1 from _test_ids where k='coach';
  select v into v_manager from _test_ids where k='manager';
  perform set_config('app.current_uid', v_manager::text, true);

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, current_date + 802, '18:00', 6, 'ongoing', 'active') returning id into v_series_a;
  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, current_date + 809, '18:00', 6, 'ongoing', 'active') returning id into v_series_b;

  perform _generate_series_occurrence_claim(v_series_a, current_date + 802);
  select id into v_sess_a from training_sessions where series_id = v_series_a and session_date = current_date + 802;
  if v_sess_a is null then raise exception 'TEST2 SETUP FAILED: series A occurrence not created'; end if;

  select staff_update_session_series_scope(v_sess_a, 'this', current_date+802, '19:00', v_coach1, 6, 60, false, false, false, null) into v_res;
  if not (v_res->>'ok')::boolean then raise exception 'TEST2 FAILED: edit rejected: %', v_res; end if;

  v_claim_result := _generate_series_occurrence_claim(v_series_b, current_date + 802);
  if v_claim_result <> 'series_logical_conflict' then
    raise exception 'TEST2 FAILED: expected series_logical_conflict, got %', v_claim_result;
  end if;

  if not exists (select 1 from training_sessions where id = v_sess_a and start_time = '19:00') then
    raise exception 'TEST2 FAILED: edited session missing or reverted';
  end if;
  if exists (select 1 from training_sessions where session_date = current_date+802 and start_time='18:00' and coach_id = v_coach1) then
    raise exception 'TEST2 FAILED: original-time ghost was created -- this is the 2026-10-06 incident recurring';
  end if;
  select count(*) into v_count from training_sessions where session_date = current_date+802 and coach_id = v_coach1;
  if v_count <> 1 then raise exception 'TEST2 FAILED: expected exactly 1 session, found %', v_count; end if;

  raise notice 'TEST2 PASSED: time-change regression (18:00->19:00 structure) blocked correctly';
end $$;

-- TEST 3: multi-candidate unowned slot -- two eligible active series, neither has an existing
-- owner; generator iteration order must not decide ownership.
do $$
declare
  v_coach1 uuid; v_manager uuid;
  v_series_c uuid; v_series_d uuid; v_target_date date := current_date + 9;
  v_horizon_result json; v_evt_count int;
begin
  select v into v_coach1 from _test_ids where k='coach';
  select v into v_manager from _test_ids where k='manager';
  perform set_config('app.current_uid', v_manager::text, true);

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target_date, '23:33', 6, 'ongoing', 'active') returning id into v_series_c;
  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target_date - 7, '23:33', 6, 'ongoing', 'active') returning id into v_series_d;

  select _maintain_session_series_horizon_core() into v_horizon_result;

  if exists (select 1 from training_sessions where session_date = v_target_date and start_time='23:33' and coach_id = v_coach1) then
    raise exception 'TEST3 FAILED: a session was generated for the unresolved multi-candidate slot';
  end if;
  if exists (select 1 from session_series_occurrences where template_coach_id=v_coach1 and template_start_time='23:33' and template_occurrence_date=v_target_date) then
    raise exception 'TEST3 FAILED: a ledger row was claimed for the unresolved multi-candidate slot';
  end if;
  select count(*) into v_evt_count from user_activity_events
  where event_type='series_unresolved_ownership'
    and metadata->>'template_occurrence_date' = v_target_date::text
    and (metadata->>'template_start_time') = '23:33:00';
  if v_evt_count < 1 then raise exception 'TEST3 FAILED: no series_unresolved_ownership event logged'; end if;

  raise notice 'TEST3 PASSED: multi-candidate slot generated nothing, logged UNRESOLVED_SERIES_OWNERSHIP';
end $$;

-- TEST 4: idempotency -- repeated horizon runs produce no duplicates and never leave a
-- committed state='claimed' row.
do $$
declare v_dupe_count int;
begin
  perform _maintain_session_series_horizon_core();
  perform _maintain_session_series_horizon_core();

  select count(*) into v_dupe_count from (
    select coach_id, session_date, start_time, count(*) from training_sessions
    group by coach_id, session_date, start_time having count(*) > 1
  ) d;
  if v_dupe_count > 0 then raise exception 'TEST4 FAILED: % duplicate physical slots after repeated horizon runs', v_dupe_count; end if;
  if exists (select 1 from session_series_occurrences where state = 'claimed') then
    raise exception 'TEST4 FAILED: a claimed row was left committed';
  end if;

  raise notice 'TEST4 PASSED: idempotent re-runs produced no duplicates, no stuck claimed rows';
end $$;

-- TEST 5: physical-slot conflict -- claim succeeds logically but materialization collides with
-- an unrelated pre-existing session; the failed claim must roll back entirely, and the
-- pre-existing session must be untouched.
do $$
declare
  v_coach1 uuid; v_series_e uuid; v_target_date date := current_date + 803;
  v_blocker_id uuid; v_claim_result text; v_occ_count int;
begin
  select v into v_coach1 from _test_ids where k='coach';

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target_date, '22:15', 6, 'ongoing', 'active') returning id into v_series_e;

  insert into training_sessions (session_date, start_time, coach_id, max_participants, series_id, series_detached)
  values (v_target_date, '22:15', v_coach1, 1, null, false) returning id into v_blocker_id;

  v_claim_result := _generate_series_occurrence_claim(v_series_e, v_target_date);
  if v_claim_result <> 'series_slot_conflict' then
    raise exception 'TEST5 FAILED: expected series_slot_conflict, got %', v_claim_result;
  end if;

  select count(*) into v_occ_count from session_series_occurrences
  where series_id = v_series_e and template_occurrence_date = v_target_date;
  if v_occ_count <> 0 then
    raise exception 'TEST5 FAILED: a ledger row survived the failed materialization attempt (count=%)', v_occ_count;
  end if;
  if not exists (select 1 from training_sessions where id = v_blocker_id) then
    raise exception 'TEST5 FAILED: unrelated pre-existing session was affected';
  end if;
  if not exists (select 1 from user_activity_events where event_type='series_slot_conflict' and target_id=v_series_e::text) then
    raise exception 'TEST5 FAILED: series_slot_conflict was not logged';
  end if;

  raise notice 'TEST5 PASSED: physical-slot conflict rolled back cleanly, no ledger row left, blocker untouched, logged';
end $$;

-- TEST 6: forward-only self-protection -- coach-change edit starting from a LEGACY occurrence
-- that has NO prior ledger row (plain INSERT, bypassing the claim-aware generator entirely, the
-- same shape as every real pre-Stage-1 production session). The edit transaction itself must
-- establish the occurrence's ledger claim; nothing here depends on backfill ever having run.
do $$
declare
  v_coach1 uuid; v_coach2 uuid; v_manager uuid;
  v_series_a uuid; v_series_b uuid; v_sess_a uuid; v_res json; v_claim_result text; v_count int;
  v_target date := current_date + 804;
begin
  select v into v_coach1 from _test_ids where k='coach';
  select v into v_manager from _test_ids where k='manager';
  v_coach2 := v_manager;
  perform set_config('app.current_uid', v_manager::text, true);

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target, '18:00', 6, 'ongoing', 'active') returning id into v_series_a;
  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target - 7, '18:00', 6, 'ongoing', 'active') returning id into v_series_b;

  insert into training_sessions (session_date, start_time, coach_id, max_participants, series_id, series_detached)
  values (v_target, '18:00', v_coach1, 6, v_series_a, false) returning id into v_sess_a;

  if (select series_occurrence_id from training_sessions where id = v_sess_a) is not null then
    raise exception 'TEST6 SETUP FAILED: legacy fixture unexpectedly has a ledger link';
  end if;

  select staff_update_session_series_scope(v_sess_a, 'this', v_target, '18:00', v_coach2, 6, 60, false, false, false, null) into v_res;
  if not (v_res->>'ok')::boolean then raise exception 'TEST6 FAILED: edit rejected: %', v_res; end if;

  if (select series_occurrence_id from training_sessions where id = v_sess_a) is null then
    raise exception 'TEST6 FAILED: edit did not establish a ledger claim for a previously-unlinked legacy session';
  end if;

  v_claim_result := _generate_series_occurrence_claim(v_series_b, v_target);
  if v_claim_result <> 'series_logical_conflict' then
    raise exception 'TEST6 FAILED: expected series_logical_conflict from sibling series, got %', v_claim_result;
  end if;

  if exists (select 1 from training_sessions where session_date = v_target and start_time='18:00' and coach_id = v_coach1) then
    raise exception 'TEST6 FAILED: original-coach ghost was regenerated for a legacy edited session';
  end if;
  select count(*) into v_count from training_sessions where session_date = v_target and start_time = '18:00';
  if v_count <> 1 then raise exception 'TEST6 FAILED: expected exactly 1 session at target slot, found %', v_count; end if;

  raise notice 'TEST6 PASSED: coach-change edit from a legacy (no prior ledger row) session self-protects correctly';
end $$;

-- TEST 7: forward-only self-protection -- time-change edit, same legacy starting condition.
do $$
declare
  v_coach1 uuid; v_manager uuid;
  v_series_a uuid; v_series_b uuid; v_sess_a uuid; v_res json; v_claim_result text; v_count int;
  v_target date := current_date + 805;
begin
  select v into v_coach1 from _test_ids where k='coach';
  select v into v_manager from _test_ids where k='manager';
  perform set_config('app.current_uid', v_manager::text, true);

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target, '18:00', 6, 'ongoing', 'active') returning id into v_series_a;
  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target - 7, '18:00', 6, 'ongoing', 'active') returning id into v_series_b;

  insert into training_sessions (session_date, start_time, coach_id, max_participants, series_id, series_detached)
  values (v_target, '18:00', v_coach1, 6, v_series_a, false) returning id into v_sess_a;

  select staff_update_session_series_scope(v_sess_a, 'this', v_target, '19:00', v_coach1, 6, 60, false, false, false, null) into v_res;
  if not (v_res->>'ok')::boolean then raise exception 'TEST7 FAILED: edit rejected: %', v_res; end if;

  if (select series_occurrence_id from training_sessions where id = v_sess_a) is null then
    raise exception 'TEST7 FAILED: edit did not establish a ledger claim for a previously-unlinked legacy session';
  end if;

  v_claim_result := _generate_series_occurrence_claim(v_series_b, v_target);
  if v_claim_result <> 'series_logical_conflict' then
    raise exception 'TEST7 FAILED: expected series_logical_conflict, got %', v_claim_result;
  end if;

  if exists (select 1 from training_sessions where session_date = v_target and start_time='18:00' and coach_id = v_coach1) then
    raise exception 'TEST7 FAILED: original-time ghost was regenerated for a legacy edited session';
  end if;
  select count(*) into v_count from training_sessions where session_date = v_target and coach_id = v_coach1;
  if v_count <> 1 then raise exception 'TEST7 FAILED: expected exactly 1 session, found %', v_count; end if;

  raise notice 'TEST7 PASSED: time-change edit from a legacy (no prior ledger row) session self-protects correctly';
end $$;

-- TEST 8: forward-only self-protection -- delete, same legacy starting condition. The tombstone
-- must be established atomically by the delete itself, blocking both regeneration by this
-- series and reclaiming by a sibling series.
do $$
declare
  v_coach1 uuid; v_manager uuid;
  v_series_a uuid; v_series_b uuid; v_sess_a uuid; v_res json; v_claim_result text;
  v_target date := current_date + 806;
begin
  select v into v_coach1 from _test_ids where k='coach';
  select v into v_manager from _test_ids where k='manager';
  perform set_config('app.current_uid', v_manager::text, true);

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target, '18:00', 6, 'ongoing', 'active') returning id into v_series_a;
  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target - 7, '18:00', 6, 'ongoing', 'active') returning id into v_series_b;

  insert into training_sessions (session_date, start_time, coach_id, max_participants, series_id, series_detached)
  values (v_target, '18:00', v_coach1, 6, v_series_a, false) returning id into v_sess_a;

  select staff_delete_session_series_scope(v_sess_a, 'this') into v_res;
  if not (v_res->>'ok')::boolean then raise exception 'TEST8 FAILED: delete rejected: %', v_res; end if;

  if exists (select 1 from training_sessions where id = v_sess_a) then
    raise exception 'TEST8 FAILED: session not actually deleted';
  end if;

  if not exists (
    select 1 from session_series_occurrences
    where series_id = v_series_a and template_occurrence_date = v_target and state = 'deleted'
  ) then
    raise exception 'TEST8 FAILED: delete did not establish a tombstone ledger row for a previously-unlinked legacy session';
  end if;

  v_claim_result := _generate_series_occurrence_claim(v_series_a, v_target);
  if v_claim_result <> 'already_handled' then
    raise exception 'TEST8 FAILED: deleted series own re-claim should be already_handled, got %', v_claim_result;
  end if;

  v_claim_result := _generate_series_occurrence_claim(v_series_b, v_target);
  if v_claim_result <> 'series_logical_conflict' then
    raise exception 'TEST8 FAILED: expected sibling series_logical_conflict after delete, got %', v_claim_result;
  end if;

  if exists (select 1 from training_sessions where session_date = v_target and start_time='18:00' and coach_id = v_coach1) then
    raise exception 'TEST8 FAILED: deleted occurrence ghost was regenerated by a sibling series';
  end if;

  raise notice 'TEST8 PASSED: delete from a legacy (no prior ledger row) session self-protects correctly, sibling blocked';
end $$;

-- TEST 9: existing-state-preservation -- this migration must never write to an existing
-- training_sessions row, even the known Shira/Lotem duplicate pair. There is deliberately no
-- backfill; series_occurrence_id stays null on every pre-existing row forever, unless and until
-- a future edit or delete touches that specific row.
do $$
declare
  v_series_x uuid; v_series_y uuid; v_sess_x uuid; v_sess_y uuid;
  v_coach1 uuid; v_target date := current_date + 807;
begin
  select v into v_coach1 from _test_ids where k='coach';

  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target, '20:00', 6, 'ongoing', 'active') returning id into v_series_x;
  insert into session_series (coach_id, anchor_date, start_time, max_participants, repeat_mode, status)
  values (v_coach1, v_target - 7, '20:00', 6, 'ongoing', 'active') returning id into v_series_y;

  -- Two legacy, never-backfilled, colliding rows -- structurally identical to the real
  -- Shira/Lotem duplicate: two physical sessions, two series, same template slot+date, neither
  -- linked to a ledger row.
  insert into training_sessions (session_date, start_time, coach_id, max_participants, series_id, series_detached)
  values (v_target, '20:00', v_coach1, 6, v_series_x, true) returning id into v_sess_x;
  insert into training_sessions (session_date, start_time, coach_id, max_participants, series_id, series_detached)
  values (v_target + 1, '20:00', v_coach1, 6, v_series_y, true) returning id into v_sess_y;

  perform _maintain_session_series_horizon_core();
  perform _maintain_session_series_horizon_core();

  if (select series_occurrence_id from training_sessions where id = v_sess_x) is not null
     or (select series_occurrence_id from training_sessions where id = v_sess_y) is not null then
    raise exception 'TEST9 FAILED: a pre-existing, never-edited legacy row was linked to the ledger';
  end if;
  if not exists (select 1 from training_sessions where id = v_sess_x and session_date = v_target and start_time = '20:00' and coach_id = v_coach1) then
    raise exception 'TEST9 FAILED: pre-existing legacy row x was modified';
  end if;
  if not exists (select 1 from training_sessions where id = v_sess_y and session_date = v_target + 1 and start_time = '20:00' and coach_id = v_coach1) then
    raise exception 'TEST9 FAILED: pre-existing legacy row y was modified';
  end if;

  raise notice 'TEST9 PASSED: pre-existing legacy rows, including a Shira/Lotem-shaped duplicate, are never touched or linked by horizon maintenance';
end $$;

do $$ begin raise notice 'ALL SESSION-SERIES OCCURRENCE-IDENTITY STAGE 1 TESTS PASSED'; end $$;
