
[functions.open-weekly-registrations]
enabled = true
verify_jwt = false
entrypoint = "./functions/open-weekly-registrations/index.ts"

[functions.notify-waitlist]
enabled = true
verify_jwt = false
entrypoint = "./functions/notify-waitlist/index.ts"

[functions.staff-user-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/staff-user-email/index.ts"
