
[functions.open-weekly-registrations]
enabled = true
verify_jwt = false
entrypoint = "./functions/open-weekly-registrations/index.ts"

[functions.notify-waitlist]
enabled = true
verify_jwt = false
entrypoint = "./functions/notify-waitlist/index.ts"

[functions.staff-user-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/staff-user-email/index.ts"

[functions.generate-document-pdf]
enabled = true
verify_jwt = true
entrypoint = "./functions/generate-document-pdf/index.ts"

[functions.send-document-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-document-email/index.ts"

[functions.dispatch-notifications]
enabled = true
verify_jwt = false
entrypoint = "./functions/dispatch-notifications/index.ts"

[functions.staff-confirm-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/staff-confirm-email/index.ts"
