/**
 * Web Push (browser/PWA) sender — VAPID signing (RFC 8292) and message encryption
 * (RFC 8291, aes128gcm) implemented directly against Deno's native WebCrypto API,
 * rather than the `web-push` npm package, to avoid depending on its Node-crypto shim
 * under the Supabase Edge Functions Deno runtime.
 *
 * Requires env vars: VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY (both base64url, as generated by
 * `npx web-push generate-vapid-keys`), VAPID_SUBJECT — a bare mailto: or https: URL (no
 * angle brackets); push services validate this as a URI and reject malformed values with
 * a generic "BadJwtToken" error that has nothing to do with the signature itself.
 */
import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";

function base64UrlToBytes(base64url: string): Uint8Array {
  const padding = "=".repeat((4 - (base64url.length % 4)) % 4);
  const base64 = (base64url + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(base64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  return bytes;
}

function bytesToBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function concatBytes(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, p) => sum + p.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

let vapidKeys: { publicKeyBytes: Uint8Array; privateKey: CryptoKey; subject: string } | null = null;

async function ensureVapidConfigured() {
  if (vapidKeys) return vapidKeys;

  const publicKeyB64 = Deno.env.get("VAPID_PUBLIC_KEY");
  const privateKeyB64 = Deno.env.get("VAPID_PRIVATE_KEY");
  const subject = Deno.env.get("VAPID_SUBJECT") ?? "mailto:support@shirafit.app";
  if (!publicKeyB64 || !privateKeyB64) {
    throw new Error("VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY not configured");
  }

  const publicKeyBytes = base64UrlToBytes(publicKeyB64); // 65-byte uncompressed EC point: 0x04 | x(32) | y(32)
  const x = publicKeyBytes.slice(1, 33);
  const y = publicKeyBytes.slice(33, 65);

  const privateKey = await crypto.subtle.importKey(
    "jwk",
    {
      kty: "EC",
      crv: "P-256",
      d: privateKeyB64,
      x: bytesToBase64Url(x),
      y: bytesToBase64Url(y),
      ext: true,
    },
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"]
  );

  vapidKeys = { publicKeyBytes, privateKey, subject };
  return vapidKeys;
}

async function buildVapidAuthHeader(endpoint: string): Promise<string> {
  const { publicKeyBytes, privateKey, subject } = await ensureVapidConfigured();
  const audience = new URL(endpoint).origin;

  const header = { typ: "JWT", alg: "ES256" };
  const payload = {
    aud: audience,
    exp: Math.floor(Date.now() / 1000) + 12 * 60 * 60,
    sub: subject,
  };

  const encoder = new TextEncoder();
  const headerB64 = bytesToBase64Url(encoder.encode(JSON.stringify(header)));
  const payloadB64 = bytesToBase64Url(encoder.encode(JSON.stringify(payload)));
  const signingInput = `${headerB64}.${payloadB64}`;

  // WebCrypto's ECDSA sign() returns the raw r||s signature (64 bytes for P-256) —
  // exactly what JWS ES256 requires, unlike Node-compat shims that can emit DER.
  const signature = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    privateKey,
    encoder.encode(signingInput)
  );

  const jwt = `${signingInput}.${bytesToBase64Url(new Uint8Array(signature))}`;
  const k = bytesToBase64Url(publicKeyBytes);
  return `vapid t=${jwt}, k=${k}`;
}

/** Encrypts a push payload per RFC 8291 (aes128gcm), returning the request body bytes. */
async function encryptPayload(
  p256dhB64: string,
  authB64: string,
  plaintext: Uint8Array
): Promise<Uint8Array> {
  const uaPublicBytes = base64UrlToBytes(p256dhB64);
  const authSecret = base64UrlToBytes(authB64);

  const uaPublicKey = await crypto.subtle.importKey(
    "raw",
    uaPublicBytes,
    { name: "ECDH", namedCurve: "P-256" },
    false,
    []
  );

  const ephemeral = await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, true, [
    "deriveBits",
  ]);
  const asPublicBytes = new Uint8Array(await crypto.subtle.exportKey("raw", ephemeral.publicKey));

  const sharedSecretBits = await crypto.subtle.deriveBits(
    { name: "ECDH", public: uaPublicKey },
    ephemeral.privateKey,
    256
  );

  const encoder = new TextEncoder();
  const ecdhSecretKey = await crypto.subtle.importKey("raw", sharedSecretBits, "HKDF", false, [
    "deriveBits",
  ]);

  // Step 1: derive the 32-byte "ikm" — HKDF over the ECDH secret, salted with the
  // subscriber's auth secret, keyed by both public points per RFC 8291 §3.4.
  const infoIkm = concatBytes(
    encoder.encode("WebPush: info\0"),
    uaPublicBytes,
    asPublicBytes
  );
  const ikmBits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt: authSecret, info: infoIkm },
    ecdhSecretKey,
    256
  );
  const ikmKey = await crypto.subtle.importKey("raw", ikmBits, "HKDF", false, ["deriveBits"]);

  const salt = crypto.getRandomValues(new Uint8Array(16));

  const cekBits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt, info: encoder.encode("Content-Encoding: aes128gcm\0") },
    ikmKey,
    128
  );
  const nonceBits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt, info: encoder.encode("Content-Encoding: nonce\0") },
    ikmKey,
    96
  );

  const cek = await crypto.subtle.importKey("raw", cekBits, { name: "AES-GCM" }, false, [
    "encrypt",
  ]);

  // Single-record aes128gcm body: plaintext + a 0x02 delimiter (no extra padding needed).
  const padded = concatBytes(plaintext, new Uint8Array([0x02]));
  const ciphertext = new Uint8Array(
    await crypto.subtle.encrypt({ name: "AES-GCM", iv: new Uint8Array(nonceBits) }, cek, padded)
  );

  const recordSize = new Uint8Array(4);
  new DataView(recordSize.buffer).setUint32(0, 4096);
  const keyIdLen = new Uint8Array([asPublicBytes.length]);

  return concatBytes(salt, recordSize, keyIdLen, asPublicBytes, ciphertext);
}

type WebPushSubscriptionRow = {
  id: string;
  endpoint: string;
  p256dh: string;
  auth: string;
};

/**
 * Sends a push to every subscription on file for a user. Best-effort per-subscription:
 * a single failed/expired endpoint doesn't stop delivery to the user's other devices.
 * Expired subscriptions (410 Gone / 404) are pruned automatically.
 */
export async function sendWebPushToUser(
  adminClient: SupabaseClient,
  userId: string,
  payload: { title: string; body: string; data?: Record<string, unknown> }
): Promise<{ sent: number; pruned: number }> {
  const { data: subs } = await adminClient
    .from("web_push_subscriptions")
    .select("id, endpoint, p256dh, auth")
    .eq("user_id", userId);

  const rows = (subs as WebPushSubscriptionRow[] | null) ?? [];
  if (rows.length === 0) return { sent: 0, pruned: 0 };

  const plaintext = new TextEncoder().encode(JSON.stringify(payload));
  let sent = 0;
  let pruned = 0;

  await Promise.all(
    rows.map(async (row) => {
      try {
        const body = await encryptPayload(row.p256dh, row.auth, plaintext);
        const authHeader = await buildVapidAuthHeader(row.endpoint);

        const res = await fetch(row.endpoint, {
          method: "POST",
          headers: {
            "Content-Type": "application/octet-stream",
            "Content-Encoding": "aes128gcm",
            TTL: "86400",
            Authorization: authHeader,
          },
          body,
        });

        if (res.status === 404 || res.status === 410) {
          await adminClient.from("web_push_subscriptions").delete().eq("id", row.id);
          pruned += 1;
          return;
        }
        if (!res.ok) {
          console.error(`push send failed for ${row.id}: ${res.status} ${await res.text()}`);
          return;
        }
        sent += 1;
      } catch (err) {
        console.error(`push send threw for ${row.id}: ${err instanceof Error ? err.message : String(err)}`);
      }
    })
  );

  return { sent, pruned };
}
