import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { theme } from "../theme";
import { AppModal } from "./AppModal";
import { AppSearchField } from "./AppSearchField";
import { DatePickerField } from "./DatePickerField";
import { PrimaryButton } from "./PrimaryButton";
import { ServiceTypePickerField } from "./ServiceTypePickerField";
import { useI18n } from "../context/I18nContext";
import { supabase } from "../lib/supabase";
import { toISODateLocal } from "../lib/isoDate";
import {
  SESSION_PAYMENT_METHOD_KEYS,
  paymentMethodHistoryLabel,
  type SessionPaymentMethodKey,
} from "../lib/paymentMethod";
import type { DocumentPaymentMethodKey } from "../lib/documentPaymentMethod";
import {
  type DocumentServiceTypeKey,
  defaultTrainingsServiceDescription,
} from "../lib/documentServiceTypes";
import { createDocumentWithPayment, autoGenerateDocumentPdfIfReady } from "../lib/documents";

type PayeeRow = {
  kind: "app" | "manual";
  id: string;
  full_name: string;
  phone: string | null;
};

type Props = {
  visible: boolean;
  onClose: () => void;
  onCreated: () => void | Promise<void>;
};

function sessionToDocumentMethod(method: SessionPaymentMethodKey): DocumentPaymentMethodKey {
  if (method === "cash" || method === "paybox" || method === "mom" || method === "other") return method;
  return "other";
}

export function CreateReceiptWithPaymentModal({ visible, onClose, onCreated }: Props) {
  const { language, t, isRTL } = useI18n();
  const [step, setStep] = useState<"payee" | "form">("payee");
  const [payeeQ, setPayeeQ] = useState("");
  const [payeeRows, setPayeeRows] = useState<PayeeRow[]>([]);
  const [payeeLoading, setPayeeLoading] = useState(false);
  const [selectedPayee, setSelectedPayee] = useState<PayeeRow | null>(null);
  const [amount, setAmount] = useState("");
  const [serviceType, setServiceType] = useState<DocumentServiceTypeKey>("other");
  const [serviceDescription, setServiceDescription] = useState(() => defaultTrainingsServiceDescription());
  const [serviceDescriptionTouched, setServiceDescriptionTouched] = useState(false);
  const [method, setMethod] = useState<SessionPaymentMethodKey>("cash");
  const [note, setNote] = useState("");
  const [paidAt, setPaidAt] = useState(() => toISODateLocal(new Date()));
  const [busy, setBusy] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState("");
  const scrollRef = useRef<ScrollView>(null);

  const loadPayees = useCallback(async (termRaw: string) => {
    const q = termRaw.trim();
    setPayeeLoading(true);
    try {
      let profileQuery = supabase
        .from("profiles")
        .select("user_id, full_name, phone")
        .eq("role", "athlete")
        .order("full_name", { ascending: true })
        .limit(60);
      if (q) profileQuery = profileQuery.or(`full_name.ilike.%${q}%,phone.ilike.%${q}%`);

      let manualQuery = supabase
        .from("manual_participants")
        .select("id, full_name, phone, linked_user_id")
        .is("disabled_at", null)
        .order("full_name", { ascending: true })
        .limit(60);
      if (q) manualQuery = manualQuery.or(`full_name.ilike.%${q}%,phone.ilike.%${q}%`);

      const [profilesRes, manualRes] = await Promise.all([profileQuery, manualQuery]);
      const athletes: PayeeRow[] = (profilesRes.data ?? []).map((p) => ({
        kind: "app",
        id: p.user_id,
        full_name: p.full_name,
        phone: p.phone,
      }));
      const manuals: PayeeRow[] = (manualRes.data ?? [])
        .filter((m) => !m.linked_user_id)
        .map((m) => ({
          kind: "manual",
          id: m.id,
          full_name: m.full_name,
          phone: m.phone,
        }));
      setPayeeRows([...manuals, ...athletes]);
    } finally {
      setPayeeLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!visible) return;
    setStep("payee");
    setPayeeQ("");
    setSelectedPayee(null);
    setAmount("");
    setServiceType("other");
    const today = toISODateLocal(new Date());
    setPaidAt(today);
    setServiceDescription(defaultTrainingsServiceDescription(today));
    setServiceDescriptionTouched(false);
    setMethod("cash");
    setNote("");
    setError("");
    setBusy(false);
    void loadPayees("");
    requestAnimationFrame(() => {
      scrollRef.current?.scrollTo({ y: 0, animated: false });
    });
  }, [visible, loadPayees]);

  useEffect(() => {
    requestAnimationFrame(() => {
      scrollRef.current?.scrollTo({ y: 0, animated: false });
    });
  }, [step]);

  useEffect(() => {
    if (!visible || step !== "payee") return;
    void loadPayees(payeeQ);
  }, [visible, step, payeeQ, loadPayees]);

  useEffect(() => {
    if (serviceType !== "other" || serviceDescriptionTouched) return;
    setServiceDescription(defaultTrainingsServiceDescription(paidAt));
  }, [paidAt, serviceType, serviceDescriptionTouched]);

  function pickPayee(row: PayeeRow) {
    setSelectedPayee(row);
    setStep("form");
    setError("");
  }

  function handleServiceTypeChange(next: DocumentServiceTypeKey) {
    setServiceType(next);
    if (next === "other") {
      if (!serviceDescriptionTouched) {
        setServiceDescription(defaultTrainingsServiceDescription(paidAt));
      }
    } else {
      setServiceDescription("");
      setServiceDescriptionTouched(false);
    }
  }

  async function submit() {
    if (!selectedPayee) return;
    setError("");
    const amt = Number.parseFloat(amount.replace(",", ".").trim());
    if (!Number.isFinite(amt) || amt <= 0) {
      setError(language === "he" ? "הזינו סכום תקין." : "Enter a valid amount.");
      return;
    }
    if (serviceType === "other" && !serviceDescription.trim()) {
      setError(language === "he" ? "תיאור שירות חובה כשבוחרים 'אימונים'." : "Description required for Trainings.");
      return;
    }
    setBusy(true);
    try {
      const result = await createDocumentWithPayment({
        mode: "account",
        gross_amount: amt,
        service_type: serviceType,
        payment_method: sessionToDocumentMethod(method),
        customer_name: selectedPayee.full_name,
        customer_phone: selectedPayee.phone,
        service_description: serviceType === "other" ? serviceDescription.trim() : null,
        notes: note.trim() || null,
        profile_user_id: selectedPayee.kind === "app" ? selectedPayee.id : null,
        manual_participant_id: selectedPayee.kind === "manual" ? selectedPayee.id : null,
        paid_at: paidAt.trim() || null,
      });
      await autoGenerateDocumentPdfIfReady(result.document_id, result.status, {
        needsPdf: result.needs_pdf,
      });
      await onCreated();
      setSuccess(true);
      await new Promise((resolve) => setTimeout(resolve, theme.motion.normal));
      setSuccess(false);
      onClose();
    } catch (e) {
      setError(e instanceof Error ? e.message : t("common.error"));
    } finally {
      setBusy(false);
    }
  }

  return (
    <AppModal visible={visible} onClose={onClose} variant="sheet" backdropAccessibilityLabel={t("common.close")}>
      <ScrollView ref={scrollRef} contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">
        <Text style={[styles.title, isRTL && styles.rtl]}>
          {language === "he" ? "קבלה + תשלום חדש" : "New receipt & payment"}
        </Text>
        <Text style={[styles.subtitle, isRTL && styles.rtl]}>
          {language === "he"
            ? "ירשם תשלום בחשבון המתאמן/ת ותופק קבלה."
            : "Records an account payment and issues a receipt."}
        </Text>

        {step === "payee" ? (
          <>
            <AppSearchField
              value={payeeQ}
              onChangeText={setPayeeQ}
              // loadPayees already re-runs via the effect watching payeeQ above.
              onSearch={() => {}}
              placeholder={language === "he" ? "חיפוש מתאמן/ת או quick-add…" : "Search athlete or quick-add…"}
            />
            {payeeLoading ? (
              <ActivityIndicator color={theme.colors.cta} style={{ marginVertical: 16 }} />
            ) : (
              payeeRows.map((row) => (
                <Pressable
                  key={`${row.kind}-${row.id}`}
                  onPress={() => pickPayee(row)}
                  style={({ pressed }) => [styles.listRow, pressed && { opacity: 0.85 }]}
                >
                  <Text style={[styles.listRowTitle, isRTL && styles.rtl]}>{row.full_name}</Text>
                  <Text style={[styles.listRowSub, isRTL && styles.rtl]}>
                    {row.kind === "manual"
                      ? "Quick-add"
                      : language === "he"
                        ? "מתאמן/ת"
                        : "Athlete"}
                    {row.phone ? ` · ${row.phone}` : ""}
                  </Text>
                </Pressable>
              ))
            )}
          </>
        ) : selectedPayee ? (
          <>
            <Pressable onPress={() => setStep("payee")} style={styles.backLink}>
              <Text style={styles.backLinkText}>
                {language === "he" ? "← שינוי משלם" : "← Change payee"}
              </Text>
            </Pressable>
            <View style={styles.payeeBanner}>
              <Text style={[styles.payeeBannerTitle, isRTL && styles.rtl]}>{selectedPayee.full_name}</Text>
              {selectedPayee.phone ? (
                <Text style={[styles.payeeBannerSub, isRTL && styles.rtl]}>{selectedPayee.phone}</Text>
              ) : null}
            </View>

            <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>
              {language === "he" ? "סכום (₪)" : "Amount (₪)"}
            </Text>
            <TextInput
              value={amount}
              onChangeText={setAmount}
              keyboardType="decimal-pad"
              style={[styles.input, styles.amountInput, isRTL && styles.rtlInput]}
            />

            <ServiceTypePickerField
              label={language === "he" ? "סוג שירות" : "Service type"}
              value={serviceType}
              onChange={handleServiceTypeChange}
              language={language === "he" ? "he" : "en"}
              isRTL={isRTL}
            />
            {serviceType === "other" ? (
              <>
                <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>
                  {language === "he" ? "תיאור שירות" : "Service description"}
                </Text>
                <TextInput
                  value={serviceDescription}
                  onChangeText={(v) => {
                    setServiceDescription(v);
                    setServiceDescriptionTouched(true);
                  }}
                  style={[styles.input, isRTL && styles.rtlInput]}
                />
              </>
            ) : null}

            <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>
              {language === "he" ? "אמצעי תשלום" : "Payment method"}
            </Text>
            <View style={[styles.chipRow, isRTL && styles.chipRowRtl]}>
              {SESSION_PAYMENT_METHOD_KEYS.map((k) => (
                <Pressable
                  key={k}
                  onPress={() => setMethod(k)}
                  style={[styles.chip, method === k && styles.chipOn]}
                >
                  <Text style={[styles.chipText, method === k && styles.chipTextOn]}>
                    {paymentMethodHistoryLabel(k, language)}
                  </Text>
                </Pressable>
              ))}
            </View>

            <DatePickerField
              label={language === "he" ? "תאריך תשלום" : "Payment date"}
              value={paidAt}
              onChange={setPaidAt}
            />

            <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>
              {language === "he" ? "הערה" : "Note"}
            </Text>
            <TextInput
              value={note}
              onChangeText={setNote}
              placeholder={language === "he" ? "אופציונלי" : "Optional"}
              placeholderTextColor={theme.colors.textSoft}
              style={[styles.input, isRTL && styles.rtlInput]}
            />

            {error ? <Text style={[styles.error, isRTL && styles.rtl]}>{error}</Text> : null}
            <PrimaryButton
              label={language === "he" ? "הפק קבלה ורשום תשלום" : "Create receipt & payment"}
              onPress={() => void submit()}
              disabled={busy}
              loading={busy && !success}
              success={success}
              loadingLabel={t("common.loading")}
            />
          </>
        ) : null}
      </ScrollView>
    </AppModal>
  );
}

const styles = StyleSheet.create({
  scroll: { padding: theme.spacing.lg, paddingBottom: theme.spacing.xl + theme.spacing.md, gap: theme.spacing.md },
  title: { fontSize: 20, fontWeight: "800", color: theme.colors.text },
  subtitle: { fontSize: 14, fontWeight: "500", color: theme.colors.textMuted, lineHeight: 20 },
  listRow: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: 4,
  },
  listRowTitle: { fontSize: 15, fontWeight: "800", color: theme.colors.text },
  listRowSub: { fontSize: 13, fontWeight: "500", color: theme.colors.textMuted },
  backLink: { alignSelf: "flex-start" },
  backLinkText: { fontSize: 13, fontWeight: "700", color: theme.colors.cta },
  payeeBanner: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: 4,
  },
  payeeBannerTitle: { fontSize: 16, fontWeight: "800", color: theme.colors.text },
  payeeBannerSub: { fontSize: 13, fontWeight: "600", color: theme.colors.textMuted },
  fieldLabel: { fontSize: 13, fontWeight: "700", color: theme.colors.textMuted },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.radius.md,
    paddingVertical: 12,
    paddingHorizontal: theme.spacing.md,
    color: theme.colors.text,
    backgroundColor: theme.colors.surfaceElevated,
    fontSize: 15,
    fontWeight: "600",
  },
  amountInput: { fontSize: 18, fontWeight: "800" },
  rtlInput: { textAlign: "right", writingDirection: "rtl" },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.sm },
  chipRowRtl: { flexDirection: "row-reverse" },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
  },
  chipOn: { backgroundColor: theme.colors.cta, borderColor: theme.colors.cta },
  chipText: { fontSize: 12, fontWeight: "800", color: theme.colors.textMuted },
  chipTextOn: { color: theme.colors.ctaText },
  error: { color: theme.colors.error, fontWeight: "700", fontSize: 14 },
  rtl: { textAlign: "right", writingDirection: "rtl" },
});
