import { useEffect, useState, type ReactNode } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { theme } from "../theme";
import { AppModal } from "./AppModal";
import { PrimaryButton } from "./PrimaryButton";
import { useI18n } from "../context/I18nContext";
import {
  DOCUMENT_PAYMENT_METHOD_KEYS,
  type DocumentPaymentMethodKey,
  documentPaymentMethodLabel,
  mapRecordedPaymentToDocumentMethod,
} from "../lib/documentPaymentMethod";
import {
  DOCUMENT_SERVICE_TYPE_KEYS,
  type DocumentServiceTypeKey,
  documentServiceTypeLabel,
} from "../lib/documentServiceTypes";
import { createDocument, autoGenerateDocumentPdfIfReady } from "../lib/documents";
import type { DocumentSourceType } from "../lib/documents";

export type CreateDocumentPrefill = {
  gross_amount: number;
  customer_name: string;
  customer_email?: string | null;
  customer_phone?: string | null;
  profile_user_id?: string | null;
  manual_participant_id?: string | null;
  source_type?: DocumentSourceType;
  source_id?: string | null;
  source_payment_method?: string | null;
};

type Props = {
  visible: boolean;
  onClose: () => void;
  prefill?: CreateDocumentPrefill | null;
  onCreated: () => void | Promise<void>;
};

function SectionCard({ title, children }: { title: string; children: ReactNode }) {
  return (
    <View style={modalStyles.card}>
      <Text style={modalStyles.sectionLabel}>{title}</Text>
      {children}
    </View>
  );
}

function FieldLabel({ children, isRTL }: { children: string; isRTL: boolean }) {
  return <Text style={[modalStyles.fieldLabel, isRTL && modalStyles.rtl]}>{children}</Text>;
}

export function CreateDocumentModal({ visible, onClose, prefill, onCreated }: Props) {
  const { language, t, isRTL } = useI18n();
  const [gross, setGross] = useState("");
  const [customerName, setCustomerName] = useState("");
  const [customerEmail, setCustomerEmail] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const [paymentMethod, setPaymentMethod] = useState<DocumentPaymentMethodKey | "">("");
  const [serviceType, setServiceType] = useState<DocumentServiceTypeKey>("kickboxing");
  const [serviceDescription, setServiceDescription] = useState("");
  const [notes, setNotes] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!visible) return;
    setGross(prefill?.gross_amount != null ? String(prefill.gross_amount) : "");
    setCustomerName(prefill?.customer_name ?? "");
    setCustomerEmail(prefill?.customer_email ?? "");
    setCustomerPhone(prefill?.customer_phone ?? "");
    setPaymentMethod(mapRecordedPaymentToDocumentMethod(prefill?.source_payment_method) ?? "");
    setServiceType("kickboxing");
    setServiceDescription("");
    setNotes("");
    setError("");
    setBusy(false);
  }, [visible, prefill]);

  async function submit() {
    setError("");
    const amt = Number.parseFloat(gross.replace(",", ".").trim());
    if (!Number.isFinite(amt) || amt <= 0) {
      setError(language === "he" ? "הזינו סכום תקין." : "Enter a valid amount.");
      return;
    }
    if (!customerName.trim()) {
      setError(language === "he" ? "שם לקוח חובה." : "Customer name is required.");
      return;
    }
    if (serviceType === "other" && !serviceDescription.trim()) {
      setError(language === "he" ? "תיאור שירות חובה כשבוחרים 'אימונים'." : "Description required for Trainings.");
      return;
    }
    setBusy(true);
    try {
      const result = await createDocument({
        gross_amount: amt,
        service_type: serviceType,
        customer_name: customerName.trim(),
        customer_email: customerEmail.trim() || null,
        customer_phone: customerPhone.trim() || null,
        payment_method: paymentMethod || null,
        service_description: serviceDescription.trim() || null,
        notes: notes.trim() || null,
        profile_user_id: prefill?.profile_user_id ?? null,
        manual_participant_id: prefill?.manual_participant_id ?? null,
        source_type: prefill?.source_type ?? "manual",
        source_id: prefill?.source_id ?? null,
        source_payment_method: prefill?.source_payment_method ?? null,
      });
      await autoGenerateDocumentPdfIfReady(result.document_id, result.status, { needsPdf: result.needs_pdf });
      await onCreated();
      onClose();
    } catch (e) {
      setError(e instanceof Error ? e.message : t("common.error"));
    } finally {
      setBusy(false);
    }
  }

  return (
    <AppModal visible={visible} onClose={onClose} variant="sheet" backdropAccessibilityLabel={t("common.close")}>
      <ScrollView contentContainerStyle={modalStyles.scroll} keyboardShouldPersistTaps="handled">
        <Text style={[modalStyles.title, isRTL && modalStyles.rtl]}>
          {language === "he" ? "הפקת קבלה לתשלום" : "Issue receipt for payment"}
        </Text>
        <Text style={[modalStyles.subtitle, isRTL && modalStyles.rtl]}>
          {language === "he"
            ? "מקושר לתשלום קיים — לא יירשם תשלום נוסף."
            : "Linked to an existing payment — no new payment will be recorded."}
        </Text>

        <SectionCard title={language === "he" ? "לקוח ותשלום" : "Customer & payment"}>
          <FieldLabel isRTL={isRTL}>{language === "he" ? "שם לקוח" : "Customer name"}</FieldLabel>
          <TextInput value={customerName} onChangeText={setCustomerName} style={[modalStyles.input, isRTL && modalStyles.rtlInput]} />
          <FieldLabel isRTL={isRTL}>{language === "he" ? "אימייל לקוח" : "Customer email"}</FieldLabel>
          <TextInput
            value={customerEmail}
            onChangeText={setCustomerEmail}
            keyboardType="email-address"
            autoCapitalize="none"
            placeholder={language === "he" ? "אופציונלי — יילקח מהחשבון אם ריק" : "Optional — filled from account if empty"}
            placeholderTextColor={theme.colors.textSoft}
            style={[modalStyles.input, isRTL && modalStyles.rtlInput]}
          />
          <FieldLabel isRTL={isRTL}>{language === "he" ? "טלפון לקוח" : "Customer phone"}</FieldLabel>
          <TextInput
            value={customerPhone}
            onChangeText={setCustomerPhone}
            keyboardType="phone-pad"
            placeholder={language === "he" ? "אופציונלי" : "Optional"}
            placeholderTextColor={theme.colors.textSoft}
            style={[modalStyles.input, isRTL && modalStyles.rtlInput]}
          />
          <FieldLabel isRTL={isRTL}>{language === "he" ? "סכום כולל (₪)" : "Gross amount (₪)"}</FieldLabel>
          <TextInput
            value={gross}
            onChangeText={setGross}
            keyboardType="decimal-pad"
            style={[modalStyles.input, modalStyles.amountInput, isRTL && modalStyles.rtlInput]}
          />
          <View style={[modalStyles.chipRow, isRTL && modalStyles.chipRowRtl]}>
            {DOCUMENT_PAYMENT_METHOD_KEYS.map((k) => (
              <Pressable
                key={k}
                onPress={() => setPaymentMethod(k)}
                style={({ pressed }) => [
                  modalStyles.chip,
                  paymentMethod === k && modalStyles.chipOn,
                  pressed && paymentMethod !== k && { opacity: 0.85 },
                ]}
              >
                <Text style={[modalStyles.chipText, paymentMethod === k && modalStyles.chipTextOn]}>
                  {documentPaymentMethodLabel(k, language === "he" ? "he" : "en")}
                </Text>
              </Pressable>
            ))}
          </View>
        </SectionCard>

        <SectionCard title={language === "he" ? "סוג שירות" : "Service type"}>
          <View style={[modalStyles.chipRow, isRTL && modalStyles.chipRowRtl]}>
            {DOCUMENT_SERVICE_TYPE_KEYS.map((k) => (
              <Pressable
                key={k}
                onPress={() => setServiceType(k)}
                style={({ pressed }) => [
                  modalStyles.chip,
                  serviceType === k && modalStyles.chipOn,
                  pressed && serviceType !== k && { opacity: 0.85 },
                ]}
              >
                <Text style={[modalStyles.chipText, serviceType === k && modalStyles.chipTextOn]}>
                  {documentServiceTypeLabel(k, language === "he" ? "he" : "en")}
                </Text>
              </Pressable>
            ))}
          </View>
          {serviceType === "other" ? (
            <>
              <FieldLabel isRTL={isRTL}>{language === "he" ? "תיאור שירות" : "Service description"}</FieldLabel>
              <TextInput
                value={serviceDescription}
                onChangeText={setServiceDescription}
                style={[modalStyles.input, isRTL && modalStyles.rtlInput]}
              />
            </>
          ) : null}
        </SectionCard>

        <SectionCard title={language === "he" ? "הערות" : "Notes"}>
          <TextInput
            value={notes}
            onChangeText={setNotes}
            multiline
            placeholder={language === "he" ? "אופציונלי" : "Optional"}
            placeholderTextColor={theme.colors.textSoft}
            style={[modalStyles.input, modalStyles.textArea, isRTL && modalStyles.rtlInput]}
          />
        </SectionCard>

        {error ? <Text style={[modalStyles.error, isRTL && modalStyles.rtl]}>{error}</Text> : null}
        <PrimaryButton
          label={language === "he" ? "הפק קבלה" : "Issue receipt"}
          onPress={() => void submit()}
          disabled={busy}
          loading={busy}
          loadingLabel={t("common.loading")}
        />
      </ScrollView>
    </AppModal>
  );
}

const modalStyles = StyleSheet.create({
  scroll: { padding: theme.spacing.lg, paddingBottom: theme.spacing.xl + theme.spacing.md, gap: theme.spacing.md },
  title: { fontSize: 20, fontWeight: "800", color: theme.colors.text, letterSpacing: 0.2 },
  subtitle: { fontSize: 14, fontWeight: "500", color: theme.colors.textMuted, lineHeight: 20, marginTop: 4 },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.35,
    marginBottom: 2,
  },
  fieldLabel: { fontSize: 13, fontWeight: "700", color: theme.colors.textMuted, marginTop: 2 },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.radius.md,
    paddingVertical: 12,
    paddingHorizontal: theme.spacing.md,
    color: theme.colors.text,
    backgroundColor: theme.colors.surfaceElevated,
    fontSize: 15,
    fontWeight: "600",
  },
  amountInput: { fontSize: 18, fontWeight: "800" },
  textArea: { minHeight: 88, textAlignVertical: "top" },
  rtlInput: { textAlign: "right", writingDirection: "rtl" },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.sm },
  chipRowRtl: { flexDirection: "row-reverse" },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
  },
  chipOn: { backgroundColor: theme.colors.cta, borderColor: theme.colors.cta },
  chipText: { fontSize: 12, fontWeight: "800", color: theme.colors.textMuted },
  chipTextOn: { color: theme.colors.ctaText },
  error: { color: theme.colors.error, fontWeight: "700", fontSize: 14 },
  rtl: { textAlign: "right", writingDirection: "rtl" },
});
