import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import {
  ActivityIndicator,
  FlatList,
  Pressable,
  RefreshControl,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { theme } from "../theme";
import { useI18n } from "../context/I18nContext";
import { useToast } from "../context/ToastContext";
import { CreateReceiptWithPaymentModal } from "./CreateReceiptWithPaymentModal";
import { AppSwitch } from "./AppSwitch";
import { CollapsibleDateRangeCard } from "./CollapsibleDateRangeCard";
import { SortToggleButton } from "./SortToggleButton";
import { PrimaryButton } from "./PrimaryButton";
import { formatISODateLong } from "../lib/dateFormat";
import { formatSessionStartTime } from "../lib/sessionTime";
import { formatIls, autoGenerateDocumentPdfIfReady, invokeSendDocumentsEmail } from "../lib/documents";
import { paymentMethodHistoryLabel } from "../lib/paymentMethod";
import { documentServiceTypeLabel } from "../lib/documentServiceTypes";
import {
  createDocumentsFromPayments,
  listPaymentsWithoutReceipt,
  type PendingReceiptPayment,
} from "../lib/pendingReceipts";
import { lastNDaysRangeISO } from "../lib/isoDate";

type Props = {
  enabled: boolean;
  header: ReactNode;
  onCreated: () => void | Promise<void>;
  testingMode?: boolean;
};

function slotKindLabel(kind: string | null, language: "he" | "en"): string | null {
  if (kind === "arrival") return language === "he" ? "הגעה" : "Arrival";
  if (kind === "no_show") return language === "he" ? "אי הגעה" : "No-show";
  if (kind === "cancellation") return language === "he" ? "ביטול מאוחר" : "Late cancel";
  return null;
}

export function PendingReceiptsPanel({ enabled, header, onCreated, testingMode = false }: Props) {
  const { language, t, isRTL } = useI18n();
  const { showToast } = useToast();
  const lang = language === "he" ? "he" : "en";
  const defaultRange = useMemo(() => lastNDaysRangeISO(90), []);

  const [dateStart, setDateStart] = useState(defaultRange.start);
  const [dateEnd, setDateEnd] = useState(defaultRange.end);
  const [rows, setRows] = useState<PendingReceiptPayment[]>([]);
  const [totalCount, setTotalCount] = useState(0);
  const [totalAmount, setTotalAmount] = useState(0);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [creating, setCreating] = useState(false);
  const [createPaymentOpen, setCreatePaymentOpen] = useState(false);
  const [generatePdfs, setGeneratePdfs] = useState(true);
  const [emailCustomers, setEmailCustomers] = useState(false);
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc");

  const load = useCallback(async () => {
    try {
      const result = await listPaymentsWithoutReceipt({
        date_start: dateStart,
        date_end: dateEnd,
      });
      setRows(result.payments);
      setTotalCount(result.total_count);
      setTotalAmount(result.total_amount);
      setSelected((prev) => {
        const valid = new Set(result.payments.map((p) => p.row_id));
        return new Set([...prev].filter((id) => valid.has(id)));
      });
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      showToast({
        message: language === "he" ? "שגיאה בטעינת תשלומים" : "Failed to load payments",
        detail,
        variant: "error",
      });
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [dateStart, dateEnd, language, showToast]);

  useEffect(() => {
    if (!enabled) {
      setLoading(false);
      return;
    }
    setLoading(true);
    void load();
  }, [enabled, load]);

  const sortedRows = useMemo(() => {
    return [...rows].sort((a, b) => {
      const aTime = new Date(a.paid_at).getTime();
      const bTime = new Date(b.paid_at).getTime();
      return sortOrder === "asc" ? aTime - bTime : bTime - aTime;
    });
  }, [rows, sortOrder]);

  const selectableRows = useMemo(() => rows.filter((r) => !r.needs_payment_method), [rows]);
  const allSelected = selectableRows.length > 0 && selectableRows.every((r) => selected.has(r.row_id));
  const selectedCount = selected.size;
  const selectedTotal = useMemo(
    () => rows.filter((r) => selected.has(r.row_id)).reduce((s, r) => s + r.amount_ils, 0),
    [rows, selected]
  );

  function toggleRow(rowId: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(rowId)) next.delete(rowId);
      else next.add(rowId);
      return next;
    });
  }

  function toggleSelectAll() {
    if (allSelected) {
      setSelected(new Set());
    } else {
      setSelected(new Set(selectableRows.map((r) => r.row_id)));
    }
  }

  async function createSelected() {
    if (selectedCount === 0) return;
    setCreating(true);
    try {
      const result = await createDocumentsFromPayments([...selected]);
      let pdfCount = 0;
      let emailCount = 0;
      const createdDocIds: string[] = [];
      for (const doc of result.created) {
        if (generatePdfs) {
          await autoGenerateDocumentPdfIfReady(doc.document_id, doc.status, {
            needsPdf: doc.needs_pdf,
            allowOverwrite: testingMode,
          });
          if (doc.status !== "NEEDS_PAYMENT_METHOD") pdfCount += 1;
        }
        if (doc.status !== "NEEDS_PAYMENT_METHOD") {
          createdDocIds.push(doc.document_id);
        }
      }
      if (emailCustomers && createdDocIds.length > 0) {
        try {
          const emailResult = await invokeSendDocumentsEmail({
            documentIds: createdDocIds,
            mode: "customers",
          });
          emailCount = emailResult.emails_sent;
        } catch {
          /* emails can be sent later from Documents */
        }
      }
      await onCreated();
      setSelected(new Set());
      await load();
      const msg =
        language === "he"
          ? `נוצרו ${result.created_count} קבלות${result.failed_count ? ` · ${result.failed_count} נכשלו` : ""}${generatePdfs && pdfCount ? ` · ${pdfCount} PDF` : ""}${emailCustomers && emailCount ? ` · ${emailCount} אימיילים ללקוחות` : ""}`
          : `${result.created_count} receipt(s) created${result.failed_count ? ` · ${result.failed_count} failed` : ""}${generatePdfs && pdfCount ? ` · ${pdfCount} PDF` : ""}${emailCustomers && emailCount ? ` · ${emailCount} customer email(s)` : ""}`;
      showToast({ message: msg, variant: result.failed_count ? "info" : "success" });
    } catch (e) {
      showToast({
        message: t("common.error"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setCreating(false);
    }
  }

  function renderRow({ item }: { item: PendingReceiptPayment }) {
    const isSelected = selected.has(item.row_id);
    const slotLabel = slotKindLabel(item.session_slot_kind, lang);
    const disabled = item.needs_payment_method;

    return (
      <Pressable
        disabled={disabled}
        onPress={() => toggleRow(item.row_id)}
        style={({ pressed }) => [
          styles.row,
          isSelected && styles.rowSelected,
          disabled && styles.rowDisabled,
          pressed && !disabled && { opacity: 0.9 },
        ]}
      >
        <View style={[styles.rowTop, isRTL && styles.rowTopRtl]}>
          <View style={[styles.check, isSelected && styles.checkOn, disabled && styles.checkDisabled]}>
            {isSelected ? <Text style={styles.checkMark}>✓</Text> : null}
          </View>
          <View style={styles.rowMain}>
            <Text style={[styles.payeeName, isRTL && styles.rtl]} numberOfLines={1}>
              {item.payee_name}
            </Text>
            <Text style={[styles.rowMeta, isRTL && styles.rtl]} numberOfLines={2}>
              {item.source === "account"
                ? language === "he"
                  ? "תשלום בחשבון"
                  : "Account payment"
                : [
                    item.session_date ? formatISODateLong(item.session_date, language) : null,
                    item.session_start_time ? formatSessionStartTime(item.session_start_time) : null,
                    item.coach_name,
                    slotLabel,
                  ]
                    .filter(Boolean)
                    .join(" · ")}
            </Text>
            <Text style={[styles.rowSub, isRTL && styles.rtl]}>
              {documentServiceTypeLabel(item.service_type, lang)}
              {item.payment_method ? ` · ${paymentMethodHistoryLabel(item.payment_method, lang)}` : ""}
            </Text>
          </View>
          <Text style={styles.amount}>{formatIls(item.amount_ils)}</Text>
        </View>
        {disabled ? (
          <Text style={[styles.warn, isRTL && styles.rtl]}>
            {language === "he"
              ? "אמצעי תשלום לא נתמך — עדכנו את התשלום לפני הפקת קבלה"
              : "Unsupported payment method — update payment before issuing receipt"}
          </Text>
        ) : null}
      </Pressable>
    );
  }

  const listHeader = (
    <>
      {header}
      <CollapsibleDateRangeCard
        start={dateStart}
        end={dateEnd}
        onChange={({ start, end }) => {
          setDateStart(start);
          setDateEnd(end);
        }}
        label={language === "he" ? "טווח תאריכים" : "Date range"}
      />
      <PrimaryButton
        label={language === "he" ? "קבלה + תשלום חדש" : "New receipt & payment"}
        onPress={() => setCreatePaymentOpen(true)}
      />
      {selectableRows.length > 0 ? (
        <View style={styles.bulkOpts}>
          <View style={[styles.toggleRow, isRTL && styles.toggleRowRtl]}>
            <Text style={[styles.toggleLabel, isRTL && styles.rtl]}>
              {language === "he" ? "צור PDF לכל הנוצרים" : "Generate PDF for all created"}
            </Text>
            <AppSwitch
              value={generatePdfs}
              onValueChange={setGeneratePdfs}
              onColor={theme.colors.success}
              accessibilityLabel={language === "he" ? "צור PDF לכל הנוצרים" : "Generate PDF for all created"}
            />
          </View>
          <View style={[styles.toggleRow, isRTL && styles.toggleRowRtl]}>
            <Text style={[styles.toggleLabel, isRTL && styles.rtl]}>
              {language === "he" ? "שלח אימייל (כשיש כתובת)" : "Email customers (when address exists)"}
            </Text>
            <AppSwitch
              value={emailCustomers}
              onValueChange={setEmailCustomers}
              onColor={theme.colors.success}
              accessibilityLabel={language === "he" ? "שלח אימייל (כשיש כתובת)" : "Email customers (when address exists)"}
            />
          </View>
        </View>
      ) : null}
      <View style={styles.summaryStrip}>
        <Text style={[styles.summaryText, isRTL && styles.rtl]}>
          {language === "he"
            ? `${totalCount} תשלומים ללא קבלה · ${formatIls(totalAmount)}`
            : `${totalCount} payments without receipt · ${formatIls(totalAmount)}`}
        </Text>
        <View style={[styles.summaryStripActions, isRTL && styles.summaryStripActionsRtl]}>
        <SortToggleButton
          value={sortOrder}
          onChange={setSortOrder}
          ascLabel={language === "he" ? "מהישן לחדש" : "Oldest first"}
          descLabel={language === "he" ? "מהחדש לישן" : "Newest first"}
        />
        {selectableRows.length > 0 ? (
          <Pressable onPress={toggleSelectAll} style={styles.selectAllBtn}>
            <Text style={styles.selectAllText}>
              {allSelected
                ? language === "he"
                  ? "בטל הכל"
                  : "Clear all"
                : language === "he"
                  ? "בחר הכל"
                  : "Select all"}
            </Text>
          </Pressable>
        ) : null}
        </View>
      </View>
    </>
  );

  if (!enabled) {
    return (
      <View style={styles.disabledBox}>
        <Text style={[styles.disabledText, isRTL && styles.rtl]}>
          {language === "he" ? "הפקת מסמכים כבויה — הפעילו בהגדרות." : "Document generation is off — enable in Settings."}
        </Text>
      </View>
    );
  }

  return (
    <View style={styles.wrap}>
      <FlatList
        style={styles.list}
        data={loading ? [] : sortedRows}
        keyExtractor={(x) => x.row_id}
        renderItem={renderRow}
        ListHeaderComponent={listHeader}
        ListEmptyComponent={
          loading ? (
            <ActivityIndicator color={theme.colors.cta} style={styles.loader} />
          ) : (
            <View style={styles.emptyBox}>
              <Text style={[styles.emptyTitle, isRTL && styles.rtl]}>
                {language === "he" ? "אין תשלומים ממתינים לקבלה" : "No payments pending receipt"}
              </Text>
              <Text style={[styles.emptyHint, isRTL && styles.rtl]}>
                {language === "he"
                  ? "כל התשלומים בטווח כבר קיבלו קבלה."
                  : "All payments in this range already have receipts."}
              </Text>
            </View>
          )
        }
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={() => {
              setRefreshing(true);
              void load();
            }}
            tintColor={theme.colors.cta}
          />
        }
        contentContainerStyle={styles.listContent}
      />

      {selectedCount > 0 ? (
        <View style={[styles.footer, isRTL && styles.footerRtl]}>
          <View style={styles.footerCopy}>
            <Text style={[styles.footerTitle, isRTL && styles.rtl]}>
              {language === "he" ? `${selectedCount} נבחרו` : `${selectedCount} selected`}
            </Text>
            <Text style={[styles.footerSub, isRTL && styles.rtl]}>{formatIls(selectedTotal)}</Text>
          </View>
          <PrimaryButton
            label={
              generatePdfs
                ? language === "he"
                  ? "הפק + PDF"
                  : "Create + PDF"
                : language === "he"
                  ? "הפק קבלות"
                  : "Create receipts"
            }
            onPress={() => void createSelected()}
            disabled={creating}
            loading={creating}
            loadingLabel={t("common.loading")}
            style={styles.footerBtn}
          />
        </View>
      ) : null}

      <CreateReceiptWithPaymentModal
        visible={createPaymentOpen}
        onClose={() => setCreatePaymentOpen(false)}
        onCreated={async () => {
          await onCreated();
          await load();
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { flex: 1 },
  list: { flex: 1 },
  listContent: { paddingHorizontal: theme.spacing.md, paddingBottom: 120, gap: theme.spacing.sm },
  loader: { marginTop: 32 },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
  },
  cardLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  bulkOpts: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
  },
  toggleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: theme.spacing.md },
  toggleRowRtl: { flexDirection: "row-reverse" },
  toggleLabel: { flex: 1, fontSize: 14, fontWeight: "700", color: theme.colors.text },
  summaryStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
  },
  summaryText: { flex: 1, fontSize: 13, fontWeight: "700", color: theme.colors.textMuted },
  summaryStripActions: { flexDirection: "row", alignItems: "center", gap: theme.spacing.sm },
  summaryStripActionsRtl: { flexDirection: "row-reverse" },
  selectAllBtn: { paddingVertical: 6, paddingHorizontal: 10 },
  selectAllText: { fontSize: 13, fontWeight: "800", color: theme.colors.cta },
  row: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: 6,
  },
  rowSelected: { borderColor: theme.colors.cta, backgroundColor: "rgba(59, 130, 246, 0.06)" },
  rowDisabled: { opacity: 0.55 },
  rowTop: { flexDirection: "row", alignItems: "flex-start", gap: theme.spacing.sm },
  rowTopRtl: { flexDirection: "row-reverse" },
  check: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: theme.colors.borderMuted,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  checkOn: { backgroundColor: theme.colors.cta, borderColor: theme.colors.cta },
  checkDisabled: { borderColor: theme.colors.borderMuted },
  checkMark: { color: theme.colors.ctaText, fontSize: 13, fontWeight: "900" },
  rowMain: { flex: 1, gap: 2 },
  payeeName: { fontSize: 15, fontWeight: "800", color: theme.colors.text },
  rowMeta: { fontSize: 13, fontWeight: "600", color: theme.colors.textMuted, lineHeight: 18 },
  rowSub: { fontSize: 12, fontWeight: "600", color: theme.colors.textSoft },
  amount: { fontSize: 16, fontWeight: "800", color: theme.colors.cta },
  warn: { fontSize: 12, fontWeight: "700", color: theme.colors.error, marginTop: 4 },
  emptyBox: { paddingVertical: 40, alignItems: "center", gap: 8 },
  emptyTitle: { fontSize: 16, fontWeight: "800", color: theme.colors.text },
  emptyHint: { fontSize: 14, fontWeight: "500", color: theme.colors.textMuted, textAlign: "center" },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
    paddingBottom: theme.spacing.lg,
    backgroundColor: theme.colors.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
  },
  footerRtl: { flexDirection: "row-reverse" },
  footerCopy: { flex: 1 },
  footerTitle: { fontSize: 15, fontWeight: "800", color: theme.colors.text },
  footerSub: { fontSize: 13, fontWeight: "700", color: theme.colors.textMuted, marginTop: 2 },
  footerBtn: { minWidth: 140 },
  disabledBox: {
    margin: theme.spacing.md,
    padding: theme.spacing.md,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  disabledText: { fontSize: 14, fontWeight: "600", color: theme.colors.textMuted, textAlign: "center" },
  rtl: { textAlign: "right", writingDirection: "rtl" },
});
