import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import {
  ActivityIndicator,
  FlatList,
  Platform,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import * as Linking from "expo-linking";
import { Stack } from "expo-router";
import { theme } from "../theme";
import { AppIcon } from "../components/AppIcon";
import { useI18n } from "../context/I18nContext";
import { useAuth } from "../context/AuthContext";
import { useAppAlert } from "../context/AppAlertContext";
import { useToast } from "../context/ToastContext";
import { useBulkJobs } from "../context/BulkJobsContext";
import { ManagerMoneyHubTabs, ManagerStatePillTabBar } from "../components/ManagerOverviewTabs";
import { ListRowSkeleton } from "../components/ListRowSkeleton";
import { AppSwitch } from "../components/AppSwitch";
import { FadeSlideIn } from "../components/FadeSlideIn";
import { CrossfadeSwap } from "../components/CrossfadeSwap";
import { useCountUp } from "../hooks/useCountUp";
import { CollapsibleDateRangeCard } from "../components/CollapsibleDateRangeCard";
import { PrimaryButton } from "../components/PrimaryButton";
import { PendingReceiptsPanel } from "../components/PendingReceiptsPanel";
import { SortToggleButton } from "../components/SortToggleButton";
import { GoLiveReadinessSection } from "../components/GoLiveReadinessSection";
import { ReceiptRequirementsTestingSection } from "../components/ReceiptRequirementsTestingSection";
import { EditCustomerEmailModal } from "../components/EditCustomerEmailModal";
import { PayeePickerModal, type PayeePickerRow } from "../components/PayeePickerModal";
import { isFullCalendarMonthRangeISO, lastNDaysRangeISO } from "../lib/isoDate";
import {
  autoGenerateDocumentPdfIfReady,
  cancelDocument,
  deleteDocumentFull,
  deleteMonthlySummaryReport,
  fetchDocumentReport,
  fetchMonthlySummaries,
  fetchReceiptSettings,
  getDocumentPdfSignedUrl,
  getMonthlySummaryPdfSignedUrl,
  invokeGenerateDocumentPdf,
  invokeGenerateMonthlySummaryPdf,
  invokeSendDocumentEmail,
  invokeSendDocumentsEmail,
  invokeSendMonthlySummaryEmail,
  listDocuments,
  logDocumentEvent,
  prepareDocumentPdfRegeneration,
  publishLegalDocument,
  setDocumentPaymentMethod,
  updateReceiptSettings,
  vatPercentLabel,
  formatIls,
  type DocumentCustomerType,
  type DocumentRow,
  type DocumentReportRow,
  type MonthlySummaryRow,
  type ReceiptSettings,
} from "../lib/documents";
import { DOCUMENT_PAYMENT_METHOD_KEYS, documentPaymentMethodLabel } from "../lib/documentPaymentMethod";
import { documentServiceTypeLabel } from "../lib/documentServiceTypes";
import { buildCsv, downloadCsvWeb } from "../lib/csvExport";
import { supabase } from "../lib/supabase";
import { formatDateTimeForDisplay, formatISODateFull } from "../lib/dateFormat";
import { rowFlipFor, userContentTextProps } from "../lib/layoutDirection";
import { useScreenContentStyle } from "../hooks/useScreenLayout";

type HubSection = "pending" | "documents" | "reports" | "settings";

function customerTypeBadgeLabel(type: DocumentCustomerType | null | undefined, language: "he" | "en"): string | null {
  if (!type || type === "regular") return null;
  if (type === "manual") return language === "he" ? "מהיר" : "Quick-add";
  return language === "he" ? "משפחה" : "Family";
}

type PayeeFilter = { type: "all" } | { type: "app" | "manual"; id: string; label: string };

function matchesPayeeFilter(doc: DocumentRow, filter: PayeeFilter): boolean {
  if (filter.type === "all") return true;
  if (filter.type === "app") return doc.customer_profile_user_id === filter.id;
  return doc.customer_manual_participant_id === filter.id;
}

function parseMoney(raw: string): number | null {
  const n = Number.parseFloat(raw.replace(",", ".").trim());
  return Number.isFinite(n) ? n : null;
}

function statusBadgeStyle(status: DocumentRow["status"]) {
  if (status === "ACTIVE") return styles.badgeActive;
  if (status === "CANCELLED") return styles.badgeCancelled;
  return styles.badgePending;
}

function statusLabel(status: DocumentRow["status"], language: "he" | "en") {
  if (status === "ACTIVE") return language === "he" ? "פעיל" : "Active";
  if (status === "CANCELLED") return language === "he" ? "בוטל" : "Cancelled";
  return language === "he" ? "דרוש תשלום" : "Needs method";
}

function SectionCard({ label, children }: { label: string; children: ReactNode }) {
  return (
    <View style={styles.card}>
      <Text style={styles.cardLabel}>{label}</Text>
      {children}
    </View>
  );
}

function ToggleRow({
  title,
  subtitle,
  value,
  onChange,
  isRTL,
}: {
  title: string;
  subtitle?: string;
  value: boolean;
  onChange: (v: boolean) => void;
  isRTL: boolean;
}) {
  return (
    <View style={[styles.toggleRow, rowFlipFor(isRTL) && styles.toggleRowRtl]}>
      <View style={styles.toggleCopy}>
        <Text style={[styles.toggleTitle, isRTL && styles.rtl]}>{title}</Text>
        {subtitle ? <Text style={[styles.toggleSub, isRTL && styles.rtl]}>{subtitle}</Text> : null}
      </View>
      <AppSwitch value={value} onValueChange={onChange} onColor={theme.colors.success} accessibilityLabel={title} />
    </View>
  );
}

function HubTabs({
  tabs,
  active,
  onChange,
}: {
  tabs: { id: HubSection; label: string }[];
  active: HubSection;
  onChange: (id: HubSection) => void;
}) {
  return (
    <ManagerStatePillTabBar
      tabs={tabs}
      active={active}
      onChange={(id) => onChange(id as HubSection)}
      density="compact"
    />
  );
}

export default function DocumentsInvoicesScreen() {
  const { language, t, isRTL } = useI18n();
  const screenContent = useScreenContentStyle("standard");
  const { profile } = useAuth();
  const { showConfirm, showAlert } = useAppAlert();
  const { showToast } = useToast();
  const isManager = profile?.role === "manager";
  const isCoach = profile?.role === "coach";
  const lang = ((language === "he" ? "he" : "en"));

  const [section, setSection] = useState<HubSection>("pending");
  const [settings, setSettings] = useState<ReceiptSettings | null>(null);
  const [settingsForm, setSettingsForm] = useState<Partial<ReceiptSettings>>({});
  const [documents, setDocuments] = useState<DocumentRow[]>([]);
  const [reportRows, setReportRows] = useState<DocumentReportRow[]>([]);
  const [monthlySummaries, setMonthlySummaries] = useState<MonthlySummaryRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [savingSettings, setSavingSettings] = useState(false);
  const [consentTitle, setConsentTitle] = useState("");
  const [consentBody, setConsentBody] = useState("");
  const defaultRange = useMemo(() => lastNDaysRangeISO(30), []);
  const [dateStart, setDateStart] = useState(defaultRange.start);
  const [dateEnd, setDateEnd] = useState(defaultRange.end);
  const [payeeFilter, setPayeeFilter] = useState<PayeeFilter>({ type: "all" });
  const [docsSortOrder, setDocsSortOrder] = useState<"asc" | "desc">("desc");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [payeePickerOpen, setPayeePickerOpen] = useState(false);
  const [pdfBusyId, setPdfBusyId] = useState<string | null>(null);
  const [accountantBusyId, setAccountantBusyId] = useState<string | null>(null);
  const [bulkAccountantBusy, setBulkAccountantBusy] = useState(false);
  const [monthlySummaryBusy, setMonthlySummaryBusy] = useState(false);
  const [deletingSummaryId, setDeletingSummaryId] = useState<string | null>(null);
  const [cancelBusyId, setCancelBusyId] = useState<string | null>(null);
  const [deleteDocBusyId, setDeleteDocBusyId] = useState<string | null>(null);
  const [editEmailDoc, setEditEmailDoc] = useState<DocumentRow | null>(null);
  const { job: bulkJob, runJob: runBulkJob, cancelJob: cancelBulkJob } = useBulkJobs();
  const bulkRegenProgress = bulkJob?.key === "regenerateAllReceiptPdfs" ? bulkJob : null;
  const bulkRegenBusy = bulkRegenProgress !== null;
  const regenFetchingRef = useRef(false);
  const [regenAllDates, setRegenAllDates] = useState(true);
  const [regenDateStart, setRegenDateStart] = useState(defaultRange.start);
  const [regenDateEnd, setRegenDateEnd] = useState(defaultRange.end);

  const canCancelDocument = isManager || (isCoach && !!settings?.staff_can_cancel_documents);

  const filteredDocuments = useMemo(
    () => documents.filter((d) => matchesPayeeFilter(d, payeeFilter)),
    [documents, payeeFilter]
  );

  const sortedDocuments = useMemo(() => {
    return [...filteredDocuments].sort((a, b) => {
      const aTime = new Date(a.paid_at).getTime();
      const bTime = new Date(b.paid_at).getTime();
      if (aTime !== bTime) return docsSortOrder === "asc" ? aTime - bTime : bTime - aTime;
      const cmp = a.document_number.localeCompare(b.document_number);
      return docsSortOrder === "asc" ? cmp : -cmp;
    });
  }, [filteredDocuments, docsSortOrder]);

  const reportTotals = useMemo(() => {
    const active = reportRows.filter((r) => r.status === "ACTIVE");
    return {
      count: reportRows.length,
      gross: active.reduce((s, r) => s + Number(r.gross_amount), 0),
      vat: active.reduce((s, r) => s + Number(r.vat_amount), 0),
    };
  }, [reportRows]);

  const isFullMonthRange = useMemo(() => isFullCalendarMonthRangeISO(dateStart, dateEnd), [dateStart, dateEnd]);

  const reportCountDisplay = useCountUp(reportTotals.count);
  const reportGrossDisplay = useCountUp(reportTotals.gross);
  const reportVatDisplay = useCountUp(reportTotals.vat);

  /** Only summaries whose period overlaps the currently selected date range. */
  const filteredMonthlySummaries = useMemo(() => {
    const filterStart = new Date(`${dateStart}T00:00:00.000Z`).getTime();
    const filterEnd = new Date(`${dateEnd}T23:59:59.999Z`).getTime();
    return monthlySummaries.filter((row) => {
      const summaryStart = new Date(row.period_start).getTime();
      const summaryEnd = new Date(row.period_end).getTime();
      return summaryStart <= filterEnd && summaryEnd >= filterStart;
    });
  }, [monthlySummaries, dateStart, dateEnd]);

  const load = useCallback(async () => {
    try {
      const s = await fetchReceiptSettings();
      setSettings(s);
      if (s) {
        setSettingsForm({
          business_id: s.business_id,
          business_name: s.business_name,
          address: s.address,
          phone: s.phone,
          email: s.email,
          accountant_email: s.accountant_email ?? "",
          digital_receipts_enabled: s.digital_receipts_enabled,
          vat_rate: s.vat_rate,
          vat_enabled: s.vat_enabled,
          document_prefix: s.document_prefix,
          staff_can_cancel_documents: s.staff_can_cancel_documents,
          is_operational: s.is_operational,
          request_address_from_existing_users: s.request_address_from_existing_users ?? false,
          request_consent_from_existing_users: s.request_consent_from_existing_users ?? false,
          next_document_number: s.next_document_number,
        });
      }
      const startIso = `${dateStart}T00:00:00.000Z`;
      const endIso = `${dateEnd}T23:59:59.999Z`;
      try {
        const { rows } = await listDocuments({
          date_start: startIso,
          date_end: endIso,
        });
        setDocuments(rows);
      } catch (e) {
        setDocuments([]);
        showToast({
          message: t("ui.documentsInvoices.failedToLoadDocuments"),
          detail: e instanceof Error ? e.message : String(e),
          variant: "error",
        });
      }
      if (isManager) {
        try {
          setReportRows(await fetchDocumentReport(startIso, endIso));
        } catch {
          setReportRows([]);
        }
        try {
          setMonthlySummaries(await fetchMonthlySummaries());
        } catch {
          setMonthlySummaries([]);
        }
      }
      const { data: legal } = await supabase.rpc("get_current_legal_document", {
        p_consent_type: "electronic_receipts",
      });
      const legalRow = legal as { ok?: boolean; document?: { title: string; body_text: string } };
      if (legalRow?.ok && legalRow.document) {
        setConsentTitle(legalRow.document.title);
        setConsentBody(legalRow.document.body_text);
      }
    } catch (e) {
      showToast({
        message: t("common.error"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [dateStart, dateEnd, isManager, showToast, t]);

  useEffect(() => {
    void load();
  }, [load]);

  async function saveSettings() {
    if (!isManager) return;
    setSavingSettings(true);
    try {
      const vatPct = parseMoney(String((settingsForm.vat_rate ?? 0.18) * 100));
      const updated = await updateReceiptSettings({
        business_id: settingsForm.business_id,
        business_name: settingsForm.business_name,
        address: settingsForm.address,
        phone: settingsForm.phone,
        email: settingsForm.email,
        accountant_email: settingsForm.accountant_email,
        digital_receipts_enabled: settingsForm.digital_receipts_enabled,
        vat_rate: vatPct != null ? vatPct / 100 : undefined,
        vat_enabled: settingsForm.vat_enabled,
        document_prefix: settingsForm.document_prefix,
        staff_can_cancel_documents: settingsForm.staff_can_cancel_documents,
        is_operational: settingsForm.is_operational,
        request_address_from_existing_users: settingsForm.request_address_from_existing_users,
        request_consent_from_existing_users: settingsForm.request_consent_from_existing_users,
        next_document_number: settingsForm.is_operational ? undefined : settingsForm.next_document_number,
      });
      setSettings(updated);
      showToast({ message: t("ui.documentsInvoices.settingsSaved"), variant: "success" });
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    } finally {
      setSavingSettings(false);
    }
  }

  async function openPdf(doc: DocumentRow) {
    if (!doc.pdf_url) {
      showToast({ message: t("ui.documentsInvoices.pdfNotReady"), variant: "error" });
      return;
    }
    try {
      const url = await getDocumentPdfSignedUrl(doc.pdf_url, doc.signature_hash ?? doc.id);
      await logDocumentEvent(doc.id, "document_viewed");
      if (Platform.OS === "web") window.open(url, "_blank", "noopener,noreferrer");
      else await Linking.openURL(url);
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    }
  }

  async function generatePdf(doc: DocumentRow) {
    if (pdfBusyId) return;
    setPdfBusyId(doc.id);
    const hadPdf = !!doc.pdf_url;
    try {
      if (doc.pdf_url) {
        await prepareDocumentPdfRegeneration(doc.id);
        await invokeGenerateDocumentPdf(doc.id, true);
      } else {
        // A cancelled receipt may still have its pre-cancellation PDF sitting in storage
        // (the auto-reissue on cancel can fail); always overwrite so retrying here can't
        // collide with that stale file.
        await invokeGenerateDocumentPdf(doc.id, doc.status === "CANCELLED" || !settings?.is_operational);
      }
      await load();
      showToast({
        message: hadPdf
          ? t("ui.documentsInvoices.pdfRegenerated")
          : t("ui.documentsInvoices.pdfGenerated"),
        variant: "success",
      });
    } catch (e) {
      showToast({
        message: t("ui.documentsInvoices.pdfGenerationFailed"),
        detail: e instanceof Error ? e.message : String(e),
        variant: "error",
      });
    } finally {
      setPdfBusyId(null);
    }
  }

  async function regeneratePdf(doc: DocumentRow) {
    await generatePdf(doc);
  }

  async function sendToAccountant(doc: DocumentRow) {
    const accountant = settings?.accountant_email?.trim();
    if (!accountant) {
      showToast({
        message: t("ui.documentsInvoices.setAccountantEmailInSettings"),
        variant: "error",
      });
      return;
    }
    if (!doc.pdf_url) {
      showToast({ message: t("ui.documentsInvoices.pdfNotReady"), variant: "error" });
      return;
    }
    setAccountantBusyId(doc.id);
    try {
      await invokeSendDocumentEmail(doc.id, accountant);
      showToast({
        message: t("ui.documentsInvoices.sentToAccountant"),
        variant: "success",
      });
      void load();
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    } finally {
      setAccountantBusyId(null);
    }
  }

  async function cancelReceipt(doc: DocumentRow, revertPayment: boolean) {
    if (cancelBusyId) return;
    setCancelBusyId(doc.id);
    try {
      const { needsPdfReissue } = await cancelDocument(doc.id, "בוטל על ידי מנהל", revertPayment);
      let pdfReissueFailed = false;
      if (needsPdfReissue) {
        try {
          await invokeGenerateDocumentPdf(doc.id, true);
        } catch {
          pdfReissueFailed = true;
        }
      }
      await load();
      if (pdfReissueFailed) {
        showToast({
          message: t("ui.documentsInvoices.receiptCancelledButReissuingTheCancelled"),
          detail: t("ui.documentsInvoices.youCanRetryFromTheRegen"),
          variant: "info",
        });
      } else {
        showToast({
          message: language === "he"
            ? revertPayment
              ? "הקבלה בוטלה והתשלום שוחזר"
              : "הקבלה בוטלה, התשלום נשמר"
            : revertPayment
              ? "Receipt cancelled and payment reverted"
              : "Receipt cancelled, payment kept",
          variant: "success",
        });
      }
    } catch (e) {
      showToast({
        message: t("ui.documentsInvoices.failedToCancelReceipt"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setCancelBusyId(null);
    }
  }

  function confirmCancelReceipt(doc: DocumentRow) {
    const title = t("ui.documentsInvoices.cancelReceipt");
    const message =
      t("ui.documentsInvoices.theReceiptWillBeMarkedCancelled");
    showAlert({
      title,
      message,
      actions: [
        { label: t("common.cancel"), variant: "secondary", onPress: () => {} },
        {
          label: t("ui.documentsInvoices.cancelReceiptKeepPayment"),
          variant: "secondary",
          onPress: () => void cancelReceipt(doc, false),
        },
        {
          label: t("ui.documentsInvoices.cancelReceiptRevertPayment"),
          variant: "danger",
          onPress: () => void cancelReceipt(doc, true),
        },
      ],
    });
  }

  async function deleteReceipt(doc: DocumentRow, deletePayment: boolean) {
    if (deleteDocBusyId) return;
    setDeleteDocBusyId(doc.id);
    try {
      await deleteDocumentFull(doc.id, deletePayment);
      await load();
      showToast({
        message: language === "he"
          ? deletePayment
            ? "הקבלה נמחקה לצמיתות והתשלום נמחק"
            : "הקבלה נמחקה לצמיתות, התשלום נשמר"
          : deletePayment
            ? "Receipt permanently deleted and payment deleted"
            : "Receipt permanently deleted, payment kept",
        variant: "success",
      });
    } catch (e) {
      showToast({
        message: t("ui.documentsInvoices.failedToDeleteReceipt"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setDeleteDocBusyId(null);
    }
  }

  function confirmDeleteReceipt(doc: DocumentRow) {
    const title = t("ui.documentsInvoices.deleteReceipt");
    const message =
      t("ui.documentsInvoices.theReceiptItsPdfAndIts");
    showAlert({
      title,
      message,
      actions: [
        { label: t("common.cancel"), variant: "secondary", onPress: () => {} },
        {
          label: t("ui.documentsInvoices.deleteKeepPayment"),
          variant: "danger",
          onPress: () => void deleteReceipt(doc, false),
        },
        {
          label: t("ui.documentsInvoices.deleteDeletePayment"),
          variant: "danger",
          onPress: () => void deleteReceipt(doc, true),
        },
      ],
    });
  }
  /** One-time maintenance: after document_number values are reassigned in bulk (e.g. renumbering
   * by payment date), already-generated PDF files still show the old number baked into the file.
   * Regenerates every ACTIVE document's PDF so the file matches the current number. Testing-mode
   * only — the generate-document-pdf function refuses to overwrite once operational. */
  async function regenerateAllPdfs() {
    if (bulkJob || regenFetchingRef.current) return;
    regenFetchingRef.current = true;
    // Fetch fresh regardless of the main list's currently-selected filter — this maintenance
    // pass uses its own date range (or all dates), set separately below.
    let allDocs: DocumentRow[] = [];
    try {
      allDocs = (await listDocuments({ limit: 500 })).rows;
    } catch (e) {
      regenFetchingRef.current = false;
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
      return;
    }
    const rangeStartMs = regenAllDates ? null : new Date(`${regenDateStart}T00:00:00.000Z`).getTime();
    const rangeEndMs = regenAllDates ? null : new Date(`${regenDateEnd}T23:59:59.999Z`).getTime();
    const targets = allDocs.filter((d) => {
      if (d.status !== "ACTIVE") return false;
      if (rangeStartMs === null || rangeEndMs === null) return true;
      const paidAtMs = new Date(d.paid_at).getTime();
      return paidAtMs >= rangeStartMs && paidAtMs <= rangeEndMs;
    });
    regenFetchingRef.current = false;
    if (targets.length === 0) {
      showToast({
        message: t("ui.documentsInvoices.noActiveReceiptsInTheSelected"),
        variant: "info",
      });
      return;
    }

    // Runs inside the app-wide bulk-job context, not local component state, so it keeps going
    // (and stays visible) even if the manager navigates to another screen mid-run.
    await runBulkJob("regenerateAllReceiptPdfs", targets.length, async (setDone, isCancelled) => {
      let failed = 0;
      let i = 0;
      for (; i < targets.length; i++) {
        if (isCancelled()) break;
        try {
          await prepareDocumentPdfRegeneration(targets[i].id);
          await invokeGenerateDocumentPdf(targets[i].id, true);
        } catch {
          failed += 1;
        }
        setDone(i + 1);
      }
      await load();
      const cancelled = isCancelled();
      const doneCount = i;
      const succeeded = doneCount - failed;
      showToast({
        message: cancelled
          ? language === "he"
            ? `בוטל — ${succeeded} מתוך ${targets.length} PDF-ים נוצרו מחדש${failed ? ` · ${failed} נכשלו` : ""}`
            : `Cancelled — ${succeeded} of ${targets.length} PDFs regenerated${failed ? ` · ${failed} failed` : ""}`
          : language === "he"
            ? `${succeeded} מתוך ${targets.length} PDF-ים נוצרו מחדש${failed ? ` · ${failed} נכשלו` : ""}`
            : `${succeeded} of ${targets.length} PDFs regenerated${failed ? ` · ${failed} failed` : ""}`,
        variant: failed ? "info" : "success",
      });
    });
  }

  function cancelRegenerateAllPdfs() {
    cancelBulkJob("regenerateAllReceiptPdfs");
  }

  function confirmRegenerateAllPdfs() {
    const scope = regenAllDates
      ? t("ui.documentsInvoices.acrossAllDates")
      : language === "he"
        ? `בין ${formatISODateFull(regenDateStart, language)} ל-${formatISODateFull(regenDateEnd, language)}`
        : `between ${formatISODateFull(regenDateStart, language)} and ${formatISODateFull(regenDateEnd, language)}`;
    showConfirm({
      title: t("ui.documentsInvoices.regeneratePdfs"),
      message:
        language === "he"
          ? `יופקו מחדש כל קבצי ה-PDF הפעילים עם המספרים הנוכחיים שלהם, ${scope}. פעולה זו עלולה לקחת זמן.`
          : `Regenerates every active PDF file with its current number, ${scope}. This may take a while.`,
      cancelLabel: t("common.cancel"),
      confirmLabel: t("ui.documentsInvoices.regenerate"),
      onConfirm: () => void regenerateAllPdfs(),
    });
  }

  async function sendAllToAccountant() {
    const accountant = settings?.accountant_email?.trim();
    if (!accountant) {
      showToast({
        message: t("ui.documentsInvoices.setAccountantEmailInSettings"),
        variant: "error",
      });
      return;
    }
    const eligible = filteredDocuments.filter((d) => d.status === "ACTIVE" && d.pdf_url);
    if (eligible.length === 0) {
      showToast({
        message: t("ui.documentsInvoices.noDocumentsWithPdfInRange"),
        variant: "info",
      });
      return;
    }
    setBulkAccountantBusy(true);
    try {
      const result = await invokeSendDocumentsEmail({
        documentIds: eligible.map((d) => d.id),
        mode: "accountant",
        recipientEmail: accountant,
      });
      showToast({
        message:
          language === "he"
            ? `נשלח אימייל אחד לרו״ח עם ${result.documents_sent} קבלות`
            : `1 email sent to accountant with ${result.documents_sent} receipt(s)`,
        variant: "success",
      });
      void load();
    } catch (e) {
      showToast({
        message: t("ui.documentsInvoices.failedToSendToAccountant"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setBulkAccountantBusy(false);
    }
  }

  async function generateMonthlySummary() {
    if (monthlySummaryBusy) return;
    if (!isFullMonthRange) {
      showToast({
        message:
          t("ui.documentsInvoices.summariesCanOnlyBeGeneratedFor"),
        variant: "error",
      });
      return;
    }
    setMonthlySummaryBusy(true);
    try {
      const { summaryId, pdfPath } = await invokeGenerateMonthlySummaryPdf(dateStart, dateEnd);
      const accountant = settings?.accountant_email?.trim();
      if (accountant) {
        await invokeSendMonthlySummaryEmail(summaryId, accountant);
      }
      const url = await getMonthlySummaryPdfSignedUrl(pdfPath);
      if (Platform.OS === "web") window.open(url, "_blank", "noopener,noreferrer");
      else await Linking.openURL(url);
      showToast({
        message: accountant
          ? t("ui.documentsInvoices.summaryGeneratedAndEmailedToAccountant")
          : t("ui.documentsInvoices.summaryGenerated"),
        variant: "success",
      });
      try {
        setMonthlySummaries(await fetchMonthlySummaries());
      } catch {
        /* list refresh is best-effort */
      }
    } catch (e) {
      showToast({
        message: t("ui.documentsInvoices.failedToGenerateSummary"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setMonthlySummaryBusy(false);
    }
  }

  async function viewMonthlySummary(row: MonthlySummaryRow) {
    if (!row.pdf_url) return;
    try {
      const url = await getMonthlySummaryPdfSignedUrl(row.pdf_url);
      if (Platform.OS === "web") window.open(url, "_blank", "noopener,noreferrer");
      else await Linking.openURL(url);
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    }
  }

  function confirmDeleteMonthlySummary(row: MonthlySummaryRow) {
    showConfirm({
      title: t("ui.documentsInvoices.deleteSummary"),
      message:
        t("ui.documentsInvoices.theMonthlySummaryAndItsPdf"),
      cancelLabel: t("common.cancel"),
      confirmLabel: t("ui.documentsInvoices.delete"),
      confirmVariant: "danger",
      onConfirm: () => void deleteMonthlySummary(row),
    });
  }

  async function deleteMonthlySummary(row: MonthlySummaryRow) {
    if (deletingSummaryId) return;
    setDeletingSummaryId(row.id);
    try {
      await deleteMonthlySummaryReport(row.id, row.pdf_url);
      setMonthlySummaries((rows) => rows.filter((r) => r.id !== row.id));
      showToast({ message: t("ui.documentsInvoices.summaryDeleted"), variant: "success" });
    } catch (e) {
      showToast({
        message: t("ui.documentsInvoices.failedToDeleteSummary"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setDeletingSummaryId(null);
    }
  }

  async function sendEmail(doc: DocumentRow) {
    const email = doc.customer_email?.trim();
    if (!email) {
      showToast({ message: t("ui.documentsInvoices.noCustomerEmail"), variant: "error" });
      return;
    }
    try {
      await invokeSendDocumentEmail(doc.id, email);
      showToast({ message: t("ui.documentsInvoices.sent"), variant: "success" });
      void load();
    } catch (e) {
      const message = e instanceof Error ? e.message : undefined;
      if (message === "email_provider_not_configured") {
        showToast({
          message: t("ui.documentsInvoices.emailSendingIsnTSetUp"),
          detail:
            t("ui.documentsInvoices.setResendApiKeyOnThe"),
          variant: "error",
        });
        return;
      }
      showToast({ message: t("common.error"), detail: message, variant: "error" });
    }
  }

  function exportCsv() {
    const vatOn = !!settings?.vat_enabled;
    const headers = [
      "document_number", "date", "customer", "gross",
      ...(vatOn ? ["net", "vat", "vat_rate"] : []),
      "payment_method", "service_type", "status",
    ];
    const rows = reportRows.map((r) => [
      r.document_number,
      r.paid_at.slice(0, 10),
      r.customer_name,
      String(r.gross_amount),
      ...(vatOn ? [String(r.net_amount), String(r.vat_amount), vatPercentLabel(r.vat_rate)] : []),
      r.payment_method ?? "",
      r.service_type,
      r.status,
    ]);
    const csv = buildCsv(headers, rows);
    if (Platform.OS === "web") downloadCsvWeb(`documents-${dateStart}-${dateEnd}.csv`, csv);
    else showToast({ message: t("ui.documentsInvoices.exportAvailableOnWeb"), variant: "info" });
  }

  const sectionTabs: { id: HubSection; label: string; managerOnly?: boolean }[] = [
    { id: "pending", label: t("ui.documentsInvoices.pendingReceipts") },
    { id: "documents", label: t("ui.documentsInvoices.documents") },
    { id: "reports", label: t("ui.documentsInvoices.reports"), managerOnly: true },
  ];

  const visibleTabs = sectionTabs.filter((x) => !x.managerOnly || isManager);

  function renderDocumentItem({ item, index }: { item: DocumentRow; index: number }) {
    const needsMethod = item.status === "NEEDS_PAYMENT_METHOD";
    const pdfBusy = pdfBusyId === item.id;
    const accountantBusy = accountantBusyId === item.id;
    const typeBadge = customerTypeBadgeLabel(item.customer_type, lang);
    const missingEmail = !item.customer_email?.trim();
    const isManual = item.customer_type === "manual" || !!item.customer_manual_participant_id;
    return (
      <FadeSlideIn delay={Math.min(index, theme.motion.maxStaggerIndex) * 30}>
      <View style={styles.docCard}>
        <View style={[styles.docHead, rowFlipFor(isRTL) && styles.docHeadRtl]}>
          <View style={styles.docHeadMain}>
            <View style={[styles.docTitleRow, rowFlipFor(isRTL) && styles.docTitleRowRtl]}>
              <Text style={[styles.docNumber, isRTL && styles.rtl]}>{item.document_number}</Text>
              {typeBadge ? (
                <View style={styles.typeBadge}>
                  <Text style={styles.typeBadgeText}>{typeBadge}</Text>
                </View>
              ) : null}
            </View>
            <Text {...userContentTextProps} style={[styles.docCustomer, isRTL && styles.userContentRtl]} numberOfLines={1}>
              {item.customer_name}
            </Text>
          </View>
          <View style={styles.docHeadEnd}>
            <Text style={styles.docAmount}>{formatIls(item.gross_amount)}</Text>
            <View style={[styles.badge, statusBadgeStyle(item.status)]}>
              <Text style={styles.badgeText}>{statusLabel(item.status, lang)}</Text>
            </View>
          </View>
        </View>

        <Text style={[styles.docMeta, isRTL && styles.rtl]}>
          {item.source_type === "account_payment"
            ? formatISODateFull(item.paid_at.slice(0, 10), lang)
            : formatDateTimeForDisplay(item.paid_at, lang)}
          {" · "}
          {documentServiceTypeLabel(item.service_type, lang)}
          {item.payment_method ? ` · ${documentPaymentMethodLabel(item.payment_method, lang)}` : ""}
        </Text>

        {needsMethod ? (
          <View style={styles.warnBox}>
            <Text style={[styles.warnText, isRTL && styles.rtl]}>
              {t("ui.documentsInvoices.selectAPaymentMethodForThis")}
            </Text>
          </View>
        ) : missingEmail ? (
          <View style={styles.warnBox}>
            <Text style={[styles.warnText, isRTL && styles.rtl]}>
              {isManual
                ? t("ui.documentsInvoices.noEmailAddManuallyOrSkip")
                : t("ui.documentsInvoices.noCustomerEmailUpdateBeforeSend")}
            </Text>
            {isManager ? (
              <Pressable onPress={() => setEditEmailDoc(item)} style={styles.warnAction}>
                <Text style={styles.warnActionText}>{t("ui.documentsInvoices.editEmail")}</Text>
              </Pressable>
            ) : null}
          </View>
        ) : !item.pdf_url && (item.status === "ACTIVE" || item.status === "CANCELLED") ? (
          <View style={styles.warnBox}>
            <Text style={[styles.warnText, isRTL && styles.rtl]}>
              {t("ui.documentsInvoices.pdfMissingTapGeneratePdf")}
            </Text>
          </View>
        ) : null}

        <View style={[styles.actionBar, rowFlipFor(isRTL) && styles.actionBarRtl]}>
          {!needsMethod && item.pdf_url ? (
            <Pressable onPress={() => void openPdf(item)} style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}>
              <Text style={[styles.actionText, isRTL && styles.rtl]}>{t("ui.documentsInvoices.view")}</Text>
            </Pressable>
          ) : null}
          {!needsMethod && !item.pdf_url && (item.status === "ACTIVE" || item.status === "CANCELLED") ? (
            <Pressable
              disabled={pdfBusy}
              onPress={() => void generatePdf(item)}
              style={({ pressed }) => [
                styles.actionItem,
                pdfBusy && styles.actionItemBusy,
                pressed && !pdfBusy && styles.actionItemPressed,
              ]}
            >
              {pdfBusy ? (
                <ActivityIndicator size="small" color={theme.colors.cta} />
              ) : (
                <Text style={[styles.actionText, isRTL && styles.rtl]}>{t("ui.documentsInvoices.generatePdf")}</Text>
              )}
            </Pressable>
          ) : null}
          {needsMethod
            ? DOCUMENT_PAYMENT_METHOD_KEYS.map((m) => (
                <Pressable
                  key={m}
                  onPress={() =>
                    void setDocumentPaymentMethod(item.id, m).then((res) =>
                      autoGenerateDocumentPdfIfReady(item.id, "ACTIVE", {
                        needsPdf: res.needs_pdf,
                        allowOverwrite: !settings?.is_operational,
                      }).finally(() => load())
                    )
                  }
                  style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}
                >
                  <Text style={[styles.actionText, isRTL && styles.rtl]}>
                    {documentPaymentMethodLabel(m, lang)}
                  </Text>
                </Pressable>
              ))
            : null}
          {isManager && !settings?.is_operational && item.pdf_url ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={pdfBusy}
                onPress={() => void regeneratePdf(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  pdfBusy && styles.actionItemBusy,
                  pressed && !pdfBusy && styles.actionItemPressed,
                ]}
              >
                {pdfBusy ? (
                  <ActivityIndicator size="small" color={theme.colors.cta} />
                ) : (
                  <Text style={[styles.actionText, isRTL && styles.rtl]}>{t("ui.documentsInvoices.regen")}</Text>
                )}
              </Pressable>
            </>
          ) : null}
          {isManager && item.customer_email && item.pdf_url ? (
            <>
              <View style={styles.actionSep} />
              <Pressable onPress={() => void sendEmail(item)} style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}>
                <Text style={[styles.actionText, isRTL && styles.rtl]}>{t("ui.documentsInvoices.send")}</Text>
              </Pressable>
            </>
          ) : null}
          {isManager && item.pdf_url && item.status === "ACTIVE" ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={accountantBusy}
                onPress={() => void sendToAccountant(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  accountantBusy && styles.actionItemBusy,
                  pressed && !accountantBusy && styles.actionItemPressed,
                ]}
              >
                {accountantBusy ? (
                  <ActivityIndicator size="small" color={theme.colors.cta} />
                ) : (
                  <Text style={[styles.actionText, isRTL && styles.rtl]}>
                    {t("ui.documentsInvoices.accountant")}
                  </Text>
                )}
              </Pressable>
            </>
          ) : null}
          {canCancelDocument && item.status === "ACTIVE" ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={cancelBusyId === item.id}
                onPress={() => confirmCancelReceipt(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  styles.actionItemDanger,
                  cancelBusyId === item.id && styles.actionItemBusy,
                  pressed && cancelBusyId !== item.id && styles.actionItemPressed,
                ]}
              >
                {cancelBusyId === item.id ? (
                  <ActivityIndicator size="small" color={theme.colors.error} />
                ) : (
                  <Text style={[styles.actionTextDanger, isRTL && styles.rtl]}>{t("ui.documentsInvoices.cancel")}</Text>
                )}
              </Pressable>
            </>
          ) : null}
          {isManager && !settings?.is_operational ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={deleteDocBusyId === item.id}
                onPress={() => confirmDeleteReceipt(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  styles.actionItemDanger,
                  deleteDocBusyId === item.id && styles.actionItemBusy,
                  pressed && deleteDocBusyId !== item.id && styles.actionItemPressed,
                ]}
              >
                {deleteDocBusyId === item.id ? (
                  <ActivityIndicator size="small" color={theme.colors.error} />
                ) : (
                  <Text style={[styles.actionTextDanger, isRTL && styles.rtl]}>{t("ui.documentsInvoices.delete")}</Text>
                )}
              </Pressable>
            </>
          ) : null}
        </View>
      </View>
      </FadeSlideIn>
    );
  }

  const pageHeader = (
    <View style={styles.headerBlock}>
      <View style={styles.tabBarRow}>
        <View style={styles.tabBarFill}>
          <HubTabs tabs={visibleTabs} active={section} onChange={setSection} />
        </View>
        {isManager ? (
          <Pressable
            onPress={() => setSection("settings")}
            hitSlop={10}
            style={({ pressed }) => [styles.settingsGear, pressed && { opacity: 0.6 }]}
            accessibilityRole="button"
            accessibilityLabel={t("ui.documentsInvoices.settings")}
          >
            <AppIcon name="settings-outline" size="md" color={section === "settings" ? theme.colors.text : theme.colors.textMuted} />
          </Pressable>
        ) : null}
      </View>
      {!settings?.is_operational && settings?.digital_receipts_enabled ? (
        <View style={styles.testingBanner}>
          <Text style={[styles.testingText, isRTL && styles.rtl]}>
            {t("ui.documentsInvoices.testingModeVoidReceiptsAndRegenerate")}
          </Text>
        </View>
      ) : null}
    </View>
  );

  const settingsContent = (
    <ScrollView contentContainerStyle={[styles.scrollContent, screenContent]} keyboardShouldPersistTaps="handled">
      {pageHeader}
      <GoLiveReadinessSection isRTL={isRTL} language={lang} />
      <ReceiptRequirementsTestingSection
        isRTL={isRTL}
        language={lang}
        addressLabel={t("profile.address")}
        zipLabel={t("profile.zipCode")}
        consentEnabled={!!settingsForm.request_consent_from_existing_users}
        addressEnabled={!!settingsForm.request_address_from_existing_users}
      />

      {isManager && !settings?.is_operational ? (
        <SectionCard label={t("ui.documentsInvoices.regenerateAllReceiptPdfs")}>
          <Text style={[styles.filterHint, isRTL && styles.rtl]}>
            {t("ui.documentsInvoices.useThisAfterABulkChange")}
          </Text>
          {!bulkRegenBusy ? (
            <>
              <ToggleRow
                isRTL={isRTL}
                title={t("ui.documentsInvoices.allDates")}
                subtitle={
                  t("ui.documentsInvoices.turnOffToLimitRegenerationTo")
                }
                value={regenAllDates}
                onChange={setRegenAllDates}
              />
              {!regenAllDates ? (
                <CollapsibleDateRangeCard
                  start={regenDateStart}
                  end={regenDateEnd}
                  onChange={({ start, end }) => {
                    setRegenDateStart(start);
                    setRegenDateEnd(end);
                  }}
                  label={t("ui.documentsInvoices.paymentDateRange")}
                />
              ) : null}
            </>
          ) : null}
          {bulkRegenBusy && bulkRegenProgress ? (
            <>
              <View style={styles.bulkRegenProgressRow}>
                <ActivityIndicator size="small" color={theme.colors.cta} />
                <Text style={[styles.bulkRegenProgressText, isRTL && styles.rtl]}>
                  {bulkRegenProgress.cancelling
                    ? t("ui.documentsInvoices.cancelling")
                    : language === "he"
                      ? `יוצר מחדש ${bulkRegenProgress.done} מתוך ${bulkRegenProgress.total}…`
                      : `Regenerating ${bulkRegenProgress.done} of ${bulkRegenProgress.total}…`}
                </Text>
              </View>
              <PrimaryButton
                label={t("ui.documentsInvoices.cancel")}
                onPress={cancelRegenerateAllPdfs}
                disabled={bulkRegenProgress.cancelling}
                variant="ghost"
              />
            </>
          ) : (
            <PrimaryButton
              label={
                regenAllDates
                  ? t("ui.documentsInvoices.regenerateAllPdfs")
                  : t("ui.documentsInvoices.regeneratePdfsInRange")
              }
              onPress={confirmRegenerateAllPdfs}
              disabled={bulkRegenBusy || regenFetchingRef.current}
            />
          )}
        </SectionCard>
      ) : null}

      <SectionCard label={t("ui.documentsInvoices.system")}>
        <ToggleRow
          isRTL={isRTL}
          title={t("ui.documentsInvoices.enableDigitalReceipts")}
          subtitle={t("ui.documentsInvoices.allowsCreatingNewDocuments")}
          value={!!settingsForm.digital_receipts_enabled}
          onChange={(v) => setSettingsForm((s) => ({ ...s, digital_receipts_enabled: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={t("ui.documentsInvoices.operationalMode")}
          subtitle={
            t("ui.documentsInvoices.locksPdfsAndBlocksVoidingReceipts")
          }
          value={!!settingsForm.is_operational}
          onChange={(v) => setSettingsForm((s) => ({ ...s, is_operational: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={t("ui.documentsInvoices.requestElectronicReceiptConsent")}
          subtitle={
            t("ui.documentsInvoices.existingAthletesAndManagersArePrompted")
          }
          value={!!settingsForm.request_consent_from_existing_users}
          onChange={(v) => setSettingsForm((s) => ({ ...s, request_consent_from_existing_users: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={t("ui.documentsInvoices.requestAddressFromExistingUsers")}
          subtitle={
            t("ui.documentsInvoices.existingAthletesAndManagersArePrompted2")
          }
          value={!!settingsForm.request_address_from_existing_users}
          onChange={(v) => setSettingsForm((s) => ({ ...s, request_address_from_existing_users: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={t("ui.documentsInvoices.staffCanCancel")}
          value={!!settingsForm.staff_can_cancel_documents}
          onChange={(v) => setSettingsForm((s) => ({ ...s, staff_can_cancel_documents: v }))}
        />
      </SectionCard>

      <SectionCard label={t("ui.documentsInvoices.vatNumbering")}>
        <ToggleRow
          isRTL={isRTL}
          title={t("ui.documentsInvoices.includeVatOnReceipts")}
          subtitle={
            t("ui.documentsInvoices.whenOffReceiptsAndReportsShow")
          }
          value={!!settingsForm.vat_enabled}
          onChange={(v) => setSettingsForm((s) => ({ ...s, vat_enabled: v }))}
        />
        <View style={styles.cardDivider} />
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{t("ui.documentsInvoices.vat")}</Text>
        <TextInput
          value={String(Math.round((settingsForm.vat_rate ?? 0.18) * 10000) / 100)}
          onChangeText={(v) => {
            const n = parseMoney(v);
            if (n != null) setSettingsForm((s) => ({ ...s, vat_rate: n / 100 }));
          }}
          editable={!!settingsForm.vat_enabled}
          keyboardType="decimal-pad"
          style={[styles.input, isRTL && styles.rtlInput, !settingsForm.vat_enabled && styles.inputDisabled]}
        />
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{t("ui.documentsInvoices.documentPrefix")}</Text>
        <TextInput
          value={String(settingsForm.document_prefix ?? "")}
          onChangeText={(v) => setSettingsForm((s) => ({ ...s, document_prefix: v }))}
          style={[styles.input, isRTL && styles.rtlInput]}
          autoCapitalize="characters"
        />
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>
          {t("ui.documentsInvoices.nextDocumentNumber")}
        </Text>
        {settingsForm.is_operational ? (
          <Text style={[styles.filterHint, isRTL && styles.rtl]}>
            {language === "he"
              ? `${settingsForm.next_document_number ?? "—"} (ניתן לשינוי רק לפני מעבר למצב תפעולי)`
              : `${settingsForm.next_document_number ?? "—"} (only changeable before going operational)`}
          </Text>
        ) : (
          <TextInput
            value={String(settingsForm.next_document_number ?? "")}
            onChangeText={(v) => {
              const n = Number.parseInt(v, 10);
              setSettingsForm((s) => ({ ...s, next_document_number: Number.isFinite(n) ? n : undefined }));
            }}
            keyboardType="number-pad"
            style={[styles.input, isRTL && styles.rtlInput]}
          />
        )}
      </SectionCard>

      <SectionCard label={t("ui.documentsInvoices.businessDetails")}>
        {(
          [
            ["business_name", t("ui.documentsInvoices.businessName")],
            ["business_id", t("ui.documentsInvoices.businessId")],
            ["address", t("ui.documentsInvoices.address")],
            ["phone", t("ui.documentsInvoices.phone")],
            ["email", t("ui.documentsInvoices.email")],
            ["accountant_email", t("ui.documentsInvoices.accountantEmail")],
          ] as const
        ).map(([key, label]) => (
          <View key={key} style={styles.fieldBlock}>
            <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{label}</Text>
            <TextInput
              value={String(settingsForm[key] ?? "")}
              onChangeText={(v) => setSettingsForm((s) => ({ ...s, [key]: v }))}
              style={[styles.input, isRTL && styles.rtlInput]}
              keyboardType={key === "email" || key === "accountant_email" ? "email-address" : key === "phone" ? "phone-pad" : "default"}
            />
          </View>
        ))}
      </SectionCard>

      <SectionCard label={t("ui.documentsInvoices.electronicReceiptConsent")}>
        <Text style={[styles.fieldHint, isRTL && styles.rtl]}>
          {t("ui.documentsInvoices.shownWhenRequestConsentFromExisting")}
        </Text>
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{t("ui.documentsInvoices.title")}</Text>
        <TextInput value={consentTitle} onChangeText={setConsentTitle} style={[styles.input, isRTL && styles.rtlInput]} />
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{t("ui.documentsInvoices.body")}</Text>
        <TextInput
          value={consentBody}
          onChangeText={setConsentBody}
          multiline
          style={[styles.input, styles.textArea, isRTL && styles.rtlInput]}
        />
        <PrimaryButton
          label={t("ui.documentsInvoices.publishNewVersion")}
          onPress={() =>
            void publishLegalDocument("electronic_receipts", consentTitle, consentBody).then((v) =>
              showToast({
                message: language === "he" ? `גרסה ${v} פורסמה` : `Version ${v} published`,
                variant: "success",
              })
            )
          }
        />
      </SectionCard>

      <PrimaryButton
        label={t("ui.documentsInvoices.saveSettings")}
        onPress={() => void saveSettings()}
        loading={savingSettings}
        loadingLabel={t("common.loading")}
      />
    </ScrollView>
  );

  const docsFiltersActive = payeeFilter.type !== "all";
  const docsDateRangeLabel = `${formatISODateFull(dateStart, language)} – ${formatISODateFull(dateEnd, language)}`;
  const docsFiltersSummary = `${docsFiltersActive ? payeeFilter.label : t("accountPayments.allPayees")} · ${docsDateRangeLabel}`;

  const documentsListHeader = (
    <>
      {pageHeader}
      <View style={styles.payeeFilterCard}>
        <Pressable
          onPress={() => setFiltersOpen((v) => !v)}
          style={({ pressed }) => [styles.filterToggle, pressed && { opacity: 0.9 }]}
        >
          <View style={styles.filterToggleCopy}>
            <Text style={[styles.filterToggleLabel, isRTL && styles.rtl]}>{t("accountPayments.filters")}</Text>
            <Text style={[styles.filterSummary, isRTL && styles.rtl]} numberOfLines={1}>
              {docsFiltersSummary}
            </Text>
          </View>
          <Text style={styles.chevron}>{filtersOpen ? "︿" : "﹀"}</Text>
        </Pressable>
        {filtersOpen ? (
          <View style={styles.filterBody}>
            <Text style={[styles.sectionLabel, isRTL && styles.rtl]}>{t("accountPayments.payeeFilter")}</Text>
            <Pressable
              style={({ pressed }) => [styles.pickerTouch, pressed && { opacity: 0.92 }]}
              onPress={() => setPayeePickerOpen(true)}
            >
              <Text
                style={payeeFilter.type === "all" ? styles.pickerPlaceholder : styles.pickerText}
                numberOfLines={1}
              >
                {payeeFilter.type === "all" ? t("accountPayments.allPayees") : payeeFilter.label}
              </Text>
            </Pressable>
            {payeeFilter.type !== "all" ? (
              <Pressable style={({ pressed }) => [styles.clearLink, pressed && { opacity: 0.85 }]} onPress={() => setPayeeFilter({ type: "all" })}>
                <Text style={styles.clearLinkText}>{t("common.clearSelection")}</Text>
              </Pressable>
            ) : null}

            <Text style={[styles.sectionLabel, styles.sectionSpaced, isRTL && styles.rtl]}>
              {t("ui.documentsInvoices.dateRange")}
            </Text>
            <CollapsibleDateRangeCard
              start={dateStart}
              end={dateEnd}
              onChange={({ start, end }) => { setDateStart(start); setDateEnd(end); }}
              label={t("ui.documentsInvoices.dateRange")}
            />
          </View>
        ) : null}
      </View>
      <View style={[styles.sortRow, rowFlipFor(isRTL) && styles.sortRowRtl]}>
        <SortToggleButton
          value={docsSortOrder}
          onChange={setDocsSortOrder}
          ascLabel={t("ui.documentsInvoices.oldestFirst")}
          descLabel={t("ui.documentsInvoices.newestFirst")}
        />
      </View>
    </>
  );

  const reportsContent = (
    <ScrollView contentContainerStyle={[styles.scrollContent, screenContent]} keyboardShouldPersistTaps="handled">
      {pageHeader}
      <CollapsibleDateRangeCard
        start={dateStart}
        end={dateEnd}
        onChange={({ start, end }) => { setDateStart(start); setDateEnd(end); }}
        label={t("ui.documentsInvoices.dateRange")}
      />
      <View style={[styles.summaryRow, rowFlipFor(isRTL) && styles.summaryRowRtl]}>
        <View style={styles.summaryStat}>
          <Text style={styles.summaryValue}>{Math.round(reportCountDisplay)}</Text>
          <Text style={styles.summaryLabel}>{t("ui.documentsInvoices.documents")}</Text>
        </View>
        <View style={styles.summaryDivider} />
        <View style={styles.summaryStat}>
          <Text style={styles.summaryValue}>{formatIls(reportGrossDisplay)}</Text>
          <Text style={styles.summaryLabel}>{t("ui.documentsInvoices.grossTotal")}</Text>
        </View>
        <View style={styles.summaryDivider} />
        <View style={styles.summaryStat}>
          {settings?.vat_enabled ? (
            <>
              <Text style={styles.summaryValue}>{formatIls(reportVatDisplay)}</Text>
              <Text style={styles.summaryLabel}>{t("ui.documentsInvoices.vat2")}</Text>
            </>
          ) : (
            <>
              <Text style={styles.summaryValue}>{`ע.פ. ${settings?.business_id ?? ""}`}</Text>
              <Text style={styles.summaryLabel}>{t("ui.documentsInvoices.exemptDealer")}</Text>
            </>
          )}
        </View>
      </View>
      <PrimaryButton label={t("ui.documentsInvoices.exportCsv")} onPress={exportCsv} />
      <PrimaryButton
        label={t("ui.documentsInvoices.sendAllToAccountant")}
        onPress={() => void sendAllToAccountant()}
        loading={bulkAccountantBusy}
        loadingLabel={t("common.loading")}
      />
      <PrimaryButton
        label={t("ui.documentsInvoices.generateMonthlySummaryPdf")}
        onPress={() => void generateMonthlySummary()}
        loading={monthlySummaryBusy}
        loadingLabel={t("common.loading")}
        disabled={!isFullMonthRange}
      />
      {!isFullMonthRange ? (
        <Text style={[styles.filterHint, isRTL && styles.rtl]}>
          {t("ui.documentsInvoices.switchTheDateRangeToMonth")}
        </Text>
      ) : null}
      {filteredMonthlySummaries.length > 0 ? (
        <View style={styles.card}>
          <Text style={[styles.cardLabel, isRTL && styles.rtl]}>
            {t("ui.documentsInvoices.generatedMonthlySummaries")}
          </Text>
          {filteredMonthlySummaries.map((row) => {
            const rowDeleting = deletingSummaryId === row.id;
            return (
              <View key={row.id} style={[styles.summaryHistoryRow, rowFlipFor(isRTL) && styles.docHeadRtl]}>
                <Pressable onPress={() => void viewMonthlySummary(row)} style={{ flex: 1 }}>
                  <Text style={[styles.summaryHistoryPeriod, isRTL && styles.rtl]}>
                    {new Date(row.period_start).toLocaleDateString(t("ui.documentsInvoices.enGb"), {
                      timeZone: "Asia/Jerusalem",
                      day: "2-digit",
                      month: "short",
                      year: "numeric",
                    })}
                    {" – "}
                    {new Date(row.period_end).toLocaleDateString(t("ui.documentsInvoices.enGb"), {
                      timeZone: "Asia/Jerusalem",
                      day: "2-digit",
                      month: "short",
                      year: "numeric",
                    })}
                  </Text>
                  <Text style={[styles.summaryHistoryMeta, isRTL && styles.rtl]}>
                    {language === "he"
                      ? `${row.active_count} קבלות · ${formatIls(row.gross_total)}`
                      : `${row.active_count} receipts · ${formatIls(row.gross_total)}`}
                  </Text>
                </Pressable>
                <Pressable onPress={() => void viewMonthlySummary(row)} style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}>
                  <Text style={styles.summaryHistoryView}>{t("ui.documentsInvoices.view")}</Text>
                </Pressable>
                <Pressable
                  disabled={rowDeleting}
                  onPress={() => confirmDeleteMonthlySummary(row)}
                  style={({ pressed }) => [
                    styles.actionItem,
                    styles.actionItemDanger,
                    rowDeleting && styles.actionItemBusy,
                    pressed && !rowDeleting && styles.actionItemPressed,
                  ]}
                >
                  {rowDeleting ? (
                    <ActivityIndicator size="small" color={theme.colors.error} />
                  ) : (
                    <Text style={[styles.actionTextDanger, isRTL && styles.rtl]}>
                      {t("ui.documentsInvoices.delete")}
                    </Text>
                  )}
                </Pressable>
              </View>
            );
          })}
        </View>
      ) : null}
    </ScrollView>
  );

  return (
    <View style={styles.screen}>
      <Stack.Screen options={{ title: t("menu.documentsInvoices") }} />
      <ManagerMoneyHubTabs />

      <CrossfadeSwap
        loading={loading}
        style={styles.tabPanel}
        skeleton={
          <View style={styles.loaderSkeletonList}>
            <ListRowSkeleton />
            <ListRowSkeleton />
            <ListRowSkeleton />
          </View>
        }
      >
      {section === "pending" ? (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          <PendingReceiptsPanel
            enabled={!!settings?.digital_receipts_enabled}
            header={pageHeader}
            onCreated={() => load()}
            testingMode={!settings?.is_operational}
          />
        </FadeSlideIn>
      ) : section === "reports" && isManager ? (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          {reportsContent}
        </FadeSlideIn>
      ) : section === "settings" && isManager ? (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          {settingsContent}
        </FadeSlideIn>
      ) : (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          <FlatList
            style={styles.list}
            data={sortedDocuments}
            keyExtractor={(x) => x.id}
            renderItem={renderDocumentItem}
            ListHeaderComponent={documentsListHeader}
            ListEmptyComponent={
              <View style={styles.emptyBox}>
                <Text style={[styles.emptyTitle, isRTL && styles.rtl]}>
                  {payeeFilter.type !== "all"
                    ? t("ui.documentsInvoices.noDocumentsForThisName")
                    : t("ui.documentsInvoices.noDocumentsInRange")}
                </Text>
                <Text style={[styles.emptyHint, isRTL && styles.rtl]}>
                  {payeeFilter.type !== "all"
                    ? t("ui.documentsInvoices.tryAnotherNameOrClearThe")
                    : t("ui.documentsInvoices.tryAWiderDateRangeOr")}
                </Text>
              </View>
            }
            refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor={theme.colors.cta} />}
            contentContainerStyle={[styles.listContent, screenContent]}
          />
        </FadeSlideIn>
      )}
      </CrossfadeSwap>

      <EditCustomerEmailModal
        visible={editEmailDoc != null}
        documentId={editEmailDoc?.id ?? null}
        customerName={editEmailDoc?.customer_name ?? ""}
        initialEmail={editEmailDoc?.customer_email ?? null}
        onClose={() => setEditEmailDoc(null)}
        onSaved={async () => {
          await load();
          showToast({ message: t("ui.documentsInvoices.emailUpdated"), variant: "success" });
        }}
      />

      <PayeePickerModal
        visible={payeePickerOpen}
        onClose={() => setPayeePickerOpen(false)}
        onSelect={(row: PayeePickerRow) => setPayeeFilter({ type: row.kind, id: row.id, label: row.full_name })}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.backgroundAlt },
  tabPanel: { flex: 1 },
  list: { flex: 1 },
  listContent: { paddingHorizontal: theme.spacing.md, paddingBottom: theme.spacing.xl, gap: theme.spacing.sm },
  scrollContent: { paddingHorizontal: theme.spacing.md, paddingBottom: theme.spacing.xl, gap: theme.spacing.md },
  loaderSkeletonList: { padding: theme.spacing.md, gap: theme.spacing.sm },
  payeeFilterCard: {
    padding: theme.spacing.md,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    marginBottom: theme.spacing.sm,
  },
  filterToggle: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: theme.spacing.sm },
  filterToggleCopy: { flex: 1 },
  filterToggleLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  filterSummary: { fontSize: 13, fontWeight: "700", color: theme.colors.text, marginTop: 2 },
  chevron: { fontSize: 14, fontWeight: "800", color: theme.colors.textSoft },
  filterBody: {
    marginTop: theme.spacing.md,
    paddingTop: theme.spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.35,
    marginBottom: theme.spacing.sm,
  },
  sectionSpaced: { marginTop: theme.spacing.md },
  pickerTouch: {
    paddingVertical: 12,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
    minHeight: 48,
    justifyContent: "center",
  },
  pickerText: { fontSize: 15, fontWeight: "700", color: theme.colors.text },
  pickerPlaceholder: { fontSize: 15, fontWeight: "600", color: theme.colors.textSoft },
  clearLink: { alignSelf: "flex-start", marginTop: theme.spacing.sm, paddingVertical: 4 },
  clearLinkText: { fontSize: 13, fontWeight: "800", color: theme.colors.textMuted },
  sortRow: { flexDirection: "row", marginTop: theme.spacing.xs, marginBottom: theme.spacing.xs },
  sortRowRtl: { flexDirection: "row-reverse" },
  bulkRegenProgressRow: { flexDirection: "row", alignItems: "center", gap: theme.spacing.sm, paddingVertical: theme.spacing.sm },
  bulkRegenProgressText: { fontSize: 14, fontWeight: "700", color: theme.colors.text },
  headerBlock: { marginTop: -theme.spacing.sm, gap: theme.spacing.xs, marginBottom: theme.spacing.xs },
  tabBarRow: { flexDirection: "row", alignItems: "flex-end" },
  tabBarFill: {},
  settingsGear: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: theme.spacing.sm,
  },
  settingsGearIcon: { fontSize: 18, fontWeight: "600", color: theme.colors.textMuted },
  settingsGearIconActive: { color: theme.colors.text, fontWeight: "800" },
  testingBanner: {
    marginTop: theme.spacing.xs,
    backgroundColor: theme.colors.warningBg,
    borderWidth: 1,
    borderColor: theme.colors.warningBorder,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.md,
  },
  testingText: { color: theme.colors.warning, fontWeight: "700", fontSize: 13, textAlign: "center" },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  cardLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  cardDivider: { height: StyleSheet.hairlineWidth, backgroundColor: theme.colors.borderMuted, marginVertical: 4 },
  toggleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: theme.spacing.md, paddingVertical: 4 },
  toggleRowRtl: { flexDirection: "row-reverse" },
  toggleCopy: { flex: 1 },
  toggleTitle: { fontSize: 15, fontWeight: "700", color: theme.colors.text },
  toggleSub: { marginTop: 2, fontSize: 12, fontWeight: "500", color: theme.colors.textSoft, lineHeight: 17 },
  fieldBlock: { gap: 6 },
  fieldHint: { fontSize: 13, fontWeight: "500", color: theme.colors.textSoft, lineHeight: 19, marginBottom: theme.spacing.sm },
  fieldLabel: { fontSize: 13, fontWeight: "700", color: theme.colors.textMuted },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.radius.md,
    paddingVertical: 12,
    paddingHorizontal: theme.spacing.md,
    color: theme.colors.text,
    backgroundColor: theme.colors.surfaceElevated,
    fontSize: 15,
    fontWeight: "600",
  },
  inputDisabled: { opacity: 0.5 },
  textArea: { minHeight: 140, textAlignVertical: "top" },
  rtlInput: { textAlign: "right", writingDirection: "rtl" },
  createBtn: { marginBottom: theme.spacing.sm },
  disabledBox: {
    padding: theme.spacing.md,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    marginBottom: theme.spacing.sm,
  },
  disabledText: { color: theme.colors.textMuted, fontSize: 14, fontWeight: "600", lineHeight: 20 },
  docCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  docHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: theme.spacing.md },
  docHeadRtl: { flexDirection: "row-reverse" },
  docHeadMain: { flex: 1, minWidth: 0 },
  docTitleRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  docTitleRowRtl: { flexDirection: "row-reverse" },
  typeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  typeBadgeText: { fontSize: 11, fontWeight: "800", color: theme.colors.textMuted },
  docHeadEnd: { alignItems: "flex-end", gap: 6 },
  docNumber: { ...theme.typography.title, color: theme.colors.text, letterSpacing: 0.2 },
  docCustomer: { marginTop: 2, ...theme.typography.secondary, color: theme.colors.textMuted },
  docAmount: { ...theme.typography.headline, color: theme.colors.text },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: theme.radius.full },
  badgeActive: { backgroundColor: theme.colors.successBg },
  badgeCancelled: { backgroundColor: theme.colors.errorBg },
  badgePending: { backgroundColor: theme.colors.warningBg },
  badgeText: { fontSize: 11, fontWeight: "800", color: theme.colors.text, letterSpacing: 0.2 },
  docMeta: { marginTop: theme.spacing.sm, fontSize: 13, fontWeight: "500", color: theme.colors.textSoft, lineHeight: 18 },
  warnBox: {
    marginTop: theme.spacing.sm,
    padding: theme.spacing.sm,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.warningBg,
    borderWidth: 1,
    borderColor: theme.colors.warningBorder,
  },
  warnText: { ...theme.typography.label, color: theme.colors.warning },
  warnAction: { marginTop: 6, alignSelf: "flex-start" },
  warnActionText: { fontSize: 12, fontWeight: "800", color: theme.colors.cta },
  filterCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
  },
  filterHint: { fontSize: 12, fontWeight: "600", color: theme.colors.textSoft },
  actionBar: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", marginTop: theme.spacing.md, gap: 2 },
  actionBarRtl: { flexDirection: "row-reverse" },
  actionItem: { paddingVertical: 8, paddingHorizontal: 10, borderRadius: theme.radius.md },
  actionItemPressed: { backgroundColor: theme.colors.surfaceElevated },
  actionItemBusy: { opacity: 0.65 },
  actionItemDanger: {},
  actionSep: { width: StyleSheet.hairlineWidth, height: 16, backgroundColor: theme.colors.borderMuted, marginHorizontal: 2 },
  actionText: { fontSize: 13, fontWeight: "800", color: theme.colors.text },
  actionTextDanger: { fontSize: 13, fontWeight: "800", color: theme.colors.error },
  summaryHistoryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.sm,
    paddingVertical: 8,
    borderRadius: theme.radius.md,
  },
  summaryHistoryPeriod: { fontSize: 14, fontWeight: "700", color: theme.colors.text },
  summaryHistoryMeta: { fontSize: 12, fontWeight: "600", color: theme.colors.textSoft, marginTop: 2 },
  summaryHistoryView: { fontSize: 13, fontWeight: "800", color: theme.colors.primary },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  summaryRowRtl: { flexDirection: "row-reverse" },
  summaryStat: { flex: 1, alignItems: "center" },
  summaryDivider: { width: StyleSheet.hairlineWidth, alignSelf: "stretch", backgroundColor: theme.colors.borderMuted },
  summaryValue: { fontSize: 17, fontWeight: "800", color: theme.colors.text },
  summaryLabel: { marginTop: 2, fontSize: 11, fontWeight: "700", color: theme.colors.textSoft, textTransform: "uppercase", letterSpacing: 0.25 },
  reportRow: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: 4,
  },
  reportHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  reportHeadRtl: { flexDirection: "row-reverse" },
  reportNumber: { fontSize: 15, fontWeight: "800", color: theme.colors.text },
  reportAmount: { fontSize: 16, fontWeight: "800", color: theme.colors.text },
  reportMeta: { fontSize: 13, fontWeight: "500", color: theme.colors.textSoft },
  emptyBox: {
    paddingVertical: theme.spacing.xl,
    paddingHorizontal: theme.spacing.lg,
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  emptyTitle: { ...theme.typography.title, color: theme.colors.text },
  emptyHint: { fontSize: 14, fontWeight: "500", color: theme.colors.textMuted, textAlign: "center", lineHeight: 20 },
  rtl: { textAlign: "right", writingDirection: "rtl" },
  /** User content keeps its own writing direction (so Latin names truncate at their end); only the alignment follows the UI. */
  userContentRtl: { textAlign: "right" },
});
