import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import {
  ActivityIndicator,
  FlatList,
  Platform,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import * as Linking from "expo-linking";
import { Stack } from "expo-router";
import { theme } from "../theme";
import { useI18n } from "../context/I18nContext";
import { useAuth } from "../context/AuthContext";
import { useAppAlert } from "../context/AppAlertContext";
import { useToast } from "../context/ToastContext";
import { ManagerMoneyHubTabs, ManagerStatePillTabBar } from "../components/ManagerOverviewTabs";
import { ListRowSkeleton } from "../components/ListRowSkeleton";
import { AppSwitch } from "../components/AppSwitch";
import { FadeSlideIn } from "../components/FadeSlideIn";
import { CrossfadeSwap } from "../components/CrossfadeSwap";
import { useCountUp } from "../hooks/useCountUp";
import { ReportDateRangeControls } from "../components/ReportDateRangeControls";
import { PrimaryButton } from "../components/PrimaryButton";
import { PendingReceiptsPanel } from "../components/PendingReceiptsPanel";
import { GoLiveReadinessSection } from "../components/GoLiveReadinessSection";
import { ReceiptRequirementsTestingSection } from "../components/ReceiptRequirementsTestingSection";
import { EditCustomerEmailModal } from "../components/EditCustomerEmailModal";
import { isFullCalendarMonthRangeISO, lastNDaysRangeISO } from "../lib/isoDate";
import {
  autoGenerateDocumentPdfIfReady,
  cancelDocument,
  deleteDocumentFull,
  deleteMonthlySummaryReport,
  fetchDocumentReport,
  fetchMonthlySummaries,
  fetchReceiptSettings,
  getDocumentPdfSignedUrl,
  getMonthlySummaryPdfSignedUrl,
  invokeGenerateDocumentPdf,
  invokeGenerateMonthlySummaryPdf,
  invokeSendDocumentEmail,
  invokeSendDocumentsEmail,
  invokeSendMonthlySummaryEmail,
  listDocuments,
  logDocumentEvent,
  prepareDocumentPdfRegeneration,
  publishLegalDocument,
  setDocumentPaymentMethod,
  updateReceiptSettings,
  vatPercentLabel,
  formatIls,
  type DocumentCustomerType,
  type DocumentRow,
  type DocumentReportRow,
  type MonthlySummaryRow,
  type ReceiptSettings,
} from "../lib/documents";
import { DOCUMENT_PAYMENT_METHOD_KEYS, documentPaymentMethodLabel } from "../lib/documentPaymentMethod";
import { documentServiceTypeLabel } from "../lib/documentServiceTypes";
import { buildCsv, downloadCsvWeb } from "../lib/csvExport";
import { supabase } from "../lib/supabase";

type HubSection = "pending" | "documents" | "reports" | "settings";

function customerTypeBadgeLabel(type: DocumentCustomerType | null | undefined, language: "he" | "en"): string | null {
  if (!type || type === "regular") return null;
  if (type === "manual") return language === "he" ? "מהיר" : "Quick-add";
  return language === "he" ? "משפחה" : "Family";
}

function matchesCustomerName(doc: DocumentRow, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  return doc.customer_name.toLowerCase().includes(q);
}

function parseMoney(raw: string): number | null {
  const n = Number.parseFloat(raw.replace(",", ".").trim());
  return Number.isFinite(n) ? n : null;
}

function statusBadgeStyle(status: DocumentRow["status"]) {
  if (status === "ACTIVE") return styles.badgeActive;
  if (status === "CANCELLED") return styles.badgeCancelled;
  return styles.badgePending;
}

function statusLabel(status: DocumentRow["status"], language: "he" | "en") {
  if (status === "ACTIVE") return language === "he" ? "פעיל" : "Active";
  if (status === "CANCELLED") return language === "he" ? "בוטל" : "Cancelled";
  return language === "he" ? "דרוש תשלום" : "Needs method";
}

function SectionCard({ label, children }: { label: string; children: ReactNode }) {
  return (
    <View style={styles.card}>
      <Text style={styles.cardLabel}>{label}</Text>
      {children}
    </View>
  );
}

function ToggleRow({
  title,
  subtitle,
  value,
  onChange,
  isRTL,
}: {
  title: string;
  subtitle?: string;
  value: boolean;
  onChange: (v: boolean) => void;
  isRTL: boolean;
}) {
  return (
    <View style={[styles.toggleRow, isRTL && styles.toggleRowRtl]}>
      <View style={styles.toggleCopy}>
        <Text style={[styles.toggleTitle, isRTL && styles.rtl]}>{title}</Text>
        {subtitle ? <Text style={[styles.toggleSub, isRTL && styles.rtl]}>{subtitle}</Text> : null}
      </View>
      <AppSwitch value={value} onValueChange={onChange} onColor={theme.colors.success} accessibilityLabel={title} />
    </View>
  );
}

function HubTabs({
  tabs,
  active,
  onChange,
}: {
  tabs: { id: HubSection; label: string }[];
  active: HubSection;
  onChange: (id: HubSection) => void;
}) {
  return (
    <ManagerStatePillTabBar
      tabs={tabs}
      active={active}
      onChange={(id) => onChange(id as HubSection)}
      density="comfortable"
    />
  );
}

export default function DocumentsInvoicesScreen() {
  const { language, t, isRTL } = useI18n();
  const { profile } = useAuth();
  const { showConfirm } = useAppAlert();
  const { showToast } = useToast();
  const isManager = profile?.role === "manager";
  const isCoach = profile?.role === "coach";
  const lang = language === "he" ? "he" : "en";

  const [section, setSection] = useState<HubSection>("pending");
  const [settings, setSettings] = useState<ReceiptSettings | null>(null);
  const [settingsForm, setSettingsForm] = useState<Partial<ReceiptSettings>>({});
  const [documents, setDocuments] = useState<DocumentRow[]>([]);
  const [reportRows, setReportRows] = useState<DocumentReportRow[]>([]);
  const [monthlySummaries, setMonthlySummaries] = useState<MonthlySummaryRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [savingSettings, setSavingSettings] = useState(false);
  const [consentTitle, setConsentTitle] = useState("");
  const [consentBody, setConsentBody] = useState("");
  const defaultRange = useMemo(() => lastNDaysRangeISO(30), []);
  const [dateStart, setDateStart] = useState(defaultRange.start);
  const [dateEnd, setDateEnd] = useState(defaultRange.end);
  const [nameFilter, setNameFilter] = useState("");
  const [pdfBusyId, setPdfBusyId] = useState<string | null>(null);
  const [accountantBusyId, setAccountantBusyId] = useState<string | null>(null);
  const [bulkAccountantBusy, setBulkAccountantBusy] = useState(false);
  const [monthlySummaryBusy, setMonthlySummaryBusy] = useState(false);
  const [deletingSummaryId, setDeletingSummaryId] = useState<string | null>(null);
  const [cancelBusyId, setCancelBusyId] = useState<string | null>(null);
  const [deleteDocBusyId, setDeleteDocBusyId] = useState<string | null>(null);
  const [editEmailDoc, setEditEmailDoc] = useState<DocumentRow | null>(null);

  const canCancelDocument = isManager || (isCoach && !!settings?.staff_can_cancel_documents);

  const filteredDocuments = useMemo(
    () => documents.filter((d) => matchesCustomerName(d, nameFilter)),
    [documents, nameFilter]
  );

  const reportTotals = useMemo(() => {
    const active = reportRows.filter((r) => r.status === "ACTIVE");
    return {
      count: reportRows.length,
      gross: active.reduce((s, r) => s + Number(r.gross_amount), 0),
      vat: active.reduce((s, r) => s + Number(r.vat_amount), 0),
    };
  }, [reportRows]);

  const isFullMonthRange = useMemo(() => isFullCalendarMonthRangeISO(dateStart, dateEnd), [dateStart, dateEnd]);

  const reportCountDisplay = useCountUp(reportTotals.count);
  const reportGrossDisplay = useCountUp(reportTotals.gross);
  const reportVatDisplay = useCountUp(reportTotals.vat);

  /** Only summaries whose period overlaps the currently selected date range. */
  const filteredMonthlySummaries = useMemo(() => {
    const filterStart = new Date(`${dateStart}T00:00:00.000Z`).getTime();
    const filterEnd = new Date(`${dateEnd}T23:59:59.999Z`).getTime();
    return monthlySummaries.filter((row) => {
      const summaryStart = new Date(row.period_start).getTime();
      const summaryEnd = new Date(row.period_end).getTime();
      return summaryStart <= filterEnd && summaryEnd >= filterStart;
    });
  }, [monthlySummaries, dateStart, dateEnd]);

  const load = useCallback(async () => {
    try {
      const s = await fetchReceiptSettings();
      setSettings(s);
      if (s) {
        setSettingsForm({
          business_id: s.business_id,
          business_name: s.business_name,
          address: s.address,
          phone: s.phone,
          email: s.email,
          accountant_email: s.accountant_email ?? "",
          digital_receipts_enabled: s.digital_receipts_enabled,
          vat_rate: s.vat_rate,
          document_prefix: s.document_prefix,
          staff_can_cancel_documents: s.staff_can_cancel_documents,
          is_operational: s.is_operational,
          request_address_from_existing_users: s.request_address_from_existing_users ?? false,
          request_consent_from_existing_users: s.request_consent_from_existing_users ?? false,
          next_document_number: s.next_document_number,
        });
      }
      const startIso = `${dateStart}T00:00:00.000Z`;
      const endIso = `${dateEnd}T23:59:59.999Z`;
      try {
        const { rows } = await listDocuments({
          date_start: startIso,
          date_end: endIso,
        });
        setDocuments(rows);
      } catch (e) {
        setDocuments([]);
        showToast({
          message: language === "he" ? "שגיאה בטעינת מסמכים" : "Failed to load documents",
          detail: e instanceof Error ? e.message : String(e),
          variant: "error",
        });
      }
      if (isManager) {
        try {
          setReportRows(await fetchDocumentReport(startIso, endIso));
        } catch {
          setReportRows([]);
        }
        try {
          setMonthlySummaries(await fetchMonthlySummaries());
        } catch {
          setMonthlySummaries([]);
        }
      }
      const { data: legal } = await supabase.rpc("get_current_legal_document", {
        p_consent_type: "electronic_receipts",
      });
      const legalRow = legal as { ok?: boolean; document?: { title: string; body_text: string } };
      if (legalRow?.ok && legalRow.document) {
        setConsentTitle(legalRow.document.title);
        setConsentBody(legalRow.document.body_text);
      }
    } catch (e) {
      showToast({
        message: t("common.error"),
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [dateStart, dateEnd, isManager, language, showToast, t]);

  useEffect(() => {
    void load();
  }, [load]);

  async function saveSettings() {
    if (!isManager) return;
    setSavingSettings(true);
    try {
      const vatPct = parseMoney(String((settingsForm.vat_rate ?? 0.18) * 100));
      const updated = await updateReceiptSettings({
        business_id: settingsForm.business_id,
        business_name: settingsForm.business_name,
        address: settingsForm.address,
        phone: settingsForm.phone,
        email: settingsForm.email,
        accountant_email: settingsForm.accountant_email,
        digital_receipts_enabled: settingsForm.digital_receipts_enabled,
        vat_rate: vatPct != null ? vatPct / 100 : undefined,
        document_prefix: settingsForm.document_prefix,
        staff_can_cancel_documents: settingsForm.staff_can_cancel_documents,
        is_operational: settingsForm.is_operational,
        request_address_from_existing_users: settingsForm.request_address_from_existing_users,
        request_consent_from_existing_users: settingsForm.request_consent_from_existing_users,
        next_document_number: settingsForm.is_operational ? undefined : settingsForm.next_document_number,
      });
      setSettings(updated);
      showToast({ message: language === "he" ? "ההגדרות נשמרו" : "Settings saved", variant: "success" });
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    } finally {
      setSavingSettings(false);
    }
  }

  async function openPdf(doc: DocumentRow) {
    if (!doc.pdf_url) {
      showToast({ message: language === "he" ? "PDF לא מוכן" : "PDF not ready", variant: "error" });
      return;
    }
    try {
      const url = await getDocumentPdfSignedUrl(doc.pdf_url, doc.signature_hash ?? doc.id);
      await logDocumentEvent(doc.id, "document_viewed");
      if (Platform.OS === "web") window.open(url, "_blank", "noopener,noreferrer");
      else await Linking.openURL(url);
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    }
  }

  async function generatePdf(doc: DocumentRow) {
    if (pdfBusyId) return;
    setPdfBusyId(doc.id);
    const hadPdf = !!doc.pdf_url;
    try {
      if (doc.pdf_url) {
        await prepareDocumentPdfRegeneration(doc.id);
        await invokeGenerateDocumentPdf(doc.id, true);
      } else {
        // A cancelled receipt may still have its pre-cancellation PDF sitting in storage
        // (the auto-reissue on cancel can fail); always overwrite so retrying here can't
        // collide with that stale file.
        await invokeGenerateDocumentPdf(doc.id, doc.status === "CANCELLED" || !settings?.is_operational);
      }
      await load();
      showToast({
        message: hadPdf
          ? language === "he"
            ? "PDF נוצר מחדש"
            : "PDF regenerated"
          : language === "he"
            ? "PDF נוצר"
            : "PDF generated",
        variant: "success",
      });
    } catch (e) {
      showToast({
        message: language === "he" ? "יצירת PDF נכשלה" : "PDF generation failed",
        detail: e instanceof Error ? e.message : String(e),
        variant: "error",
      });
    } finally {
      setPdfBusyId(null);
    }
  }

  async function regeneratePdf(doc: DocumentRow) {
    await generatePdf(doc);
  }

  async function sendToAccountant(doc: DocumentRow) {
    const accountant = settings?.accountant_email?.trim();
    if (!accountant) {
      showToast({
        message: language === "he" ? "הגדירו אימייל רו״ח בהגדרות" : "Set accountant email in Settings",
        variant: "error",
      });
      return;
    }
    if (!doc.pdf_url) {
      showToast({ message: language === "he" ? "PDF לא מוכן" : "PDF not ready", variant: "error" });
      return;
    }
    setAccountantBusyId(doc.id);
    try {
      await invokeSendDocumentEmail(doc.id, accountant);
      showToast({
        message: language === "he" ? "נשלח לרו״ח" : "Sent to accountant",
        variant: "success",
      });
      void load();
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    } finally {
      setAccountantBusyId(null);
    }
  }

  async function cancelReceipt(doc: DocumentRow) {
    if (cancelBusyId) return;
    setCancelBusyId(doc.id);
    try {
      const { needsPdfReissue } = await cancelDocument(doc.id, "בוטל על ידי מנהל");
      let pdfReissueFailed = false;
      if (needsPdfReissue) {
        try {
          await invokeGenerateDocumentPdf(doc.id, true);
        } catch {
          pdfReissueFailed = true;
        }
      }
      await load();
      if (pdfReissueFailed) {
        showToast({
          message: language === "he" ? "הקבלה בוטלה, אך יצירת ה-PDF המבוטל נכשלה" : "Receipt cancelled, but reissuing the cancelled PDF failed",
          detail: language === "he" ? "אפשר לנסות שוב מכפתור «PDF מחדש»." : "You can retry from the Regen button.",
          variant: "info",
        });
      } else {
        showToast({
          message: language === "he" ? "הקבלה בוטלה" : "Receipt cancelled",
          variant: "success",
        });
      }
    } catch (e) {
      showToast({
        message: language === "he" ? "ביטול הקבלה נכשל" : "Failed to cancel receipt",
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setCancelBusyId(null);
    }
  }

  function confirmCancelReceipt(doc: DocumentRow) {
    showConfirm({
      title: language === "he" ? "לבטל קבלה?" : "Cancel receipt?",
      message:
        language === "he"
          ? "הקבלה תסומן כבוטלת וה-PDF יופק מחדש עם חותמת \"בוטל\". התשלום המקושר לא ייחשב כתשלום עם קבלה."
          : "The receipt will be marked cancelled and its PDF reissued with a \"Cancelled\" stamp. The linked payment will no longer count as receipted.",
      cancelLabel: t("common.cancel"),
      confirmLabel: language === "he" ? "ביטול קבלה" : "Cancel receipt",
      confirmVariant: "danger",
      onConfirm: () => void cancelReceipt(doc),
    });
  }

  async function deleteReceipt(doc: DocumentRow) {
    if (deleteDocBusyId) return;
    setDeleteDocBusyId(doc.id);
    try {
      await deleteDocumentFull(doc.id);
      await load();
      showToast({
        message: language === "he" ? "הקבלה נמחקה לצמיתות" : "Receipt permanently deleted",
        variant: "success",
      });
    } catch (e) {
      showToast({
        message: language === "he" ? "מחיקת הקבלה נכשלה" : "Failed to delete receipt",
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setDeleteDocBusyId(null);
    }
  }

  function confirmDeleteReceipt(doc: DocumentRow) {
    showConfirm({
      title: language === "he" ? "מחיקת קבלה?" : "Delete receipt?",
      message:
        language === "he"
          ? "הקבלה, ה-PDF וכל היסטוריית האירועים שלה יימחקו לצמיתות — לא תישמר עותק. זמין רק במצב בדיקה."
          : "The receipt, its PDF, and its event history will be permanently deleted — no copy is kept. Only available in testing mode.",
      cancelLabel: t("common.cancel"),
      confirmLabel: language === "he" ? "מחיקה לצמיתות" : "Delete permanently",
      confirmVariant: "danger",
      onConfirm: () => void deleteReceipt(doc),
    });
  }

  async function sendAllToAccountant() {
    const accountant = settings?.accountant_email?.trim();
    if (!accountant) {
      showToast({
        message: language === "he" ? "הגדירו אימייל רו״ח בהגדרות" : "Set accountant email in Settings",
        variant: "error",
      });
      return;
    }
    const eligible = filteredDocuments.filter((d) => d.status === "ACTIVE" && d.pdf_url);
    if (eligible.length === 0) {
      showToast({
        message: language === "he" ? "אין מסמכים עם PDF בטווח" : "No documents with PDF in range",
        variant: "info",
      });
      return;
    }
    setBulkAccountantBusy(true);
    try {
      const result = await invokeSendDocumentsEmail({
        documentIds: eligible.map((d) => d.id),
        mode: "accountant",
        recipientEmail: accountant,
      });
      showToast({
        message:
          language === "he"
            ? `נשלח אימייל אחד לרו״ח עם ${result.documents_sent} קבלות`
            : `1 email sent to accountant with ${result.documents_sent} receipt(s)`,
        variant: "success",
      });
      void load();
    } catch (e) {
      showToast({
        message: language === "he" ? "שליחה לרו״ח נכשלה" : "Failed to send to accountant",
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setBulkAccountantBusy(false);
    }
  }

  async function generateMonthlySummary() {
    if (monthlySummaryBusy) return;
    if (!isFullMonthRange) {
      showToast({
        message:
          language === "he"
            ? "ניתן להפיק סיכום רק לחודש קלנדרי מלא — בחרו טווח \"חודש\""
            : "Summaries can only be generated for a full calendar month — pick the Month range mode",
        variant: "error",
      });
      return;
    }
    setMonthlySummaryBusy(true);
    try {
      const { summaryId, pdfPath } = await invokeGenerateMonthlySummaryPdf(dateStart, dateEnd);
      const accountant = settings?.accountant_email?.trim();
      if (accountant) {
        await invokeSendMonthlySummaryEmail(summaryId, accountant);
      }
      const url = await getMonthlySummaryPdfSignedUrl(pdfPath);
      if (Platform.OS === "web") window.open(url, "_blank", "noopener,noreferrer");
      else await Linking.openURL(url);
      showToast({
        message: accountant
          ? language === "he"
            ? "הסיכום נוצר ונשלח לרו״ח"
            : "Summary generated and emailed to accountant"
          : language === "he"
            ? "הסיכום נוצר"
            : "Summary generated",
        variant: "success",
      });
      try {
        setMonthlySummaries(await fetchMonthlySummaries());
      } catch {
        /* list refresh is best-effort */
      }
    } catch (e) {
      showToast({
        message: language === "he" ? "יצירת הסיכום נכשלה" : "Failed to generate summary",
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setMonthlySummaryBusy(false);
    }
  }

  async function viewMonthlySummary(row: MonthlySummaryRow) {
    if (!row.pdf_url) return;
    try {
      const url = await getMonthlySummaryPdfSignedUrl(row.pdf_url);
      if (Platform.OS === "web") window.open(url, "_blank", "noopener,noreferrer");
      else await Linking.openURL(url);
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    }
  }

  function confirmDeleteMonthlySummary(row: MonthlySummaryRow) {
    showConfirm({
      title: language === "he" ? "מחיקת סיכום?" : "Delete summary?",
      message:
        language === "he"
          ? "הסיכום החודשי וה-PDF שלו יימחקו לצמיתות."
          : "The monthly summary and its PDF will be permanently deleted.",
      cancelLabel: t("common.cancel"),
      confirmLabel: language === "he" ? "מחיקה" : "Delete",
      confirmVariant: "danger",
      onConfirm: () => void deleteMonthlySummary(row),
    });
  }

  async function deleteMonthlySummary(row: MonthlySummaryRow) {
    if (deletingSummaryId) return;
    setDeletingSummaryId(row.id);
    try {
      await deleteMonthlySummaryReport(row.id, row.pdf_url);
      setMonthlySummaries((rows) => rows.filter((r) => r.id !== row.id));
      showToast({ message: language === "he" ? "הסיכום נמחק" : "Summary deleted", variant: "success" });
    } catch (e) {
      showToast({
        message: language === "he" ? "מחיקת הסיכום נכשלה" : "Failed to delete summary",
        detail: e instanceof Error ? e.message : undefined,
        variant: "error",
      });
    } finally {
      setDeletingSummaryId(null);
    }
  }

  async function sendEmail(doc: DocumentRow) {
    const email = doc.customer_email?.trim();
    if (!email) {
      showToast({ message: language === "he" ? "אין אימייל ללקוח" : "No customer email", variant: "error" });
      return;
    }
    try {
      await invokeSendDocumentEmail(doc.id, email);
      showToast({ message: language === "he" ? "נשלח" : "Sent", variant: "success" });
      void load();
    } catch (e) {
      showToast({ message: t("common.error"), detail: e instanceof Error ? e.message : undefined, variant: "error" });
    }
  }

  function exportCsv() {
    const headers = ["document_number", "date", "customer", "gross", "net", "vat", "vat_rate", "payment_method", "service_type", "status"];
    const rows = reportRows.map((r) => [
      r.document_number,
      r.created_at.slice(0, 10),
      r.customer_name,
      String(r.gross_amount),
      String(r.net_amount),
      String(r.vat_amount),
      vatPercentLabel(r.vat_rate),
      r.payment_method ?? "",
      r.service_type,
      r.status,
    ]);
    const csv = buildCsv(headers, rows);
    if (Platform.OS === "web") downloadCsvWeb(`documents-${dateStart}-${dateEnd}.csv`, csv);
    else showToast({ message: language === "he" ? "ייצוא זמין בדפדפן" : "Export available on web", variant: "info" });
  }

  const sectionTabs: { id: HubSection; label: string; managerOnly?: boolean }[] = [
    { id: "pending", label: language === "he" ? "ממתינים לקבלה" : "Pending receipts" },
    { id: "documents", label: language === "he" ? "מסמכים" : "Documents" },
    { id: "reports", label: language === "he" ? "דוחות" : "Reports", managerOnly: true },
    { id: "settings", label: language === "he" ? "הגדרות" : "Settings", managerOnly: true },
  ];

  const visibleTabs = sectionTabs.filter((x) => !x.managerOnly || isManager);

  function renderDocumentItem({ item, index }: { item: DocumentRow; index: number }) {
    const needsMethod = item.status === "NEEDS_PAYMENT_METHOD";
    const pdfBusy = pdfBusyId === item.id;
    const accountantBusy = accountantBusyId === item.id;
    const typeBadge = customerTypeBadgeLabel(item.customer_type, lang);
    const missingEmail = !item.customer_email?.trim();
    const isManual = item.customer_type === "manual" || !!item.customer_manual_participant_id;
    return (
      <FadeSlideIn delay={Math.min(index, theme.motion.maxStaggerIndex) * 30}>
      <View style={styles.docCard}>
        <View style={[styles.docHead, isRTL && styles.docHeadRtl]}>
          <View style={styles.docHeadMain}>
            <View style={[styles.docTitleRow, isRTL && styles.docTitleRowRtl]}>
              <Text style={[styles.docNumber, isRTL && styles.rtl]}>{item.document_number}</Text>
              {typeBadge ? (
                <View style={styles.typeBadge}>
                  <Text style={styles.typeBadgeText}>{typeBadge}</Text>
                </View>
              ) : null}
            </View>
            <Text style={[styles.docCustomer, isRTL && styles.rtl]} numberOfLines={1}>
              {item.customer_name}
            </Text>
          </View>
          <View style={styles.docHeadEnd}>
            <Text style={styles.docAmount}>{formatIls(item.gross_amount)}</Text>
            <View style={[styles.badge, statusBadgeStyle(item.status)]}>
              <Text style={styles.badgeText}>{statusLabel(item.status, lang)}</Text>
            </View>
          </View>
        </View>

        <Text style={[styles.docMeta, isRTL && styles.rtl]}>
          {item.created_at.slice(0, 10)}
          {" · "}
          {documentServiceTypeLabel(item.service_type, lang)}
          {item.payment_method ? ` · ${documentPaymentMethodLabel(item.payment_method, lang)}` : ""}
        </Text>

        {needsMethod ? (
          <View style={styles.warnBox}>
            <Text style={[styles.warnText, isRTL && styles.rtl]}>
              {language === "he" ? "נדרש לבחור אמצעי תשלום למסמך" : "Select a payment method for this document"}
            </Text>
          </View>
        ) : missingEmail ? (
          <View style={styles.warnBox}>
            <Text style={[styles.warnText, isRTL && styles.rtl]}>
              {isManual
                ? language === "he"
                  ? "אין אימייל — הוסיפו ידנית או דלגו על שליחה"
                  : "No email — add manually or skip send"
                : language === "he"
                  ? "אין אימייל ללקוח — עדכנו לפני שליחה"
                  : "No customer email — update before send"}
            </Text>
            {isManager ? (
              <Pressable onPress={() => setEditEmailDoc(item)} style={styles.warnAction}>
                <Text style={styles.warnActionText}>{language === "he" ? "עריכת אימייל" : "Edit email"}</Text>
              </Pressable>
            ) : null}
          </View>
        ) : !item.pdf_url && (item.status === "ACTIVE" || item.status === "CANCELLED") ? (
          <View style={styles.warnBox}>
            <Text style={[styles.warnText, isRTL && styles.rtl]}>
              {language === "he" ? "PDF לא נוצר — לחצו «צור PDF»" : "PDF missing — tap Generate PDF"}
            </Text>
          </View>
        ) : null}

        <View style={[styles.actionBar, isRTL && styles.actionBarRtl]}>
          {!needsMethod && item.pdf_url ? (
            <Pressable onPress={() => void openPdf(item)} style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}>
              <Text style={[styles.actionText, isRTL && styles.rtl]}>{language === "he" ? "צפייה" : "View"}</Text>
            </Pressable>
          ) : null}
          {!needsMethod && !item.pdf_url && (item.status === "ACTIVE" || item.status === "CANCELLED") ? (
            <Pressable
              disabled={pdfBusy}
              onPress={() => void generatePdf(item)}
              style={({ pressed }) => [
                styles.actionItem,
                pdfBusy && styles.actionItemBusy,
                pressed && !pdfBusy && styles.actionItemPressed,
              ]}
            >
              {pdfBusy ? (
                <ActivityIndicator size="small" color={theme.colors.cta} />
              ) : (
                <Text style={[styles.actionText, isRTL && styles.rtl]}>{language === "he" ? "צור PDF" : "Generate PDF"}</Text>
              )}
            </Pressable>
          ) : null}
          {needsMethod
            ? DOCUMENT_PAYMENT_METHOD_KEYS.map((m) => (
                <Pressable
                  key={m}
                  onPress={() =>
                    void setDocumentPaymentMethod(item.id, m).then((res) =>
                      autoGenerateDocumentPdfIfReady(item.id, "ACTIVE", {
                        needsPdf: res.needs_pdf,
                        allowOverwrite: !settings?.is_operational,
                      }).finally(() => load())
                    )
                  }
                  style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}
                >
                  <Text style={[styles.actionText, isRTL && styles.rtl]}>
                    {documentPaymentMethodLabel(m, lang)}
                  </Text>
                </Pressable>
              ))
            : null}
          {isManager && !settings?.is_operational && item.pdf_url ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={pdfBusy}
                onPress={() => void regeneratePdf(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  pdfBusy && styles.actionItemBusy,
                  pressed && !pdfBusy && styles.actionItemPressed,
                ]}
              >
                {pdfBusy ? (
                  <ActivityIndicator size="small" color={theme.colors.cta} />
                ) : (
                  <Text style={[styles.actionText, isRTL && styles.rtl]}>{language === "he" ? "PDF מחדש" : "Regen"}</Text>
                )}
              </Pressable>
            </>
          ) : null}
          {isManager && item.customer_email && item.pdf_url ? (
            <>
              <View style={styles.actionSep} />
              <Pressable onPress={() => void sendEmail(item)} style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}>
                <Text style={[styles.actionText, isRTL && styles.rtl]}>{language === "he" ? "שליחה" : "Send"}</Text>
              </Pressable>
            </>
          ) : null}
          {isManager && item.pdf_url && item.status === "ACTIVE" ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={accountantBusy}
                onPress={() => void sendToAccountant(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  accountantBusy && styles.actionItemBusy,
                  pressed && !accountantBusy && styles.actionItemPressed,
                ]}
              >
                {accountantBusy ? (
                  <ActivityIndicator size="small" color={theme.colors.cta} />
                ) : (
                  <Text style={[styles.actionText, isRTL && styles.rtl]}>
                    {language === "he" ? "לרו״ח" : "Accountant"}
                  </Text>
                )}
              </Pressable>
            </>
          ) : null}
          {canCancelDocument && item.status === "ACTIVE" ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={cancelBusyId === item.id}
                onPress={() => confirmCancelReceipt(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  styles.actionItemDanger,
                  cancelBusyId === item.id && styles.actionItemBusy,
                  pressed && cancelBusyId !== item.id && styles.actionItemPressed,
                ]}
              >
                {cancelBusyId === item.id ? (
                  <ActivityIndicator size="small" color={theme.colors.error} />
                ) : (
                  <Text style={[styles.actionTextDanger, isRTL && styles.rtl]}>{language === "he" ? "ביטול" : "Cancel"}</Text>
                )}
              </Pressable>
            </>
          ) : null}
          {isManager && !settings?.is_operational ? (
            <>
              <View style={styles.actionSep} />
              <Pressable
                disabled={deleteDocBusyId === item.id}
                onPress={() => confirmDeleteReceipt(item)}
                style={({ pressed }) => [
                  styles.actionItem,
                  styles.actionItemDanger,
                  deleteDocBusyId === item.id && styles.actionItemBusy,
                  pressed && deleteDocBusyId !== item.id && styles.actionItemPressed,
                ]}
              >
                {deleteDocBusyId === item.id ? (
                  <ActivityIndicator size="small" color={theme.colors.error} />
                ) : (
                  <Text style={[styles.actionTextDanger, isRTL && styles.rtl]}>{language === "he" ? "מחיקה" : "Delete"}</Text>
                )}
              </Pressable>
            </>
          ) : null}
        </View>
      </View>
      </FadeSlideIn>
    );
  }

  const pageHeader = (
    <View style={styles.headerBlock}>
      <Text style={[styles.pageTitle, isRTL && styles.rtl]}>{t("menu.documentsInvoices")}</Text>
      <Text style={[styles.pageHint, isRTL && styles.rtl]}>
        {language === "he"
          ? "הפקה, ניהול ודיווח של קבלות וחשבוניות בעברית."
          : "Issue, manage, and report Hebrew receipts and invoices."}
      </Text>
      <HubTabs tabs={visibleTabs} active={section} onChange={setSection} />
      {!settings?.is_operational && settings?.digital_receipts_enabled ? (
        <View style={styles.testingBanner}>
          <Text style={[styles.testingText, isRTL && styles.rtl]}>
            {language === "he"
              ? "מצב בדיקה — ניתן לבטל קבלות וליצור PDF מחדש"
              : "Testing mode — void receipts and regenerate PDFs"}
          </Text>
        </View>
      ) : null}
    </View>
  );

  const settingsContent = (
    <ScrollView contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">
      {pageHeader}
      <GoLiveReadinessSection isRTL={isRTL} language={lang} />
      <ReceiptRequirementsTestingSection
        isRTL={isRTL}
        language={lang}
        addressLabel={t("profile.address")}
        zipLabel={t("profile.zipCode")}
        consentEnabled={!!settingsForm.request_consent_from_existing_users}
        addressEnabled={!!settingsForm.request_address_from_existing_users}
      />

      <SectionCard label={language === "he" ? "מערכת" : "System"}>
        <ToggleRow
          isRTL={isRTL}
          title={language === "he" ? "הפעלת קבלות דיגיטליות" : "Enable digital receipts"}
          subtitle={language === "he" ? "מאפשר הפקת מסמכים חדשים" : "Allows creating new documents"}
          value={!!settingsForm.digital_receipts_enabled}
          onChange={(v) => setSettingsForm((s) => ({ ...s, digital_receipts_enabled: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={language === "he" ? "מערכת פעילה" : "Operational mode"}
          subtitle={
            language === "he"
              ? "PDFים הופכים לבלתי ניתנים לשינוי; ביטול קבלות נחסם"
              : "Locks PDFs and blocks voiding receipts"
          }
          value={!!settingsForm.is_operational}
          onChange={(v) => setSettingsForm((s) => ({ ...s, is_operational: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={language === "he" ? "בקשת הסכמה לקבלות ממשתמשים קיימים" : "Request electronic receipt consent"}
          subtitle={
            language === "he"
              ? "מתאמנים ומנהלים יתבקשו לאשר את הסכמת הקבלות האלקטרוניות בעת כניסה"
              : "Existing athletes and managers are prompted to accept electronic receipt consent when they open the app"
          }
          value={!!settingsForm.request_consent_from_existing_users}
          onChange={(v) => setSettingsForm((s) => ({ ...s, request_consent_from_existing_users: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={language === "he" ? "בקשת כתובת ממשתמשים קיימים" : "Request address from existing users"}
          subtitle={
            language === "he"
              ? "מתאמנים ומנהלים שנרשמו לפני שנדרשה כתובת יתבקשו למלא כתובת ומיקוד בעת כניסה"
              : "Existing athletes and managers are prompted for street address and zip when they open the app"
          }
          value={!!settingsForm.request_address_from_existing_users}
          onChange={(v) => setSettingsForm((s) => ({ ...s, request_address_from_existing_users: v }))}
        />
        <View style={styles.cardDivider} />
        <ToggleRow
          isRTL={isRTL}
          title={language === "he" ? "צוות יכול לבטל" : "Staff can cancel"}
          value={!!settingsForm.staff_can_cancel_documents}
          onChange={(v) => setSettingsForm((s) => ({ ...s, staff_can_cancel_documents: v }))}
        />
      </SectionCard>

      <SectionCard label={language === "he" ? "מע״מ ומספור" : "VAT & numbering"}>
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{language === "he" ? "אחוז מע״מ" : "VAT %"}</Text>
        <TextInput
          value={String(Math.round((settingsForm.vat_rate ?? 0.18) * 10000) / 100)}
          onChangeText={(v) => {
            const n = parseMoney(v);
            if (n != null) setSettingsForm((s) => ({ ...s, vat_rate: n / 100 }));
          }}
          keyboardType="decimal-pad"
          style={[styles.input, isRTL && styles.rtlInput]}
        />
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{language === "he" ? "קידומת מסמך" : "Document prefix"}</Text>
        <TextInput
          value={String(settingsForm.document_prefix ?? "")}
          onChangeText={(v) => setSettingsForm((s) => ({ ...s, document_prefix: v }))}
          style={[styles.input, isRTL && styles.rtlInput]}
          autoCapitalize="characters"
        />
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>
          {language === "he" ? "מספר המסמך הבא" : "Next document number"}
        </Text>
        {settingsForm.is_operational ? (
          <Text style={[styles.filterHint, isRTL && styles.rtl]}>
            {language === "he"
              ? `${settingsForm.next_document_number ?? "—"} (ניתן לשינוי רק לפני מעבר למצב תפעולי)`
              : `${settingsForm.next_document_number ?? "—"} (only changeable before going operational)`}
          </Text>
        ) : (
          <TextInput
            value={String(settingsForm.next_document_number ?? "")}
            onChangeText={(v) => {
              const n = Number.parseInt(v, 10);
              setSettingsForm((s) => ({ ...s, next_document_number: Number.isFinite(n) ? n : undefined }));
            }}
            keyboardType="number-pad"
            style={[styles.input, isRTL && styles.rtlInput]}
          />
        )}
      </SectionCard>

      <SectionCard label={language === "he" ? "פרטי עסק" : "Business details"}>
        {(
          [
            ["business_name", language === "he" ? "שם העסק" : "Business name"],
            ["business_id", language === "he" ? "ע.פ" : "Business ID"],
            ["address", language === "he" ? "כתובת" : "Address"],
            ["phone", language === "he" ? "טלפון" : "Phone"],
            ["email", language === "he" ? "אימייל" : "Email"],
            ["accountant_email", language === "he" ? "אימייל רו״ח" : "Accountant email"],
          ] as const
        ).map(([key, label]) => (
          <View key={key} style={styles.fieldBlock}>
            <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{label}</Text>
            <TextInput
              value={String(settingsForm[key] ?? "")}
              onChangeText={(v) => setSettingsForm((s) => ({ ...s, [key]: v }))}
              style={[styles.input, isRTL && styles.rtlInput]}
              keyboardType={key === "email" || key === "accountant_email" ? "email-address" : key === "phone" ? "phone-pad" : "default"}
            />
          </View>
        ))}
      </SectionCard>

      <SectionCard label={language === "he" ? "הסכמה לקבלות אלקטרוניות" : "Electronic receipt consent"}>
        <Text style={[styles.fieldHint, isRTL && styles.rtl]}>
          {language === "he"
            ? "טקסט זה מוצג כשבקשת הסכמה ממשתמשים קיימים פעילה. פרסום גרסה חדשה תחייב הסכמה מחדש."
            : "Shown when request consent from existing users is on. Publishing a new version requires re-consent."}
        </Text>
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{language === "he" ? "כותרת" : "Title"}</Text>
        <TextInput value={consentTitle} onChangeText={setConsentTitle} style={[styles.input, isRTL && styles.rtlInput]} />
        <Text style={[styles.fieldLabel, isRTL && styles.rtl]}>{language === "he" ? "גוף ההסכמה" : "Body"}</Text>
        <TextInput
          value={consentBody}
          onChangeText={setConsentBody}
          multiline
          style={[styles.input, styles.textArea, isRTL && styles.rtlInput]}
        />
        <PrimaryButton
          label={language === "he" ? "פרסום גרסה חדשה" : "Publish new version"}
          onPress={() =>
            void publishLegalDocument("electronic_receipts", consentTitle, consentBody).then((v) =>
              showToast({
                message: language === "he" ? `גרסה ${v} פורסמה` : `Version ${v} published`,
                variant: "success",
              })
            )
          }
        />
      </SectionCard>

      <PrimaryButton
        label={language === "he" ? "שמירת הגדרות" : "Save settings"}
        onPress={() => void saveSettings()}
        loading={savingSettings}
        loadingLabel={t("common.loading")}
      />
    </ScrollView>
  );

  const documentsListHeader = (
    <>
      {pageHeader}
      <View style={styles.card}>
        <Text style={[styles.cardLabel, isRTL && styles.rtl]}>{language === "he" ? "טווח תאריכים" : "Date range"}</Text>
        <ReportDateRangeControls start={dateStart} end={dateEnd} onChange={({ start, end }) => { setDateStart(start); setDateEnd(end); }} />
      </View>
      <View style={styles.filterCard}>
        <Text style={[styles.cardLabel, isRTL && styles.rtl]}>
          {language === "he" ? "סינון לפי שם" : "Filter by name"}
        </Text>
        <TextInput
          value={nameFilter}
          onChangeText={setNameFilter}
          placeholder={language === "he" ? "הקלידו שם לקוח…" : "Type customer name…"}
          placeholderTextColor={theme.colors.textSoft}
          style={[styles.input, isRTL && styles.rtlInput]}
          autoCapitalize="words"
          autoCorrect={false}
        />
        {nameFilter.trim() ? (
          <Text style={[styles.filterHint, isRTL && styles.rtl]}>
            {language === "he"
              ? `${filteredDocuments.length} מתוך ${documents.length} מסמכים`
              : `${filteredDocuments.length} of ${documents.length} documents`}
          </Text>
        ) : null}
      </View>
    </>
  );

  const reportsContent = (
    <ScrollView contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">
      {pageHeader}
      <View style={styles.card}>
        <Text style={[styles.cardLabel, isRTL && styles.rtl]}>{language === "he" ? "טווח תאריכים" : "Date range"}</Text>
        <ReportDateRangeControls start={dateStart} end={dateEnd} onChange={({ start, end }) => { setDateStart(start); setDateEnd(end); }} />
      </View>
      <View style={[styles.summaryRow, isRTL && styles.summaryRowRtl]}>
        <View style={styles.summaryStat}>
          <Text style={styles.summaryValue}>{Math.round(reportCountDisplay)}</Text>
          <Text style={styles.summaryLabel}>{language === "he" ? "מסמכים" : "Documents"}</Text>
        </View>
        <View style={styles.summaryDivider} />
        <View style={styles.summaryStat}>
          <Text style={styles.summaryValue}>{formatIls(reportGrossDisplay)}</Text>
          <Text style={styles.summaryLabel}>{language === "he" ? "סה״כ ברוטו" : "Gross total"}</Text>
        </View>
        <View style={styles.summaryDivider} />
        <View style={styles.summaryStat}>
          <Text style={styles.summaryValue}>{formatIls(reportVatDisplay)}</Text>
          <Text style={styles.summaryLabel}>{language === "he" ? "מע״מ" : "VAT"}</Text>
        </View>
      </View>
      <PrimaryButton label={language === "he" ? "ייצוא CSV לרו״ח" : "Export CSV"} onPress={exportCsv} />
      <PrimaryButton
        label={language === "he" ? "שלח הכל לרו״ח" : "Send all to accountant"}
        onPress={() => void sendAllToAccountant()}
        loading={bulkAccountantBusy}
        loadingLabel={t("common.loading")}
      />
      <PrimaryButton
        label={language === "he" ? "יצירת סיכום חודשי (PDF)" : "Generate monthly summary (PDF)"}
        onPress={() => void generateMonthlySummary()}
        loading={monthlySummaryBusy}
        loadingLabel={t("common.loading")}
        disabled={!isFullMonthRange}
      />
      {!isFullMonthRange ? (
        <Text style={[styles.filterHint, isRTL && styles.rtl]}>
          {language === "he"
            ? "בחרו טווח \"חודש\" כדי להפיק סיכום — סיכומים זמינים רק לחודשים קלנדריים מלאים."
            : "Switch the date range to \"Month\" mode to generate a summary — summaries are only available for full calendar months."}
        </Text>
      ) : null}
      {filteredMonthlySummaries.length > 0 ? (
        <View style={styles.card}>
          <Text style={[styles.cardLabel, isRTL && styles.rtl]}>
            {language === "he" ? "סיכומים חודשיים שנוצרו" : "Generated monthly summaries"}
          </Text>
          {filteredMonthlySummaries.map((row) => {
            const rowDeleting = deletingSummaryId === row.id;
            return (
              <View key={row.id} style={[styles.summaryHistoryRow, isRTL && styles.docHeadRtl]}>
                <Pressable onPress={() => void viewMonthlySummary(row)} style={{ flex: 1 }}>
                  <Text style={[styles.summaryHistoryPeriod, isRTL && styles.rtl]}>
                    {new Date(row.period_start).toLocaleDateString(language === "he" ? "he-IL" : "en-GB", {
                      timeZone: "Asia/Jerusalem",
                      day: "2-digit",
                      month: "short",
                      year: "numeric",
                    })}
                    {" – "}
                    {new Date(row.period_end).toLocaleDateString(language === "he" ? "he-IL" : "en-GB", {
                      timeZone: "Asia/Jerusalem",
                      day: "2-digit",
                      month: "short",
                      year: "numeric",
                    })}
                  </Text>
                  <Text style={[styles.summaryHistoryMeta, isRTL && styles.rtl]}>
                    {language === "he"
                      ? `${row.active_count} קבלות · ${formatIls(row.gross_total)}`
                      : `${row.active_count} receipts · ${formatIls(row.gross_total)}`}
                  </Text>
                </Pressable>
                <Pressable onPress={() => void viewMonthlySummary(row)} style={({ pressed }) => [styles.actionItem, pressed && styles.actionItemPressed]}>
                  <Text style={styles.summaryHistoryView}>{language === "he" ? "צפייה" : "View"}</Text>
                </Pressable>
                <Pressable
                  disabled={rowDeleting}
                  onPress={() => confirmDeleteMonthlySummary(row)}
                  style={({ pressed }) => [
                    styles.actionItem,
                    styles.actionItemDanger,
                    rowDeleting && styles.actionItemBusy,
                    pressed && !rowDeleting && styles.actionItemPressed,
                  ]}
                >
                  {rowDeleting ? (
                    <ActivityIndicator size="small" color={theme.colors.error} />
                  ) : (
                    <Text style={[styles.actionTextDanger, isRTL && styles.rtl]}>
                      {language === "he" ? "מחיקה" : "Delete"}
                    </Text>
                  )}
                </Pressable>
              </View>
            );
          })}
        </View>
      ) : null}
    </ScrollView>
  );

  return (
    <View style={styles.screen}>
      <Stack.Screen options={{ title: t("menu.documentsInvoices") }} />
      <ManagerMoneyHubTabs />

      <CrossfadeSwap
        loading={loading}
        style={styles.tabPanel}
        skeleton={
          <View style={styles.loaderSkeletonList}>
            <ListRowSkeleton />
            <ListRowSkeleton />
            <ListRowSkeleton />
          </View>
        }
      >
      {section === "pending" ? (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          <PendingReceiptsPanel
            enabled={!!settings?.digital_receipts_enabled}
            header={pageHeader}
            onCreated={() => load()}
            testingMode={!settings?.is_operational}
          />
        </FadeSlideIn>
      ) : section === "reports" && isManager ? (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          {reportsContent}
        </FadeSlideIn>
      ) : section === "settings" && isManager ? (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          {settingsContent}
        </FadeSlideIn>
      ) : (
        <FadeSlideIn key={section} style={styles.tabPanel}>
          <FlatList
            style={styles.list}
            data={filteredDocuments}
            keyExtractor={(x) => x.id}
            renderItem={renderDocumentItem}
            ListHeaderComponent={documentsListHeader}
            ListEmptyComponent={
              <View style={styles.emptyBox}>
                <Text style={[styles.emptyTitle, isRTL && styles.rtl]}>
                  {nameFilter.trim()
                    ? language === "he"
                      ? "אין מסמכים לשם זה"
                      : "No documents for this name"
                    : language === "he"
                      ? "אין מסמכים בטווח"
                      : "No documents in range"}
                </Text>
                <Text style={[styles.emptyHint, isRTL && styles.rtl]}>
                  {nameFilter.trim()
                    ? language === "he"
                      ? "נסו שם אחר או נקו את הסינון."
                      : "Try another name or clear the filter."
                    : language === "he"
                      ? "נסו טווח תאריכים רחב יותר או הפיקו מסמך חדש."
                      : "Try a wider date range or create a new document."}
                </Text>
              </View>
            }
            refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor={theme.colors.cta} />}
            contentContainerStyle={styles.listContent}
          />
        </FadeSlideIn>
      )}
      </CrossfadeSwap>

      <EditCustomerEmailModal
        visible={editEmailDoc != null}
        documentId={editEmailDoc?.id ?? null}
        customerName={editEmailDoc?.customer_name ?? ""}
        initialEmail={editEmailDoc?.customer_email ?? null}
        onClose={() => setEditEmailDoc(null)}
        onSaved={async () => {
          await load();
          showToast({ message: language === "he" ? "אימייל עודכן" : "Email updated", variant: "success" });
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.backgroundAlt },
  tabPanel: { flex: 1 },
  list: { flex: 1 },
  listContent: { paddingHorizontal: theme.spacing.md, paddingBottom: theme.spacing.xl, gap: theme.spacing.sm },
  scrollContent: { paddingHorizontal: theme.spacing.md, paddingBottom: theme.spacing.xl, gap: theme.spacing.md },
  loaderSkeletonList: { padding: theme.spacing.md, gap: theme.spacing.sm },
  headerBlock: { paddingTop: theme.spacing.sm, gap: theme.spacing.xs, marginBottom: theme.spacing.sm },
  pageTitle: { fontSize: 22, fontWeight: "800", color: theme.colors.text, letterSpacing: 0.2 },
  pageHint: { fontSize: 14, fontWeight: "500", color: theme.colors.textMuted, lineHeight: 20, marginBottom: theme.spacing.sm },
  testingBanner: {
    marginTop: theme.spacing.xs,
    backgroundColor: theme.colors.warningBg,
    borderWidth: 1,
    borderColor: theme.colors.warningBorder,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.md,
  },
  testingText: { color: theme.colors.warning, fontWeight: "700", fontSize: 13, textAlign: "center" },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  cardLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  cardDivider: { height: StyleSheet.hairlineWidth, backgroundColor: theme.colors.borderMuted, marginVertical: 4 },
  toggleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: theme.spacing.md, paddingVertical: 4 },
  toggleRowRtl: { flexDirection: "row-reverse" },
  toggleCopy: { flex: 1 },
  toggleTitle: { fontSize: 15, fontWeight: "700", color: theme.colors.text },
  toggleSub: { marginTop: 2, fontSize: 12, fontWeight: "500", color: theme.colors.textSoft, lineHeight: 17 },
  fieldBlock: { gap: 6 },
  fieldHint: { fontSize: 13, fontWeight: "500", color: theme.colors.textSoft, lineHeight: 19, marginBottom: theme.spacing.sm },
  fieldLabel: { fontSize: 13, fontWeight: "700", color: theme.colors.textMuted },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.radius.md,
    paddingVertical: 12,
    paddingHorizontal: theme.spacing.md,
    color: theme.colors.text,
    backgroundColor: theme.colors.surfaceElevated,
    fontSize: 15,
    fontWeight: "600",
  },
  textArea: { minHeight: 140, textAlignVertical: "top" },
  rtlInput: { textAlign: "right", writingDirection: "rtl" },
  createBtn: { marginBottom: theme.spacing.sm },
  disabledBox: {
    padding: theme.spacing.md,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    marginBottom: theme.spacing.sm,
  },
  disabledText: { color: theme.colors.textMuted, fontSize: 14, fontWeight: "600", lineHeight: 20 },
  docCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  docHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: theme.spacing.md },
  docHeadRtl: { flexDirection: "row-reverse" },
  docHeadMain: { flex: 1, minWidth: 0 },
  docTitleRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  docTitleRowRtl: { flexDirection: "row-reverse" },
  typeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  typeBadgeText: { fontSize: 10, fontWeight: "800", color: theme.colors.textMuted },
  docHeadEnd: { alignItems: "flex-end", gap: 6 },
  docNumber: { fontSize: 16, fontWeight: "800", color: theme.colors.text, letterSpacing: 0.2 },
  docCustomer: { marginTop: 2, fontSize: 14, fontWeight: "600", color: theme.colors.textMuted },
  docAmount: { fontSize: 18, fontWeight: "900", color: theme.colors.text },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: theme.radius.full },
  badgeActive: { backgroundColor: theme.colors.successBg },
  badgeCancelled: { backgroundColor: theme.colors.errorBg },
  badgePending: { backgroundColor: theme.colors.warningBg },
  badgeText: { fontSize: 10, fontWeight: "800", color: theme.colors.text, letterSpacing: 0.2 },
  docMeta: { marginTop: theme.spacing.sm, fontSize: 13, fontWeight: "500", color: theme.colors.textSoft, lineHeight: 18 },
  warnBox: {
    marginTop: theme.spacing.sm,
    padding: theme.spacing.sm,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.warningBg,
    borderWidth: 1,
    borderColor: theme.colors.warningBorder,
  },
  warnText: { fontSize: 12, fontWeight: "700", color: theme.colors.warning },
  warnAction: { marginTop: 6, alignSelf: "flex-start" },
  warnActionText: { fontSize: 12, fontWeight: "800", color: theme.colors.cta },
  filterCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
  },
  filterHint: { fontSize: 12, fontWeight: "600", color: theme.colors.textSoft },
  actionBar: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", marginTop: theme.spacing.md, gap: 2 },
  actionBarRtl: { flexDirection: "row-reverse" },
  actionItem: { paddingVertical: 8, paddingHorizontal: 10, borderRadius: theme.radius.md },
  actionItemPressed: { backgroundColor: theme.colors.surfaceElevated },
  actionItemBusy: { opacity: 0.65 },
  actionItemDanger: {},
  actionSep: { width: StyleSheet.hairlineWidth, height: 16, backgroundColor: theme.colors.borderMuted, marginHorizontal: 2 },
  actionText: { fontSize: 13, fontWeight: "800", color: theme.colors.text },
  actionTextDanger: { fontSize: 13, fontWeight: "800", color: theme.colors.error },
  summaryHistoryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.sm,
    paddingVertical: 8,
    borderRadius: theme.radius.md,
  },
  summaryHistoryPeriod: { fontSize: 14, fontWeight: "700", color: theme.colors.text },
  summaryHistoryMeta: { fontSize: 12, fontWeight: "600", color: theme.colors.textSoft, marginTop: 2 },
  summaryHistoryView: { fontSize: 13, fontWeight: "800", color: theme.colors.primary },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  summaryRowRtl: { flexDirection: "row-reverse" },
  summaryStat: { flex: 1, alignItems: "center" },
  summaryDivider: { width: StyleSheet.hairlineWidth, alignSelf: "stretch", backgroundColor: theme.colors.borderMuted },
  summaryValue: { fontSize: 17, fontWeight: "900", color: theme.colors.text },
  summaryLabel: { marginTop: 2, fontSize: 10, fontWeight: "700", color: theme.colors.textSoft, textTransform: "uppercase", letterSpacing: 0.25 },
  reportRow: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    padding: theme.spacing.md,
    gap: 4,
  },
  reportHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  reportHeadRtl: { flexDirection: "row-reverse" },
  reportNumber: { fontSize: 15, fontWeight: "800", color: theme.colors.text },
  reportAmount: { fontSize: 16, fontWeight: "900", color: theme.colors.text },
  reportMeta: { fontSize: 13, fontWeight: "500", color: theme.colors.textSoft },
  emptyBox: {
    paddingVertical: theme.spacing.xl,
    paddingHorizontal: theme.spacing.lg,
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  emptyTitle: { fontSize: 16, fontWeight: "800", color: theme.colors.text },
  emptyHint: { fontSize: 14, fontWeight: "500", color: theme.colors.textMuted, textAlign: "center", lineHeight: 20 },
  rtl: { textAlign: "right", writingDirection: "rtl" },
});
