import { StyleSheet } from "react-native";
import { theme } from "../theme";

export const participantHistoryStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.backgroundAlt },
  rtlText: { textAlign: "right", writingDirection: "rtl" },
  ltrText: { textAlign: "left", writingDirection: "ltr" },
  filters: {
    margin: theme.spacing.md,
    padding: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: theme.radius.lg,
  },
  familyBanner: {
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    padding: theme.spacing.md,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    gap: theme.spacing.sm,
  },
  familyBannerHead: { gap: 2 },
  familyBannerTitle: { fontSize: 17, fontWeight: "900", color: theme.colors.text, lineHeight: 22 },
  familyBannerMeta: { fontSize: 12, fontWeight: "600", color: theme.colors.textMuted, lineHeight: 17 },
  familyMembersPanel: {
    paddingTop: theme.spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
    gap: 8,
  },
  familyMembersLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  familyMemberCard: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    gap: 4,
  },
  familyMemberMain: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  familyMemberMainRtl: { flexDirection: "row-reverse" },
  familyMemberName: { flexShrink: 1, fontSize: 14, fontWeight: "800", color: theme.colors.text },
  familyMemberBadge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.accent,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  familyMemberBadgeTxt: { fontSize: 10, fontWeight: "800", color: theme.colors.textSoft },
  familyMemberPhone: { fontSize: 13, fontWeight: "600", color: theme.colors.textMuted },
  familyMemberPhoneRtl: { textAlign: "right", writingDirection: "ltr", alignSelf: "stretch" },
  sessionMemberName: { fontWeight: "800", color: theme.colors.text },
  screenTitle: { fontSize: 18, fontWeight: "900", color: theme.colors.text, marginBottom: theme.spacing.sm },
  label: { marginTop: theme.spacing.sm, fontWeight: "600", color: theme.colors.text, fontSize: 13 },
  hint: { marginTop: theme.spacing.sm, fontSize: 12, color: theme.colors.textMuted, lineHeight: 18 },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.borderInput,
    borderRadius: theme.radius.md,
    padding: 12,
    marginTop: 6,
    fontSize: 16,
    backgroundColor: theme.colors.white,
    color: theme.colors.textOnLight,
  },
  pickerTouch: {
    borderWidth: 1,
    borderColor: theme.colors.borderInput,
    borderRadius: theme.radius.md,
    padding: 12,
    marginTop: theme.spacing.sm,
    backgroundColor: theme.colors.white,
    minHeight: 48,
    justifyContent: "center",
  },
  pickerText: { fontSize: 16, color: theme.colors.textOnLight },
  pickerPlaceholder: { fontSize: 16, color: theme.colors.textSoftOnLight },
  clearSel: { marginTop: 8, alignSelf: "flex-start" },
  clearSelTxt: { color: theme.colors.textMuted, fontWeight: "700" },
  loadingBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    paddingVertical: 10,
  },
  loadingBannerTxt: { fontSize: 13, fontWeight: "600", color: theme.colors.textMuted },
  modalBackdrop: { flex: 1, justifyContent: "flex-end" },
  modalBackdropTouch: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)" },
  modalBox: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    maxHeight: "75%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: theme.spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderMuted,
  },
  modalTitle: { fontSize: 18, fontWeight: "800", color: theme.colors.text },
  modalClose: { fontSize: 16, color: theme.colors.textMuted, fontWeight: "800" },
  modalSearchField: { marginHorizontal: theme.spacing.md, marginBottom: theme.spacing.sm },
  modalLoader: { padding: theme.spacing.xl },
  pickerItem: {
    paddingVertical: 14,
    paddingHorizontal: theme.spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderMuted,
  },
  pickerItemName: { fontSize: 16, fontWeight: "700", color: theme.colors.text },
  pickerItemRole: { fontSize: 13, color: theme.colors.textMuted, marginTop: 4 },
  pickerEmpty: { padding: theme.spacing.lg, color: theme.colors.textSoft, textAlign: "center" },
  list: { flex: 1 },
  listContent: { paddingBottom: theme.spacing.xl, flexGrow: 1 },
  sectionHead: {
    backgroundColor: theme.colors.surfaceElevated,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.radius.lg,
    marginHorizontal: theme.spacing.md,
  },
  sectionHeadRtl: { alignItems: "flex-end" },
  sectionTitle: { fontSize: 14, fontWeight: "800", color: theme.colors.text },
  row: {
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.sm,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    overflow: "hidden",
  },
  sessionCardBody: {
    paddingHorizontal: theme.spacing.md,
    paddingTop: 14,
    paddingBottom: 12,
    gap: 0,
  },
  sessionCardBodyRtl: { alignItems: "stretch" },
  sessionCardBodyPressed: { opacity: 0.92, backgroundColor: theme.colors.surfaceElevated },
  sessionCardBodyWeb: { cursor: "pointer" } as const,
  sessionHeadRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 14 },
  sessionHeadRowRtl: { flexDirection: "row-reverse" },
  sessionHeadMain: { flex: 1, minWidth: 0, gap: 4 },
  sessionHeadMainFlex: { flex: 1, minWidth: 0 },
  sessionHeadMainRtl: { alignItems: "stretch" },
  sessionHeadTextHe: { alignSelf: "stretch", textAlign: "right", writingDirection: "rtl" },
  sessionHeadTimeHe: { writingDirection: "ltr", textAlign: "right" },
  sessionHeadAside: {
    alignItems: "flex-end",
    justifyContent: "flex-start",
    gap: 6,
    flexShrink: 0,
    minWidth: 96,
    maxWidth: "40%",
    paddingTop: 1,
  },
  sessionHeadAsideHe: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 6,
    flexShrink: 0,
    minWidth: 96,
    maxWidth: "40%",
    paddingTop: 1,
  },
  sessionMetaAside: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.textMuted,
    textAlign: "right",
    lineHeight: 16,
  },
  sessionMetaAsideHe: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.textMuted,
    textAlign: "left",
    lineHeight: 16,
    alignSelf: "flex-start",
  },
  cardDatePrimary: { fontSize: 15, fontWeight: "800", color: theme.colors.text, lineHeight: 21 },
  cardDateMeta: { fontSize: 14, fontWeight: "600", color: theme.colors.textMuted, lineHeight: 20 },
  sessionSubline: { fontSize: 13, color: theme.colors.textMuted, lineHeight: 18 },
  payPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: theme.radius.full,
    borderWidth: 1,
  },
  payPillRtl: { flexDirection: "row-reverse" },
  payPillPaid: { backgroundColor: theme.colors.successBg, borderColor: "rgba(34, 197, 94, 0.35)" },
  payPillUnpaid: { backgroundColor: theme.colors.warningBg, borderColor: theme.colors.warningBorder },
  payPillMuted: { backgroundColor: theme.colors.surfaceElevated, borderColor: theme.colors.borderMuted },
  payPillTxt: { fontSize: 12, fontWeight: "800" },
  payPillTxtPaid: { color: theme.colors.success },
  payPillTxtUnpaid: { color: theme.colors.warning },
  payPillTxtMuted: { color: theme.colors.textMuted },
  payPillAmt: { fontSize: 12, fontWeight: "900", color: theme.colors.success },
  sessionFootnoteRow: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
  },
  sessionFootnote: { fontSize: 12, fontWeight: "600", color: theme.colors.textMuted, lineHeight: 17 },
  sessionAmount: { fontSize: 17, fontWeight: "800", color: theme.colors.success, flexShrink: 0 },
  actionBar: {
    flexDirection: "row",
    alignItems: "stretch",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
  },
  actionBarRtl: { flexDirection: "row-reverse" },
  actionBarInset: { borderTopWidth: 0, borderRadius: theme.radius.md, overflow: "hidden" },
  actionBarItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 13,
    paddingHorizontal: 8,
    minHeight: 46,
  },
  actionBarItemWide: { flex: 1.35 },
  actionBarItemDanger: {},
  actionBarItemActive: { backgroundColor: theme.colors.cta },
  actionBarItemPressed: { opacity: 0.88 },
  actionBarSep: { width: StyleSheet.hairlineWidth, backgroundColor: theme.colors.borderMuted },
  actionBarLabel: { fontSize: 13, fontWeight: "600", color: theme.colors.text },
  actionBarLabelActive: { color: theme.colors.ctaText, fontWeight: "700" },
  actionBarLabelDanger: { fontSize: 13, fontWeight: "600", color: theme.colors.error },
  actionBarChevron: { fontSize: 10, color: theme.colors.textSoft, marginTop: 1 },
  attPicker: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: theme.spacing.md,
    paddingTop: 4,
    paddingBottom: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
  },
  attPickerRtl: { flexDirection: "row-reverse" },
  attPickerOpt: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surfaceElevated,
  },
  attPickerOptOn: { backgroundColor: theme.colors.cta },
  attPickerTxt: { fontSize: 12, fontWeight: "600", color: theme.colors.textMuted },
  attPickerTxtOn: { color: theme.colors.ctaText, fontWeight: "700" },
  cardInset: {
    paddingHorizontal: theme.spacing.md,
    paddingBottom: theme.spacing.sm,
    gap: 6,
  },
  cardInsetLabel: { fontSize: 11, fontWeight: "600", color: theme.colors.textSoft },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  cardTopRtl: { flexDirection: "row-reverse" },
  cardDate: { fontSize: 16, fontWeight: "700", color: theme.colors.text, flexShrink: 1 },
  cardMeta: { fontSize: 12, color: theme.colors.textMuted, lineHeight: 16 },
  cardNote: { fontSize: 13, color: theme.colors.textMuted, lineHeight: 18 },
  cardDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: theme.colors.borderMuted,
    marginTop: 2,
  },
  cardSpinner: { marginVertical: 6 },
  cardLinks: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 4 },
  cardLinksRtl: { flexDirection: "row-reverse" },
  cardLinkHit: { paddingVertical: 2 },
  cardLink: { fontSize: 13, fontWeight: "800", color: theme.colors.cta },
  cardLinkDanger: { color: theme.colors.error },
  cardLinkSep: { fontSize: 13, color: theme.colors.textSoft, fontWeight: "700" },
  cardPaymentSummary: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  cardPaymentSummaryRtl: { flexDirection: "row-reverse" },
  cardPaymentAmount: { fontSize: 16, fontWeight: "900", color: theme.colors.success },
  cardPaymentMethod: { fontSize: 13, fontWeight: "700", color: theme.colors.textMuted },
  cardPaymentFoot: {
    paddingTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
    gap: 4,
  },
  cardPaymentFootPaid: {},
  cardUnpaid: { fontSize: 13, color: theme.colors.textMuted, lineHeight: 18 },
  cardSubsection: { gap: 8, paddingHorizontal: theme.spacing.md, paddingBottom: theme.spacing.sm },
  cardSubLabel: { fontSize: 12, fontWeight: "800", color: theme.colors.textMuted },
  badgeInline: { alignSelf: "flex-start", marginTop: 0 },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.radius.full,
    flexShrink: 0,
  },
  badgeOn: { backgroundColor: theme.colors.successBg },
  badgeOff: { backgroundColor: theme.colors.surfaceElevated, borderWidth: 1, borderColor: theme.colors.borderMuted },
  badgeTxt: { fontSize: 11, fontWeight: "800" },
  badgeTxtOn: { color: theme.colors.success },
  badgeTxtOff: { color: theme.colors.textMuted },
  badgeAtt: {},
  badgeAttYes: { backgroundColor: theme.colors.successBg, borderWidth: 0 },
  badgeAttTxtYes: { color: theme.colors.success },
  badgeAttNo: { backgroundColor: theme.colors.errorBg, borderWidth: 1, borderColor: theme.colors.errorBorder },
  badgeAttTxtNo: { color: theme.colors.error },
  badgeAttUnset: { backgroundColor: theme.colors.surfaceElevated, borderWidth: 1, borderColor: theme.colors.borderMuted },
  badgeAttTxtUnset: { color: theme.colors.textMuted },
  badgeLate: { marginTop: 6, backgroundColor: theme.colors.errorBg, borderWidth: 1, borderColor: theme.colors.errorBorder },
  badgeLateTxt: { color: theme.colors.error },
  badgeLateOk: { marginTop: 6, backgroundColor: theme.colors.surfaceElevated, borderWidth: 1, borderColor: theme.colors.borderMuted },
  badgeLateOkTxt: { color: theme.colors.textMuted },
  noShowPolicyBlock: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderMuted,
  },
  noShowPolicyBlockRtl: { alignItems: "stretch" },
  noShowPolicyLabel: { fontSize: 12, fontWeight: "800", color: theme.colors.textMuted, marginBottom: 8 },
  policySeg: { flexDirection: "row", gap: 8 },
  policySegRtl: { flexDirection: "row-reverse" },
  lateFeeSegMargin: { marginTop: 10 },
  policyBtn: {
    flex: 1,
    paddingVertical: 7,
    paddingHorizontal: 6,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    alignItems: "center",
  },
  policyBtnOn: { backgroundColor: theme.colors.cta, borderColor: theme.colors.cta },
  policyBtnTxt: { fontSize: 12, fontWeight: "800", color: theme.colors.textMuted },
  policyBtnTxtOn: { color: theme.colors.ctaText },
  empty: { textAlign: "center", color: theme.colors.textSoft, padding: theme.spacing.xl, fontSize: 14 },
  billingCard: {
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    padding: theme.spacing.md,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    gap: 8,
  },
  billingTitle: { fontSize: 13, fontWeight: "900", color: theme.colors.textMuted, letterSpacing: 0.3, textTransform: "uppercase" },
  billingStatGrid: { flexDirection: "row", gap: 8 },
  billingStatGridRtl: { flexDirection: "row-reverse" },
  billingStatTile: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 68,
  },
  billingStatTileOwed: { borderColor: theme.colors.errorBorder, backgroundColor: theme.colors.errorBg },
  billingStatTileCredit: { borderColor: "rgba(34,197,94,0.35)", backgroundColor: theme.colors.successBg },
  billingStatLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: theme.colors.textMuted,
    letterSpacing: 0.25,
    textTransform: "uppercase",
    textAlign: "center",
  },
  billingStatValue: { fontSize: 15, fontWeight: "900", color: theme.colors.text, textAlign: "center", lineHeight: 18 },
  billingStatValueOwed: { color: theme.colors.error },
  billingStatValueCredit: { color: theme.colors.success },
  billingMethodsBlock: { gap: 6, marginTop: 2 },
  billingMethodsTitle: { fontSize: 10, fontWeight: "800", color: theme.colors.textMuted, letterSpacing: 0.25, textTransform: "uppercase" },
  billingMethodGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  billingMethodGridRtl: { flexDirection: "row-reverse" },
  billingMethodTile: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
    alignItems: "center",
    gap: 2,
    minWidth: 72,
  },
  billingMethodLabel: { fontSize: 10, fontWeight: "800", color: theme.colors.textMuted, textAlign: "center" },
  billingMethodValue: { fontSize: 13, fontWeight: "900", color: theme.colors.text, textAlign: "center" },
  billingWarn: { fontSize: 12, color: theme.colors.textSoft, marginTop: 4, lineHeight: 17 },
  addPayBtn: {
    marginTop: 8,
    alignSelf: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.cta,
  },
  addPayBtnTxt: { color: theme.colors.ctaText, fontWeight: "900", fontSize: 13 },
  addPayBody: { padding: theme.spacing.md, gap: 8, paddingBottom: theme.spacing.lg },
  inputLight: {
    borderWidth: 1,
    borderColor: theme.colors.borderInput,
    borderRadius: theme.radius.md,
    padding: 12,
    fontSize: 16,
    backgroundColor: theme.colors.white,
    color: theme.colors.textOnLight,
  },
  methodRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  methodChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
  },
  methodChipOn: { backgroundColor: theme.colors.cta, borderColor: theme.colors.cta },
  methodChipTxt: { fontSize: 12, fontWeight: "800", color: theme.colors.text },
  methodChipTxtOn: { color: theme.colors.ctaText },
  paymentRow: { borderLeftWidth: 3, borderLeftColor: theme.colors.success },
  paymentStatusRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  paymentStatusRowRtl: { flexDirection: "row-reverse" },
  paymentPaidAmount: { fontSize: 18, fontWeight: "900", color: theme.colors.success },
  paymentMethodLine: { fontSize: 14, fontWeight: "700", color: theme.colors.text, marginTop: 4 },
  paymentMethodCash: { color: theme.colors.success },
  paymentMethodOther: { color: "#ca8a04" },
  paymentRecordedBy: { fontSize: 12, color: theme.colors.textMuted, marginTop: 4, lineHeight: 17 },
  paymentUnpaidHint: { fontSize: 13, color: theme.colors.textMuted, marginTop: 4, lineHeight: 18 },
  sessionPaymentBlock: {
    marginTop: 8,
    padding: 10,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    gap: 2,
  },
  sessionPaymentBlockPaid: {
    backgroundColor: "rgba(34, 197, 94, 0.08)",
    borderColor: "rgba(34, 197, 94, 0.35)",
  },
  sessionPaymentBlockUnpaid: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.borderMuted,
  },
  badgePayment: { backgroundColor: "rgba(96, 165, 250, 0.15)", borderWidth: 1, borderColor: theme.colors.cta },
  badgeTxtPayment: { color: theme.colors.cta },
  paymentRowHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    width: "100%",
  },
  paymentRowHeadRtl: { flexDirection: "row-reverse" },
  paymentRowActions: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 0 },
  paymentRowActionsRtl: { flexDirection: "row-reverse" },
  paymentRowDate: { flex: 1, minWidth: 0 },
  paymentEditBtn: { paddingVertical: 6, paddingHorizontal: 8 },
  paymentEditTxt: { fontSize: 13, fontWeight: "800", color: theme.colors.cta },
  paymentDeleteBtn: { paddingVertical: 6, paddingHorizontal: 8 },
  paymentDeleteTxt: { fontSize: 13, fontWeight: "800", color: theme.colors.error },
  inlineAction: {
    alignSelf: "flex-start",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    backgroundColor: theme.colors.surfaceElevated,
  },
  inlineActionTxt: { color: theme.colors.cta, fontWeight: "900", letterSpacing: 0.1 },
  rowActions: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  rowActionsRtl: { flexDirection: "row-reverse" },
  attendanceBlock: { marginTop: 10, gap: 6 },
  attendanceBlockRtl: { alignItems: "flex-end" },
  attendanceLabel: { fontSize: 12, fontWeight: "800", color: theme.colors.textMuted, letterSpacing: 0.2 },
  inlineActionDanger: {
    borderColor: "rgba(239, 68, 68, 0.35)",
    backgroundColor: "rgba(239, 68, 68, 0.08)",
  },
  inlineActionDangerTxt: { color: theme.colors.error, fontWeight: "900", letterSpacing: 0.1 },
});
