-- Monthly summary PDFs for the accountant: business details + total revenue for a period.
-- Generated by the generate-monthly-summary-pdf edge function (service role writes),
-- read/listed by managers.

create table public.monthly_summaries (
  id uuid primary key default gen_random_uuid(),
  period_start timestamptz not null,
  period_end timestamptz not null,
  document_count int not null default 0,
  active_count int not null default 0,
  cancelled_count int not null default 0,
  gross_total numeric(12, 2) not null default 0,
  net_total numeric(12, 2) not null default 0,
  vat_total numeric(12, 2) not null default 0,
  business_name text not null,
  business_id text not null,
  pdf_url text,
  pdf_hash text,
  sent_at timestamptz,
  sent_to text,
  delivery_status text,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles (user_id) on delete set null
);

create index monthly_summaries_created_at_idx on public.monthly_summaries (created_at desc);

alter table public.monthly_summaries enable row level security;

create policy "monthly_summaries_manager_select" on public.monthly_summaries
  for select using (public.is_manager(auth.uid()));

create or replace function public.list_monthly_summaries(p_limit int default 24)
returns json language plpgsql stable security definer set search_path = public as $$
declare v_rows json;
begin
  if auth.uid() is null then return json_build_object('ok', false, 'error', 'not_authenticated'); end if;
  if not public.is_manager(auth.uid()) then return json_build_object('ok', false, 'error', 'forbidden'); end if;
  select coalesce(json_agg(row_to_json(t) order by t.created_at desc), '[]'::json) into v_rows from (
    select * from public.monthly_summaries
    order by created_at desc limit greatest(1, least(coalesce(p_limit, 24), 100))
  ) t;
  return json_build_object('ok', true, 'rows', v_rows);
end; $$;

grant execute on function public.list_monthly_summaries(int) to authenticated;
