import { Platform } from "react-native";
import { supabase } from "./supabase";
import { loadNotificationPrefs } from "./notificationPrefs";

/** Converts the VAPID public key (base64url, as generated by `web-push`) to the raw bytes PushManager expects. */
function urlBase64ToUint8Array(base64Url: string): Uint8Array {
  const padding = "=".repeat((4 - (base64Url.length % 4)) % 4);
  const base64 = (base64Url + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(base64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  return bytes;
}

function isWebPushSupported(): boolean {
  return (
    Platform.OS === "web" &&
    typeof navigator !== "undefined" &&
    "serviceWorker" in navigator &&
    typeof window !== "undefined" &&
    "PushManager" in window
  );
}

async function removeCurrentSubscription(): Promise<void> {
  try {
    const registration = await navigator.serviceWorker.getRegistration("/sw.js");
    const existing = await registration?.pushManager.getSubscription();
    if (existing) {
      await supabase.from("web_push_subscriptions").delete().eq("endpoint", existing.endpoint);
      await existing.unsubscribe();
    }
  } catch {
    /* best-effort cleanup */
  }
}

/**
 * Web/PWA equivalent of syncExpoPushTokenIfNeeded — registers the service worker and
 * subscribes via the browser's Push API when notifications are enabled, storing the
 * subscription in `web_push_subscriptions` for the server to deliver to. No-ops on
 * native platforms and on browsers without Push API support (notably iOS Safari unless
 * the site has been added to the Home Screen).
 */
export async function syncWebPushSubscriptionIfNeeded(): Promise<void> {
  if (!isWebPushSupported()) return;

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return;

  const prefs = await loadNotificationPrefs();
  if (!prefs.sessionReminders && !prefs.waitlistAlerts) {
    await removeCurrentSubscription();
    return;
  }

  const vapidPublicKey = process.env.EXPO_PUBLIC_VAPID_PUBLIC_KEY;
  if (!vapidPublicKey) return;

  try {
    const permission = await Notification.requestPermission();
    if (permission !== "granted") return;

    const registration = await navigator.serviceWorker.register("/sw.js");
    await navigator.serviceWorker.ready;

    let subscription = await registration.pushManager.getSubscription();
    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(vapidPublicKey) as BufferSource,
      });
    }

    const key = subscription.getKey?.("p256dh");
    const authSecret = subscription.getKey?.("auth");
    if (!key || !authSecret) return;

    const toBase64Url = (buf: ArrayBuffer) =>
      btoa(String.fromCharCode(...new Uint8Array(buf)))
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=+$/, "");

    await supabase.from("web_push_subscriptions").upsert(
      {
        user_id: user.id,
        endpoint: subscription.endpoint,
        p256dh: toBase64Url(key),
        auth: toBase64Url(authSecret),
      },
      { onConflict: "endpoint" }
    );
  } catch {
    /* Permission denied, unsupported, or offline — ignore, matches Expo token sync behavior. */
  }
}
